### ISSUE TITLE
most effective way to start on boot

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#100]
I have been trying upstart and even tried a bash script with not luck to get it to start on boot any ideas?

**Comment by lokenx** [comment]
The simplest way is probably using [Meteor Up](https://github.com/arunoda/meteor-up) as it takes care of everything for you.

Alternatively I've seen upstart scripts you can use as a base over on [StackOverflow](http://stackoverflow.com/questions/15657071/how-to-run-meteor-on-startup-on-ubuntu-server). 

[Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-meteor-js-application-on-ubuntu-14-04-with-nginx) has a very comprehensive guide as well that also walks through setting up nginx.

Most information you will find involve running Meteor in production, not just using `meteor` in it's development state.

**Comment by camjac251** [comment]
Easiest I've found is Phusion Passenger, integrates directly with Apache or Nginx.

**Comment by unixjeff** [comment]
I ended up just deploying it via meteor.com

just run: meteor deploy myapp.meteor.com
and replace myapp with what ever you want and then you can go to https://myapp.meteor.com and its all set

**Comment by lokenx** [comment]
Deploying via Meteor works, just bearing in mind they do spin down apps if they're not actively been used. They spin them back up when someone navigates there, just sometimes takes a few seconds for it to get up to speed.

Hopefully once they've gotten the full product out we can use a similar setup for production class applications.
