### ISSUE TITLE
[BUG] Downloading meteor-tool@1.1.3

### ISSUE THREAD

**Issue by teshiburu** [lokenx/plexrequests-meteor#103]
This is what i get when i navigate to c:\plexrequest and "type" meteor into cmd prompt. 

I am running server 2008 r2 and meteor 1.1.3 

What am i doing wrong here?

**Comment by lokenx** [comment]
Downloading meteor tools is expected, there's nothing to be concerned about with that. Does it not finish or error out?

**Comment by teshiburu** [comment]
Lokenx - the download bar completes then it just has a rotating "/"

![image](https://cloud.githubusercontent.com/assets/7904118/9498411/92c74490-4c11-11e5-9b29-e228baf37196.png)

How long should this take?

**Comment by teshiburu** [comment]
Seems to have progressed past this stage now - freaking weird :P

**Comment by lokenx** [comment]
Not sure, that's meteor stuff nothing to do with my app. Just let it go, it only has to happen once and then you have it.

Sent on the go, forgive the typo!

**Comment by stephan2006** [comment]
Had the same issue. While I was finding this a windows firewall popup appeared for java. I let it thought and meteor continued.

Edit: Sorry I just noticed it was a closed topic. Sorry for reviving a dead thread.
