### ISSUE TITLE
[Question] When downloaded

### ISSUE THREAD

**Issue by krsandvik** [lokenx/plexrequests-meteor#105]
Is it possible to set the downloaded status automatically to true when then the show or move is downloaded? Now I have to do this manual, don't know if it is by design.

**Comment by lokenx** [comment]
It gets updated on a schedule, it's not possible to be instantaneous without constantly checking Couch Potato. Current it's set to check every 6 hours I believe. Change the status of a few that are completed to false and check back after 6 hours and see if they've updated.

**Comment by camjac251** [comment]
would be nice to check every minute or to have CP send to plexrequests a notification that it is complete

**Comment by lokenx** [comment]
It does check CP for status updates. It's currently set to update every 6 hours and won't be changing in this release. With the new release, I may make it more often, or user changeable.

**Comment by ooii** [comment]
Is there any way to mark a request as done manually? Cannot find it.
Thanks.

**Comment by lokenx** [comment]
Currently, no there is no manual way to mark.

**Comment by ooii** [comment]
But if downloaded with CP, then it will be marked done. Right?

**Comment by lokenx** [comment]
Yes if CP marks it as done according to your quality settings, it'll pick that up.
