### ISSUE TITLE
Movie setting is large causing slow downs

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#106]
http://i.imgur.com/R9A6R3x.png

is there a way to clear that out or reset it?

**Comment by lokenx** [comment]
Why is it so large? Duplicate requests bug? If so I can fix your DB once I'm out of hospital.

Sorry for the inconvenience!

Sent on the go, forgive the typo!

**Comment by camjac251** [comment]
I've noticed it too, when you delete a movie on CP, then PlexRequests will keep adding it under no user every second or so.

**Comment by lokenx** [comment]
OK, looking quickly I couldn't figure out the condition that caused this. I'll make sure the new CP package doesn't do this for next release!

**Comment by zenjabba** [comment]
I'm getting the same error on my movies setting. How do I flush it?

**Comment by unixjeff** [comment]
2 options
1) delete the data ".meteor/local/db" and restart

2)run
 meteor mongo
 db.dropDatabase() 
 

***NOTE** both of these option will reset the meteor database back to default all data will be lost

**Comment by unixjeff** [comment]
Is this issue still present in .6.0?

**Comment by lokenx** [comment]
Well technically no? But if you upgrade with your existing library then yes the duplicates will still be there. It's a bug that adds movies that get deleted from CP after being added a bunch of times--it's not possible in the new version.

I can manually edit your DB if you still have numerous entries to remove them.

**Comment by lokenx** [comment]
Closing ticket as this isn't an issue in v0.6. If anyone needs their DB cleared please PM via the Plex forums or the contact form on plexrequests.8bits.ca
