### ISSUE TITLE
[Feature Request] Add Plex-like skin

### ISSUE THREAD

**Issue by HazCod** [lokenx/plexrequests-meteor#108]
In order to integrate more with Plex, the same theme could be used.
Once I get meteor running, I might look at this.

**Comment by warplayer** [comment]
I'd like to bump this request. It would be nice if the look of PlexRequests was more like normal Plex.

**Comment by lokenx** [comment]
You're more than welcome to work on the CSS of the app. Keep in mind it's based on [Bootstrap](http://getbootstrap.com/) so I'd work off that just creating a Plex Bootstrap theme.

Personally I was thinking of switching to a lighter colour scheme, but the floors open. Keep in mind that I'm half way through a re-write of major parts of the application, so things could change in coming weeks.

**Comment by lokenx** [comment]
The new styling we're trying to go for:

![New search look](https://cloud.githubusercontent.com/assets/10313292/10667017/1691bc7a-78a3-11e5-8036-46bed65ad6f8.jpg)

**Comment by SmallwoodDR82** [comment]
i like it!  I'll be happy to test when it's ready

**Comment by lokenx** [comment]
Closing ticket as new "Plex-like" skin is coming with v0.6, won't be porting back to old versions.
