### ISSUE TITLE
meteor update to 12.0.1 failing

### ISSUE THREAD

**Issue by aptalca** [lokenx/plexrequests-meteor#109]
Every time I fire up meteor/plexrequests I get a message saying the meteor update is downloaded and I should update. But when I run meteor update in the project directory, I get the following error:

=> Errors while initializing project:

While building package npm-container:
error: No plugin known to handle file '../../packages.json'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('../../packages.json', 'client').

**Comment by lokenx** [comment]
Packages updated in Master and Dev branches.

**Comment by aptalca** [comment]
That was fast :-)

Thanks
