### ISSUE TITLE
Sonarr series not being added

### ISSUE THREAD

**Issue by damiantje99** [lokenx/plexrequests-meteor#113]
Hi Lokenx,

It's been a while I used PlexRequest, but I have to say that you really made some improvements!
But, at this point, there is only problem im having, and that is that the shows that are requested trough your application, will not appear in Sonarr. When im going to the build in status page of Sonarr, there are no errors at all and everything should be fine.

Do you have any idea what is causing this?

Hope to hear from you soon,

Kind Regards,

Damian

**Comment by lokenx** [comment]
Are you viewing the Sonarr page at the same time as adding requests? I know that Sonarr takes time to load them up, and if you're on the page itself it doesn't update.

Alternatively can you check the server console output for any errors when you requests a show? Do you have the Sonarr `enabled` option set to `true` as well? Does Sonarr log show any API errors or anything when requesting a show?

**Comment by damiantje99** [comment]
Its been around 16 hours since i added a show through Plex Request, but its still not added in sonarr. The console doesn't give any errors. There same is for Sonarr, no errors or warnings. So everythings seems okay, but still it isn't working.

**Comment by lokenx** [comment]
Can you download a new version quickly into a separate folder and just setup Sonarr and see if it connects?

**Comment by damiantje99** [comment]
I will try tomorrow and I'll let you know!

**Comment by damiantje99** [comment]
A new installation fixed the problem. Thanks!
