### ISSUE TITLE
Bug - CP not connecting, SSL

### ISSUE THREAD

**Issue by camjac251** [lokenx/plexrequests-meteor#114]
My Couchpotato isn't working with plexrequests for me. I've tried the public IP and localhost, with and without https, nothing is working on it. Could you add SSL support for CP?
![2015-10-09_04-10-17](https://cloud.githubusercontent.com/assets/6313132/10390058/b91fab22-6e3b-11e5-9759-a494f44e72cd.png)

**Comment by lokenx** [comment]
What does it say on the CouchPotato test page? Self-signed SSL certs should be fine, we added an exception for them awhile ago.

Is it installed on the same machine? Different machine same LAN? Entirely different LAN?

**Comment by camjac251** [comment]
I get the connection status: error. On non ssl it detects it just fine

**Comment by camjac251** [comment]
odd, guess it was a bug with CP, tried it just now after reenabling it and it works :)
