### ISSUE TITLE
Add TV Show Modal UI not showing

### ISSUE THREAD

**Issue by zack-hable** [lokenx/plexrequests-meteor#115]
When clicking add tv show button, modal shows up quickly and then closes.  This appears after updating meteor to 1.2 and after updating plex requests.

**Comment by lokenx** [comment]
Are you using it on mobile? There's a known bug with the modal on mobile where it is further down the screen.

**Comment by zack-hable** [comment]
nope on pc

**Comment by lokenx** [comment]
OS version, browser version? Have you tried it on others with same result?

**Comment by zack-hable** [comment]
firefox, chrome on windows 10.  It worked before on the older meteor/plex requests, after updating the tv show modal for all episodes or new episodes appears then quickly disappears.  Would you like my server url?

**Comment by SmallwoodDR82** [comment]
confirmed with same issue.

I'm on OSX (el capitan) and have tried Safari and Chrome.

**Comment by zack-hable** [comment]
update: seems to show fine on mobile android chrome.  still doesnt work on any pc browser

**Comment by SmallwoodDR82** [comment]
same issue on iPhone with Safari and Chrome.

Windows pops up and then disappears immediately.

**Comment by lokenx** [comment]
Thanks for the work guys! Are you on DEV or MASTER?

This isn't an issue in v0.6 which I'm pushing hard to get out ASAP, but I can see if there's a quick fix so long as I know which branch it's affecting for you guys.

**Comment by m1ll3rt1m3** [comment]
Having this issue on the Master branch. Attempted to use this on Chrome/Edge/Firefox with the same results as the original post. Android devices are unable to swipe to the pop-up as well.

**Comment by SmallwoodDR82** [comment]
I've tried both dev and master.  Same result on both.

**Comment by lokenx** [comment]
OK thanks, I think I know what it is, shall test tomorrow and push something to dev (and master if it works).

**Comment by lokenx** [comment]
Are you guys all on Windows? Can't break things on OS X and Android.

**Comment by SmallwoodDR82** [comment]
I'm running it via docker

**Comment by m1ll3rt1m3** [comment]
Also running it via Docker on unraid 6

**Comment by lokenx** [comment]
Manual docker setup or has someone packaged it?

**Comment by SmallwoodDR82** [comment]
someone packaged it for unraid.

It pulls directly form github.  We can change branches on the fly.

**Comment by lokenx** [comment]
OK, in your browser console are there any errors or anything when requesting a tv show and the modal is suppose to show up?

**Comment by SmallwoodDR82** [comment]
no errors.  I see the window pop up for like a half of second.

Then closes.  I can make it public facing if you would like.

**Comment by lokenx** [comment]
That would be helpful but I can't look into it right now (getting late!) but I should have time tomorrow.

**Comment by lokenx** [comment]
Can those on `dev` update to 0.5.6 and check? I fixed some Bootstrap issues that may help. Your admin interface will also be updated and a different colour to fix #110 hopefully.

**Comment by SmallwoodDR82** [comment]
I can move back if you would like.  However I'm loving 0.6 and don't want to go back :smile:

**Comment by lokenx** [comment]
Haha no worries, I'm looking to push v0.6 to dev pretty soon anyway!
