### ISSUE TITLE
Request list not showing when VPNed

### ISSUE THREAD

**Issue by pmow** [lokenx/plexrequests-meteor#117]
I've run into an issue with VPN whereby the request list doesn't show.  The rest of the page does, except when connected via VPN (I'm using PIA's client).  Without closing the browser or making any other changes, the request list appears fine when disconnected.

My server is external to both the VPN network and my local.

**Comment by lokenx** [comment]
In chrome does your console give any errors on page load or trying to view the requests list?

**Comment by pmow** [comment]
I'm sorry but I can't replicate on the same machine now.  It may have been an issue with the site I was connected to but there are lots of them.  If it happens again I will try and record this info.
