### ISSUE TITLE
Add Sonarr monitor override

### ISSUE THREAD

**Issue by pmow** [lokenx/plexrequests-meteor#119]
Sonarr has a default option for existing episodes.  It would be helpful to add an override to the server default.  In my case, my default is "latest season", but some users may not have seen the entire show and may want to select 'all episodes'.

Conversely, many installs may have 'all episodes' by default and may want a different option as the exception.

**Comment by lokenx** [comment]
What version are you running? We changed it to allow selecting new episodes (episodes going forward) or all episodes (self-explanatory).

**Comment by pmow** [comment]
I'm running 0.5.1 from master branch...
I tried moving to "v0.6" but it didn't seem compatible.  Got some dependency issues.
