### ISSUE TITLE
Self-signed SSL certificate CP problem

### ISSUE THREAD

**Issue by rogueosb** [lokenx/plexrequests-meteor#12]
I've been testing this on my server, and everything is working great, except the connection to CouchPotato. Looking through the logs I found this error whenever it tries to connect to CP:

 Exception while invoking method 'updateCP' Error: DEPTH_ZERO_SELF_SIGNED_CERT

From a quick search elsewhere (and the error itself), it seems to be an issue with self-signed certificates, which is what I'm using for my personal CouchPotato SSL.

**Comment by lokenx** [comment]
Interesting, mine isn't using a cert so never thought to check that. I'll give it a try after work and see what's up.

**Comment by lokenx** [comment]
@rogueosb Can you try out the dev branch or commit about? Let me know if that helps.

**Comment by rogueosb** [comment]
I just tried the latest dev branch, and the issue is gone. This should make testing much easier, thanks!

**Comment by lokenx** [comment]
Great, I'm going to keep this open while I look into a more permanent solution!

**Comment by lokenx** [comment]
I've tried another fix that is less dangerous, can you give it a try when you've a chance!

**Comment by rogueosb** [comment]
I have tried it, but unfortunately I am seeing the following error when trying to run meteor:

Your app is crashing. Here's the latest log.

Started MongoDB.
Errors prevented startup:

While building the application:
server/server.js:28:29: Unexpected token :

Your application has errors. Waiting for file change.

**Comment by lokenx** [comment]
Try now @rogueosb , if that doesn't help I'll revert it and keep looking (hard to do tests at work, don't have CP)

**Comment by rogueosb** [comment]
It runs, but as soon as it contacts CP, it crashes with this (removed some path details):

W20150401-15:31:51.936(1)? (STDERR)
W20150401-15:31:51.937(1)? (STDERR) /xxxx/plexrequests-meteor/.meteor/local/build/programs/server/packages/http.js:185
W20150401-15:31:51.937(1)? (STDERR)       callback(error, response);                                          
W20150401-15:31:51.938(1)? (STDERR)       ^
W20150401-15:31:52.057(1)? (STDERR) TypeError: object is not a function
W20150401-15:31:52.058(1)? (STDERR)     at packages/http/httpcall_server.js:70:1
W20150401-15:31:52.058(1)? (STDERR)     at packages/underscore/underscore.js:750:1
W20150401-15:31:52.058(1)? (STDERR)     at Request._callback (packages/http/httpcall_server.js:112:1)
W20150401-15:31:52.058(1)? (STDERR)     at self.callback (/xxxx/.meteor/packages/http/.1.1.0.aak84g++os+web.browser+web.cordova/npm/node_modules/request/request.js:344:22)
W20150401-15:31:52.058(1)? (STDERR)     at Request.emit (events.js:95:17)
W20150401-15:31:52.059(1)? (STDERR)     at Request.onRequestError (/xxxx/.meteor/packages/http/.1.1.0.aak84g++os+web.browser+web.cordova/npm/node_modules/request/request.js:961:8)
W20150401-15:31:52.059(1)? (STDERR)     at ClientRequest.emit (events.js:95:17)
W20150401-15:31:52.060(1)? (STDERR)     at CleartextStream.socketErrorListener (http.js:1552:9)
W20150401-15:31:52.060(1)? (STDERR)     at CleartextStream.emit (events.js:95:17)
W20150401-15:31:52.060(1)? (STDERR)     at SecurePair.<anonymous> (tls.js:1400:19)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by lokenx** [comment]
Reverted, I'll investigate when I can run more stuff locally.

**Comment by lokenx** [comment]
Doesn't appear to be any better fix than my current work around. Closing unless more information arises.
