### ISSUE TITLE
0.6.0 -  Constraints on package

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#120]
So im trying to setup .6.0 and keep getting
![2015-10-21 02_50_53](https://cloud.githubusercontent.com/assets/751756/10629666/d210f6e2-779e-11e5-98ec-820ad67b2e2d.png)

i downloaded https://github.com/lokenx/plexrequests-meteor/archive/v0.6.zip
then unziped and ran "meteor"

is there something i could be missing?

**Comment by lokenx** [comment]
I haven't pushed updates to some custom packages yet, just locally. I wouldn't try running it yet as there's no settings page too.

 I'm working on getting the settings page done and then doing the CSS and will let you know when it's somewhat usable. I need testers it's just not quite there yet, about 80% of way.

**Comment by SmallwoodDR82** [comment]
i'll assist in the testing.

**Comment by lokenx** [comment]
Thanks! There's only really the connection tests for the various services, enabling notifications/alerts, and figuring out how upgrades will work. Everything else should work.

**Comment by lokenx** [comment]
Closing ticket as the packages have been pushed and you can now run v0.6 alpha.
