### ISSUE TITLE
[v0.6-alpha] Not able to save/configure settings on a new installation

### ISSUE THREAD

**Issue by RandomNinjaAtk** [lokenx/plexrequests-meteor#122]
Branch: v0.6
Version: v0.6.1-alpha

I understand this is alpha/not fully tested. But just a heads up, on a new install for windows, meaning never previously configured. I am unable to connect it to Couchpotato, sonarr or plex.

It seems like it saves the settings, but the search never becomes active and then after re-entering the admin or restarting meteor. All settings are blank.

**Comment by lokenx** [comment]
Thanks giving it a test! Can you make sure you do an update as I did bunch of work tonight but forgot to update the about page (my bad)

When you say blank, you changed the default values to your own for say Couch Potato but when you restart the app they're blank fields?

Been on OS X and Linux but I'll see what happens on Windows tomorrow hopefully.

**Comment by SmallwoodDR82** [comment]
+1 My search actually says disabled and no matter how many times I check the boxes and update settings they still roll back to unchecked.

**Comment by lokenx** [comment]
I'm guessing also running on Windows? Will be looking at this first thing tomorrow!

**Comment by SmallwoodDR82** [comment]
Mine is running through a docker.

I've tried to add settings through mobile, osx, and windows machines.  (safari, chrome, ie)

**Comment by lokenx** [comment]
On default loading, both movies and tv shows are enabled, did you disable them or were they always disabled?

**Comment by SmallwoodDR82** [comment]
always disabled.

**Comment by lokenx** [comment]
Can you do a `meteor reset` and start back up, making sure you're on latest from GitHub?

**Comment by SmallwoodDR82** [comment]
it's via docker.  not sure how to do a meteor reset.  I'll look into that.

Here are the logs from the docker.

Updating repository
Updating 07e331b..c54a47a
Using the v0.6 branch
Your branch is behind 'origin/v0.6' by 47 commits, and can be fast-forwarded.
(use "git pull" to update your local branch)
Updating repository
Updating 07e331b..c54a47a
Using the v0.6 branch
Your branch is behind 'origin/v0.6' by 47 commits, and can be fast-forwarded.
(use "git pull" to update your local branch)
This project is already at Meteor 1.2.0.2, the latest release.

Changes to your project's package version selections from updating package
versions:

dburles:collection-helpers upgraded from 1.0.3 to 1.0.4
meteortoys:toykit upgraded from 2.1.1 to 2.1.2
msavin:mongol upgraded from 1.4.3 to 1.5.0


The following top-level dependencies were not updated to the very latest
version available:
* iron:core 1.0.8 (1.0.11 is available)
* iron:router 1.0.10 (1.0.12 is available)

Newer versions of the following indirect dependencies are available:
* iron:controller 1.0.8 (1.0.12 is available)
* iron:dynamic-template 1.0.8 (1.0.12 is available)
* iron:layout 1.0.8 (1.0.12 is available)
* iron:location 1.0.9 (1.0.11 is available)
* iron:middleware-stack 1.0.10 (1.0.11 is available)
* iron:url 1.0.9 (1.0.11 is available)
To update one or more of these packages, pass their names to `meteor update`.
Oct 25 17:17:51 8d1d8ea6cdfe syslog-ng[88]: syslog-ng starting up; version='3.5.3'
[[[[[ /config/plexrequests-meteor ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/

**Comment by lokenx** [comment]
`Your branch is behind 'origin/v0.6' by 47 commits, and can be fast-forwarded.
(use "git pull" to update your local branch)`

This line is confusing, is it not up to date?

**Comment by SmallwoodDR82** [comment]
let me delete everything and pull it new.

**Comment by lokenx** [comment]
OK, let me know!

**Comment by SmallwoodDR82** [comment]
Much better!  Something must have been stuck on my end.

```
First install detected, cloning repository
Using the v0.6 branch
Branch v0.6 set up to track remote branch v0.6 from origin.
This project is already at Meteor 1.2.0.2, the latest release.
npm-container: updating npm dependencies -- git-rev-sync...

Changes to your project's package version selections from updating package
versions:

dburles:collection-helpers upgraded from 1.0.3 to 1.0.4


The following top-level dependencies were not updated to the very latest
version available:
* iron:core 1.0.8 (1.0.11 is available)
* iron:router 1.0.10 (1.0.12 is available)

Newer versions of the following indirect dependencies are available:
* iron:controller 1.0.8 (1.0.12 is available)
* iron:dynamic-template 1.0.8 (1.0.12 is available)
* iron:layout 1.0.8 (1.0.12 is available)
* iron:location 1.0.9 (1.0.11 is available)
* iron:middleware-stack 1.0.10 (1.0.11 is available)
* iron:url 1.0.9 (1.0.11 is available)
To update one or more of these packages, pass their names to `meteor update`.
Oct 25 19:50:55 dd460ed39032 syslog-ng[94]: syslog-ng starting up; version='3.5.3'
[[[[[ /config/plexrequests-meteor ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```

**Comment by lokenx** [comment]
OK great, just need to make sure @RandomNinjaAtk is still having issues or not?

**Comment by SmallwoodDR82** [comment]
ok settings are now saving.  However so far, pushover and couchpotato are not working.

No alerts from pushover and nothing being adding to queue for CP.

Testing Sonarr next.

**Comment by lokenx** [comment]
PushOver and Pushbullet haven't been wired up yet. CouchPotato should, is approval enabled?

**Comment by SmallwoodDR82** [comment]
oh duh.  Yea it is.  Let me approve.

**Comment by SmallwoodDR82** [comment]
CP is good.  My fault.

Sonarr/TV Shows is acting odd.

```
[34mI20151025-20:15:01.262(-7)? [39m{ status: 'false' }
[34mI20151025-20:15:10.449(-7)? [39m{ [Error: ESOCKETTIMEDOUT] stack: [Getter] }
[34mI20151025-20:16:26.363(-7)? [39m{ [Error: ETIMEDOUT] stack: [Getter] }
[34mI20151025-20:16:26.363(-7)? [39mSonarr Series Get -> Match error: Expected number, got boolean
[34mI20151025-20:16:26.370(-7)? [39mTVDB ID must be a number
[34mI20151025-20:16:36.451(-7)? [39mSonarr Series Get -> ESOCKETTIMEDOUT
```

Getting those errors when trying to add a show.  After a few clicks it requests successful.  Odd thing is I was trying to add a show that was already there.  Should have come back with that.

**Comment by lokenx** [comment]
I think there's some hangups when getting the TVDB from TheMovieDB, I've flagged it already to be looked at so glad to know it's not just me.

Yes, even if the show exists it'll accept the request, the alert pop-up will be blue instead of green and say it already exists, and it should populate the download status based on episodes you've already downloaded (under requests page).

**Comment by SmallwoodDR82** [comment]
hmm.  Let me double check my sonarr settings.  It's acting like it has no idea of the Sonarr db.

**Comment by lokenx** [comment]
OK. I don't run Sonarr, just spin it up for testing, so please let me know! Off for the night.

**Comment by SmallwoodDR82** [comment]
FYI, this verbiage is used on the Sonarr page.  Also the default port for Sonarr is 8989

```
Enabled if you use SSL on your SickRage server.
```

**Comment by SmallwoodDR82** [comment]
Yea something isn't right with the Sonarr side.  It's letting me add shows that are already on Sonarr.

API maybe not pulling correctly?

**Comment by RandomNinjaAtk** [comment]
So after performing the:

meteor reset 
And a fresh git pull with the reset option

It seems that I am able to finally configure and save the settings. I have had the chance to see if everything is functioning, ie: putting a few requests

But it's better then it was. 

Now I'm on:

Branch: v0.6
Version: v0.6.2-alpha

**Comment by lokenx** [comment]
Great, you guys must have been stuck on an old version!

Are you using SickRage or Sonarr @randomninjatk ?

Is your terminal console saying anything when requesting shows? Is approval enabled? Are they coming up as Approved?

If Sonarr or SickRage aren't accessible but enabled, they'll be requested fine but won't be able to be approved. If approval isn't enabled they shouldn't be able to be requested at all. Same goes for CouchPotato.

**Comment by RandomNinjaAtk** [comment]
I'm using CP and Sonarr

Just tested CP and it's functioning. I haven't tested Sonarr yet. 

I do not have the approval requirement enabled, if you would like to me to test it, I can.

**Comment by lokenx** [comment]
Thanks @RandomNinjaAtk ! Closing ticket, open another if something else comes up!
