### ISSUE TITLE
[v0.6-alpha] Feature Request URL Base

### ISSUE THREAD

**Issue by m1ll3rt1m3** [lokenx/plexrequests-meteor#123]
Currently only Couchpotato/Sickbeard/Sonarr instances with standard URLS can be configured correctly.  Many of us will need the option to add custom URL bases for communication to happen correctly.  Not sure if this was already planned/yet to be coded addition or merely an oversight so far. Just wanted to make sure it was brought to your attention.

**Comment by lokenx** [comment]
The URL fields are set to only accept IPv4 addresses to improve checking the input is proper, however I can see how that could cause issues now.

Can you give me an example of what your URL may be and I'll have the adjust the fields schema accordingly.

**Comment by m1ll3rt1m3** [comment]
Well my example would be 192.168.0.2:5050/couchpotato and 192.168.0.2:5050/sonarr. The current config page on the latest v0.6 only lets me set the 192.168.0.2:5050 portion of the URL. I like to access my couchpotato and sonarr directly while on the road to resolve and renaming/sorting issues and run them through a reverse proxy like this to make that happen cleanly.

**Comment by lokenx** [comment]
I can't change the URL field to accept the `/sonarr` part (the URL would get generated as `http://192.168.0.2/sonarr:8981`) but I can add another field for sub-directory which could accept a String and would be added to the end of current URL.

And I'll actually change the word URL to IP address as that's more correct.

**Comment by m1ll3rt1m3** [comment]
Sounds great, I look forward to any future updates and will keep testing the latest alpha commits.

**Comment by lokenx** [comment]
Can you upgrade to v0.6.4 and give CouchPotato a test with sub-directory and let me know before I do the others?

**Comment by m1ll3rt1m3** [comment]
I will when I get a chance. I work long hours on a random rotation and
right now I am on nights. My next scheduled day off is mid week but I am
trying to squeeze some vacation time to jump into Halo 5 as early as
possible. I appreciate the really fast response and will test it out as
soon as I can.

**Comment by lokenx** [comment]
No worries, once you give the go ahead I'll add the others--it's not that long of a process!

(Jealous...I really need to get rid of my PS3 and upgrade!)

**Comment by m1ll3rt1m3** [comment]
So I took some time off work and tested the updates you made.  When ever i try to request a movie it pops up with "Couldn't submit request, please try again".

Log Output:
[34mI20151026-21:03:34.412(-5)? [39mError checking Couch Potato: Cannot read property 'success' of null

**Comment by lokenx** [comment]
Did you add a leading `/` to the directory field?

**Comment by m1ll3rt1m3** [comment]
I sure did, interestingly enough Sonarr is now working without that field.

**Comment by lokenx** [comment]
Wow haha! OK I'm going to have to emulate your setup to test locally.

- Is your CouchPotato installed on the same machine as Plex Requests? If not hows the setup roughly?
- How do you access the CouchPotato site (from the same machine PlexRequests is running from if possible) URL wise?
- When you go to Settings > General in CouchPotato, show Advanced, and click `Docs` next to your API key, what does the URL bar show, does it include the subdirectory?
- Do you have nginx/proxy involved somewhere?

**Comment by lokenx** [comment]
Can you test the below call, I want to see what you need to enter to get the correct response (`success: true`). 

`http://192.168.0.1:5050/[sub-directory]api/abcdef1234567890/app.available`

**Comment by m1ll3rt1m3** [comment]
I am going to try and update the meteor dependencies first and see if that is the issue.

**Comment by lokenx** [comment]
OK, confused why Sonarr is working now though. Try removing the sub-directory from CouchPotato?

**Comment by m1ll3rt1m3** [comment]
I tried several different combinations including an empty field.

**Comment by lokenx** [comment]
Can you let me know the above answers? As well, are you using approvals or not?

**Comment by m1ll3rt1m3** [comment]
Finally actually read through the log in its entirety instead of just scanning for errors and caught this:

The following top-level dependencies were not updated to the very latest
version available:
* iron:core 1.0.8 (1.0.11 is available)
* iron:router 1.0.10 (1.0.12 is available)

Newer versions of the following indirect dependencies are available:
* iron:controller 1.0.8 (1.0.12 is available)
* iron:dynamic-template 1.0.8 (1.0.12 is available)
* iron:layout 1.0.8 (1.0.12 is available)
* iron:location 1.0.9 (1.0.11 is available)
* iron:middleware-stack 1.0.10 (1.0.11 is available)
* iron:url 1.0.9 (1.0.11 is available)
To update one or more of these packages, pass their names to `meteor update`.
Oct 26 20:56:39 4344ac3d2cd5 syslog-ng[124]: syslog-ng starting up; version='3.5.3'
[[[[[ /config/plexrequests-meteor ]]]]]

**Comment by m1ll3rt1m3** [comment]
The test url you added was missing the / after the sub directory but it worked when i added it.

**Comment by lokenx** [comment]
Those `iron:router` messages are expected, I'm using an old version as new version was causing issues.

I've added log messages on the server console when searching for and requesting CouchPotato movies, can you check the string that get's outputted/try it in a browser to see if it's coming up correctly?

You will have to restart to get the latest package `lokenx:couchpotatowrapper@0.0.5`

**Comment by m1ll3rt1m3** [comment]
Ok I am monitory for the update to be published and then I will give it a go

**Comment by lokenx** [comment]
Should update right as you start-up the app

```
Changes to your project's package version selections:                                              
lokenx:couchpotatowrapper  upgraded from 0.0.4 to 0.0.5
```

**Comment by m1ll3rt1m3** [comment]
Nope telling me it's up to date with v0.6, also still showing the last commit was 10 hours ago on git.

**Comment by m1ll3rt1m3** [comment]
It worked !
[34mI20151026-21:45:31.569(-5)? [39mhttp://192.168.0.245:5050/couchpotato/api/123456/movie.add?identifier=tt0114709

**Comment by lokenx** [comment]
Yeah that's the package not entire app. OK so did that work in Plex Requests or did using that URL in a browser work? Or neither? Because I changed nothing but to add that console output.

**Comment by m1ll3rt1m3** [comment]
Must have just been the reboot then.  The app is working as expected.

**Comment by lokenx** [comment]
Maybe didn't get the updated package or something. But that doesn't explain why Sonarr is working because I didn't touch it.

For the hell of it does it stop working for CouchPotato if you remove the subdirectory?

**Comment by m1ll3rt1m3** [comment]
Yes, I tried removing the subdirectory after it started working again and it failed. I also noted the incorrect url in the logs.

**Comment by lokenx** [comment]
Ok good, now Sonarr.

It's working without the subdirectory, yet that's how it's setup and how you access it? I'll make the change tomorrow regardless as you can just leave it blank, but curious now!

**Comment by m1ll3rt1m3** [comment]
Also not sure how Sickbeard would react in a setup similar to mine either.

**Comment by lokenx** [comment]
Added in 26eb51c5 / v0.6.5-alpha.
