### ISSUE TITLE
[v0.6-alpha] Issue: Security

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#125]
Admin page seems to let me create an admin with whatever email.

Then I'm in the admin section.  Once the first Admin is created there should be an approval process for the next.  Unless it's not really "secure"

On Alpha btw.

Thanks and very excited to use this for my server!

**Comment by lokenx** [comment]
Yes, I hadn't yet limited it to one account sign-up, it's still on the todo list! You're only suppose to be able to create one account, after which sign ups are disabled. It's this way in master/dev already.

**Comment by lokenx** [comment]
Fixed in 5414364e
