### ISSUE TITLE
Pushover

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#126]
Not working.  (not sure if you have the back end working yet.)

Also on the Pushover section you have the verbiage "Quickly test your Pushbullet settings."

**Comment by lokenx** [comment]
It should, however I don't have Pushover so hard to test. What were you doing to get the notification? Test button? Requesting something?

**Comment by SmallwoodDR82** [comment]
odd, first 2 times I tested it, it came back with invalid API Token.

Third time it worked.

**Comment by SmallwoodDR82** [comment]
I'll run some more tests.

**Comment by lokenx** [comment]
Did you hit save on the form...it done't auto-save FYI (I've done it a few times lol)

**Comment by SmallwoodDR82** [comment]
DOH! that might have been it haha.  Seems to be solid now.  (Make sure you change the verbiage)

**Comment by lokenx** [comment]
Already done, can you check the about tab to see if it tells you there's an update?

**Comment by SmallwoodDR82** [comment]
will do.

**Comment by lokenx** [comment]
What version does it say you're currently on?

**Comment by SmallwoodDR82** [comment]
Branch: v0.6
Version: v0.6.9

**Comment by lokenx** [comment]
OK should say there's an update (v0.6.11), I'll look into that tomorrow, getting late here.
