### ISSUE TITLE
Sonarr Test Button

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#127]
When I click the test button is takes me back to main Admin page and says settings saved.

Shouldn't it stay on page and say testing failed or successful?

**Comment by lokenx** [comment]
Wow my bad, I forgot to wire that button up--done now!

**Comment by SmallwoodDR82** [comment]
nice work! Not trying to be annoying.  Just trying to hammer out the little things!  Very excited to use this for my server.

**Comment by lokenx** [comment]
No worries, its helpful with stuff I don't use like Pushover and Sonarr!
