### ISSUE TITLE
Update Notification

### ISSUE THREAD

**Issue by lokenx** [lokenx/plexrequests-meteor#128]
Confirm the `/about` page shows whether there's an update available. First mention #126

**Comment by lokenx** [comment]
Working locally in my tests, will keep open as see as more people use new version--it's not a critical bug (if there is one).

**Comment by lokenx** [comment]
Updates won't work if app is bundled for production (specifically if there is no `.git` folder)

**Comment by SmallwoodDR82** [comment]
I did get the notifications this morning about v0.6.14

**Comment by lokenx** [comment]
Great, it works as long as there's a .git folder.

**Comment by lokenx** [comment]
To get rid of `.git` dependency. Will remove pulling branch info (hard code branches) and version number is already saved/hard coded.

**Comment by lokenx** [comment]
Fixed v0.6.16
