### ISSUE TITLE
[Request] Issues with media

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#129]
Just a thought, requesting an issue is a little confusing.

What about adding a drop down to the initial result from the search.

i.e. Audio issue with Forrest Gump.  You search for Forrest Gump and when you click request there is a drop down (like tv shows) and the options are add to server or report an issue.

Thanks!

**Comment by lokenx** [comment]
I can see what you're getting at, will add, just not v0.6--but first update after.

**Comment by SmallwoodDR82** [comment]
furthermore, if it's a tv show giving them the option for Season/Episode #

**Comment by lokenx** [comment]
See #121. Not a simple implementation, and I want to keep feature parity between Sonarr and SickRage. I'll post updates in the other ticket when I have a look into it.

**Comment by SmallwoodDR82** [comment]
got ya.  I guess mine was more around issues not downloading.

If someone reports an audio issue on a TV Show like say GoT.  You will be scratching your head on where to start lol.

**Comment by lokenx** [comment]
Been thinking about issue reporting, what if it was totally separated from requests. For example the show doesn't even have to be in Plex Requests to be reported. A third nav gets added for Issues at the top, and they get dealt with on that page.

Click the report an issue button on the requests page, kicks you to the issues page, or modal popup, to fill out an issues form. A report issue button is added to search results that does something similar.

This way issues get managed separately from requests list which could be easier for admins.

**Comment by SmallwoodDR82** [comment]
I like that idea.  Would this system verify if the media was on the server first?

That way you don't just get random stuff.

**Comment by lokenx** [comment]
Possibly, I think moving issues into it's own DB would allow whatever to be done really. I'll see if I can hack on it next week sometime.

And actually I don't think I could really check if it's on the server already, it has to work for those that don't use the integration's. Obviously there aren't many of those users but still.

**Comment by rigrassm** [comment]
Implemented a while back, closing out as fixed.
