### ISSUE TITLE
Admin page to manage requests

### ISSUE THREAD

**Issue by lokenx** [lokenx/plexrequests-meteor#13]
A page to either allow or deny requests, instead of them going through automatically.

**Comment by lokenx** [comment]
An admin page has been added as of commit 7b0adac5d919687d1481d2acf77c50fc79d57752 . It's using https://github.com/gterrono/houston which works great! As no accounts are active, the first time you navigate to /admin you make an account and that is now the admin account that can add/delete/edit entries in the movie collection. I'll look into approving/denying requests too.

**Comment by markaswift** [comment]
I'd really like to see an approval system, it would really complete the solution for me.

**Comment by lokenx** [comment]
Can you please open a new issue for this? Thanks!
