### ISSUE TITLE
Requesting a Title that's already on server

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#130]
I mentioned this in another issue but should be it's own.

If I request a title that is already on the server I get the message "already requested" 

In reality it should say "already exists on server" however, in the event it's a title that has been requested and it's on the server yet then it should say "already requested"

**Comment by lokenx** [comment]
If show has already been requested in PR you can't request it again, so only the verbiage should change as the other condition doesn't arise.

**Comment by SmallwoodDR82** [comment]
fair enough!
