### ISSUE TITLE
[Bug] Requesting Movie with CP

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#131]
seeing a lot of these errors.  Sometimes a request works.  Other times it errors out and says try again later.

```
[34mI20151027-21:33:21.482(-7)? [39mTrying to check if eists in CouchPotato
[34mI20151027-21:33:21.482(-7)? [39mhttp://192.168.1.121:8081/api/aa3bd5fdf7214ea38f4fed4a3dfd64e4/media.get?id=
[34mI20151027-21:33:21.544(-7)? [39mIMDB ID is required
[34mI20151027-21:33:32.994(-7)? [39mTrying to check if eists in CouchPotato
[34mI20151027-21:33:32.994(-7)? [39mhttp://192.168.1.121:8081/api/aa3bd5fdf7214ea38f4fed4a3dfd64e4/media.get?id=
[34mI20151027-21:33:33.000(-7)? [39mIMDB ID is required
[34mI20151027-21:33:40.629(-7)? [39mTrying to check if eists in CouchPotato
[34mI20151027-21:33:40.629(-7)? [39mhttp://192.168.1.121:8081/api/aa3bd5fdf7214ea38f4fed4a3dfd64e4/media.get?id=
[34mI20151027-21:33:40.921(-7)? [39mIMDB ID is required
[34mI20151027-21:33:45.655(-7)? [39mTrying to check if eists in CouchPotato
[34mI20151027-21:33:45.655(-7)? [39mhttp://192.168.1.121:8081/api/aa3bd5fdf7214ea38f4fed4a3dfd64e4/media.get?id=
[34mI20151027-21:33:45.704(-7)? [39mIMDB ID is required
[34mI20151027-21:38:10.123(-7)? [39mTrying to check if eists in CouchPotato
[34mI20151027-21:38:10.124(-7)? [39mhttp://192.168.1.121:8081/api/aa3bd5fdf7214ea38f4fed4a3dfd64e4/media.get?id=tt1486834
[34mI20151027-21:39:22.215(-7)? [39mTrying to check if eists in CouchPotato
[34mI20151027-21:39:22.216(-7)? [39mhttp://192.168.1.121:8081/api/aa3bd5fdf7214ea38f4fed4a3dfd64e4/media.get?id=
[34mI20151027-21:39:22.334(-7)? [39mIMDB ID is required
[34mI20151027-21:39:31.602(-7)? [39mTrying to check if eists in CouchPotato
[34mI20151027-21:39:31.602(-7)? [39mhttp://192.168.1.121:8081/api/aa3bd5fdf7214ea38f4fed4a3dfd64e4/media.get?id=
[34mI20151027-21:39:31.645(-7)? [39mIMDB ID is required
```

**Comment by lokenx** [comment]
Can you please upgrade? It should be up to v0.6.11 or higher.

I've added a secondary check for IMDB and better error output.

Of note, if an IMDB ID cannot be found, a request will not go through as it's useless for Couch Potato.

**Comment by SmallwoodDR82** [comment]
on v0.6.14

```
[34mI20151028-10:48:42.829(-7)? [39mError getting IMDB ID, none found!
[34mI20151028-10:48:43.273(-7)? [39mError getting IMDB ID, none found!
```

**Comment by lokenx** [comment]
Same as with Sonarr, it's not getting an ID. What's movies? So I can see if the info exists in TheMovieDB.

**Comment by SmallwoodDR82** [comment]
Goosebumps - Attack of the Jack O Lanterns (1996)

https://www.themoviedb.org/movie/294921-goosebumps-attack-of-the-jack-o-lanterns

The movie shows up on the list just fine but when I click Request, I get a failed.

**Comment by lokenx** [comment]
Weirdly enough, it doesn't even show up with the [OMDB](http://omdbapi.com/), a common search provider as well. And from what I can tell Couch Potato is also using TheMovieDB, because you can't directly add it to CouchPotato, also complains about not having an `IMDB`.

http://www.omdbapi.com/?s=Goosebumps&r=json

**Comment by SmallwoodDR82** [comment]
Hmm.  My concern isn't the adding to CP but with my customers getting errors on the PR side.

What about a manual entry option? v0.9? lol.

**Comment by lokenx** [comment]
Maybe! Manual would really suck though--just sucks IMDB isn't usable lol

**Comment by SmallwoodDR82** [comment]
If you use TheTVDB for TV Shows and TheMovieDB for Movies that "should" cover 99% of the stuff.  I mean Kodi and Plex use TheMovieDB for Movies and TheTVDB for TV Shows.

**Comment by lokenx** [comment]
It's different when searching versus pulling meta-data. I've tried TheTVDB but using the API if you search for CSI checkout the results (it's missing virtually all of them)

http://thetvdb.com/api/GetSeries.php?seriesname=csi

**Comment by SmallwoodDR82** [comment]
funny, I wonder if TheTVDB knows about that.

If I search for CSI on Sonarr I get the same 3 results.

However on their website if you search CSI you get many more.

Have you found this result with other shows it just this one?

**Comment by lokenx** [comment]
I only tested CSI and NCIS. They do, I brought it up in their developer forums. They're pushing out a new API that's in development right now, and it's suppose to be a bit better. If it's is, and returns results properly I'll gladly switch--would save me a lot of work! But for now, the results just aren't great right now.

**Comment by SmallwoodDR82** [comment]
to find CSI: Cyber on their API I had to search for Cyber.

**Comment by lokenx** [comment]
Yeah it’s ok if you can be specific enough/know full title, but for more general browsing it’s lacking at the moment!

**Comment by SmallwoodDR82** [comment]
Looks like TheTVDB API v2.X is in full beta and getting close.

Might be worth a shot of testing it.

**Comment by camjac251** [comment]
https://forums.thetvdb.com/viewtopic.php?f=17&t=25454 for more info on that

**Comment by lokenx** [comment]
#149 for new TV API, no idea for new movie search api.
