### ISSUE TITLE
[Bug] Requesting Show with Sonarr

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#132]
Seeing a lot of these.

```
[34mI20151027-21:51:02.372(-7)? [39mSonarr Series Get -> ETIMEDOUT
[34mI20151027-21:51:02.388(-7)? [39minsertDocument :: caused by :: 11000 E11000 duplicate key error index: meteor.tv.$c2_id dup key: { : 14766 }
[34mI20151027-22:00:02.012(-7)? [39mSonarr Series Stats -> ETIMEDOUT
[34mI20151027-22:00:39.357(-7)? [39mSonarr Series Get -> ETIMEDOUT
[34mI20151027-22:01:09.675(-7)? [39mSonarr Series Get -> ESOCKETTIMEDOUT
[34mI20151027-22:07:07.480(-7)? [39mSonarr Series Get -> ETIMEDOUT
```

**Comment by lokenx** [comment]
Is there some connectivity issues between PR and Sonarr? Those are all timeouts when requesting info from Sonarr.

**Comment by SmallwoodDR82** [comment]
new error this morning.  I'm on v0.6.14

```
[34mI20151028-10:24:44.854(-7)? [39mError getting TVDB ID, none found!
```

But if I go to TVDB the show is there.  Does the site pull from TVDB or another site? (IMDB)

**Comment by lokenx** [comment]
I changed the wording to be more specific. It uses TheMovieDB as it's the search provider so I need to get its ID converted to a TVDB/IMDB for the apps.

What's the show that's not going through, or is it all shows?

**Comment by SmallwoodDR82** [comment]
Not sure how hard it would be, but could you use TheMovieDB for Movies and TheTVDB for shows?

Seems TheMovieDB doesn't always have all show info.

This particular show was "Vanderpump Rules" 
(Don't judge me it was from a customer on my server :stuck_out_tongue: )

**Comment by lokenx** [comment]
Unless they've improved the API I can't. It was missing CSI shows based on searching "CSI" which was ridiculous. Now you can't compare the website search as it's fine, the API is different engine.

Can be looked at again in next version.

**Comment by SmallwoodDR82** [comment]
How does Sonarr search for TV Shows with their API call?

I'm able to search for the show above directly on Sonarr and it's coming up just fine.

Maybe something to look into?

**Comment by lokenx** [comment]
Not sure, I'll check their repository.

**Comment by camjac251** [comment]
You can join their irc on freenode and ask the devs. They're helpful

**Comment by lokenx** [comment]
They're using the tvdb but I won't switch unless the results improve with the new API coming out.

**Comment by camjac251** [comment]
Sonarr has their own api system, shouldn't be relying on tvdb. You could add a show name probably with it

**Comment by lokenx** [comment]
They have to use someone's database of TV shows, I don't think they keep their own. So when searching for a show to add and when pulling meta data down they use tvdb.

And you have to provide a tvdb as well as bunch of other fields when adding a show into Sonarr through their API.

**Comment by SmallwoodDR82** [comment]
Sonarr has their own DB called Skyhook.  Basically it pulls from TVDB about every hour.

hopefully TVDB API 2.X solves the issue and you can use it moving forward.

**Comment by lokenx** [comment]
New issue opened.
