### ISSUE TITLE
[Request] Add Denied

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#133]
When Approval required is checked.

Add the option for denied.

This would keep the Media on file but show as denied and if anyone tried to request later show as previously denied.  Maybe for 0.7?

**Comment by lokenx** [comment]
Definitely not adding in v0.6, but can discuss later. Currently can't tell the difference between denied and not yet approved.

**Comment by Plonq** [comment]
If this gets revisited, it would be great to be able to give an explanation when denying, so the requester knows why you're denying it.

**Comment by lokenx** [comment]
Makes sense, depends if I re-do this part as right now it's either `true` or `false`.

**Comment by mbnn** [comment]
Would love to see a DENIED button so it stays denied :) Thx!

**Comment by dellipse** [comment]
+1
This is a great idea, since just deleting it looks like it disappeared to the requester and leaving it looks like you didn't see it
