### ISSUE TITLE
[Issue] Shows not showing up as already on plex

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#134]
Not sure if this is Sonarr issue or what.

If I try to add Game of Thrones is says request successful and shows in requests section as not on server, yet if I add other shows they show already on Plex.

**Comment by SmallwoodDR82** [comment]
Scratch that.  I think this is related to #132

Seems is that bug shows up then the request will go through successfully, regardless if it's on the server or not.

**Comment by lokenx** [comment]
So when something is requested, we first check if it exists in Sonarr, if it does, it gets added as approved and we try to get the download status. If we have issues checking if it exists, or it doesn't exist it then gets added.

If approval is enabled it get's set to unapproved, if approval isn't enabled it's approval status gets set depending if we can talk to Sonarr or not.

Is your Sonarr on your LAN? Seem to be having lots of connectivity issues with it.

**Comment by SmallwoodDR82** [comment]
One is a VM and the other is a docker.  They are about 4U away from eachother on a rack.  All gigabit LAN.

**Comment by lokenx** [comment]
Going to assume this related to #132 as you mentioned, closing unless I'm wrong.
