### ISSUE TITLE
Configuration of CouchPotato/SickRage/Sonarr requires IP

### ISSUE THREAD

**Issue by Dahlgren** [lokenx/plexrequests-meteor#135]
When saving CouchPotato, SickRage or Sonarr it's not possible to use a hostname, only IP. This makes it hard to use together with Docker since each linked service is assigned a hostname and the IP can/will change.

**Comment by lokenx** [comment]
Thanks for bring this up, it seems I will have to open up the field to just accept a string. Was trying to limit the scope so I could verify the input.

**Comment by Dahlgren** [comment]
Awesome, thanks!

**Comment by lokenx** [comment]
Can you update, and give it a test?

**Comment by Dahlgren** [comment]
I can confirm that couchpotato and sonarr works flawless! The page "reloads" when a server setting is saved and returns to the first tab, a tad bit annoying :scream:

**Comment by lokenx** [comment]
Yeah it's Meteor bug that is causing the form generation to do that (it reloads the data on submit). I'm keeping an eye if they fix that, but I'll most likely re-do the whole page after v0.6 to get around this.
