### ISSUE TITLE
Testing CouchPotato/SickRage/Sonarr configuration

### ISSUE THREAD

**Issue by Dahlgren** [lokenx/plexrequests-meteor#136]
_Test X Service_ requires configuration to be saved before being possible to test. `Quickly test your server settings` would at least for me imply that it's possible to test the inputed configuration before saving. Preferably it would be possible to test a new configuration without saving. Otherwise it would be nice that testing requires saving new input first.

This is using the `v0.6` branch.

**Comment by lokenx** [comment]
Good point, that is a bad experience.

I think I'll change it to allow testing immediately as that would be the better experience.

**Comment by lokenx** [comment]
For v0.6 I'm going to leave as is but update the wording. Will change in next version, too many hooks to change--trying to squash bugs to push out right now.

**Comment by Dahlgren** [comment]
Great, looking forward to the next release!

**Comment by lokenx** [comment]
Current setup doesn't allow testing without the settings saved. The tests are part of the separate packages which have their variables set when settings saved. For now will have to do with the messages, but will look again.
