### ISSUE TITLE
Unable to update v0.6.15 -> v0.6.16

### ISSUE THREAD

**Issue by RandomNinjaAtk** [lokenx/plexrequests-meteor#141]
Maybe I'm doing something wrong cause I'm not familiar with using GIT.

First I stop the application from the command line, cntrl + C twice

But when I attempt to update, by opening the GIT GUI, Selecting the project and then: Remote -> Fetch From -> Origin

It says success, but after restarting the app in meteor, it does not seem to have actually updated. This seemed to be also happening before the move to V0.6

The only way I am able to retrieve the updates is by performing a create branch and re-selecting the branch.

I'm just curious if I'm doing something wrong, looking for some advice.

Thanks in advance!

OS: Windows 10 Pro

**Comment by lokenx** [comment]
That sounds right, but I'm not great with the Git GUI. I use the command line and GitHub desktop on OS X and Linux.

However, I'll play around later on Windows and see what's up.

**Comment by RandomNinjaAtk** [comment]
What command do you use on the command line to perform the same function?

**Comment by lokenx** [comment]
On OS X it's `git checkout <branch>`

````
[11:20:35] 2629:plexrequests-meteor lokenx$ git checkout dev
Switched to branch 'dev'
Your branch is up-to-date with 'origin/dev'.
[11:21:35] 2629:plexrequests-meteor lokenx$ git checkout gh-pages
Branch gh-pages set up to track remote branch gh-pages from origin.
Switched to a new branch 'gh-pages'
[11:23:53] 2629:plexrequests-lokenx mdelport$ 
````

**Comment by lokenx** [comment]
Great free resources for Git from Atlasssian, there's tons more on web too.

https://www.atlassian.com/git/tutorials

**Comment by RandomNinjaAtk** [comment]
So on windows, after navigating to the local directory, running a "git pull" command worked.

Thanks for your help!

--Ninja

**Comment by lokenx** [comment]
No worries!

Never more applicable daily [XKCD](http://xkcd.com/1597/)
