### ISSUE TITLE
[Request] Show episode count on approval list

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#144]
Would be cool to see how many episodes are associated with the selection.

i.e. all episodes of "The Simpsons" requested and there are 579 episodes.

**Comment by lokenx** [comment]
I don't think that data is available at that point as it gets pulled in from SR/SO and the show isnt added at that point.

I can look into if TMDB provides that info but it would require a lot of refactoring.

**Comment by SmallwoodDR82** [comment]
I'll keep my hopes up for the new API :stuck_out_tongue_closed_eyes:

**Comment by lokenx** [comment]
Tracking new api in #149 , closing this issue for now.
