### ISSUE TITLE
[Bug] Available Episodes Updating

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#145]
Just wondering but if a show is added it shows 0/0 available.  On approval is moves to 0/X available.

After Sonarr downloads all the episodes shouldn't it the count update to X/X available on the approval list?  Is there a cron job that updates?  Am I just impatient?

**Comment by lokenx** [comment]
It's an hourly update, I can't get the data live as I have no idea what Sonarr is downloading/recently finished. It pulls in on request/approval and it should get checked hourly with everything else.
