### ISSUE TITLE
anyone able to request

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#147]
any username i put in the box on  v0.6.15 it allows them to request, so i could put "aaaaaaa" and it will let me request stuff

**Comment by lokenx** [comment]
Do you have user authentication enabled, with your correct plex token?

**Comment by lokenx** [comment]
Of note just noticed I haven't added a test for Plex tokens. Will be added once I've finished re-writing the settings page (the refresh is annoying me).

**Comment by unixjeff** [comment]
just noticed that was unchecked lol

**Comment by lokenx** [comment]
No worries, it's unchecked by default and setting token isn't enough, have to check it too (for cases were you wan't to disable it temporarily but don't want to bother with token again).
