### ISSUE TITLE
Readme Images

### ISSUE THREAD

**Issue by camjac251** [lokenx/plexrequests-meteor#150]
You can add this to the readme and it would still register the image. Instead of taking up extra space in the repo for images and having them clutter up the directory
You could use imgur, really nice image hosting place.

```![screenshot](http://yourimagelink.com/image.png/jpg "screenshot")```

**Comment by lokenx** [comment]
Thanks for the idea! The new version of README only has 1 image and I'll probably just put it over on the website and link from there (also hosted by GitHub).
