### ISSUE TITLE
Request queue

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#151]
After reaching your limit it queues for approval so the request can still be submitted

**Comment by lokenx** [comment]
Who is making the request? If you're logged in as the admin you don't have a limit. And if limit is 0 there is no limit.

**Comment by unixjeff** [comment]
For nonadmins I have the limit set to 10. After they have requested 10 it should just put the next request for approval instead of saying limit reached.

**Comment by lokenx** [comment]
Probably won't be making this change, as for users who are using the approval system, this means there would be no limit at all for their users as they have to approve anything anyway.
