### ISSUE TITLE
[Bug] Dev CP not working with self signed SSL

### ISSUE THREAD

**Issue by camjac251** [lokenx/plexrequests-meteor#152]
I am trying to use my CP install with the new version but it's not able to connect on the test, I believe that it's not accepting the self signed ssl on my local IP

I have CP listening on 127.0.0.1 and have SSL active with a self signed cert

**Comment by lokenx** [comment]
Thanks for letting me know. It's the self signed cert it doesn't like but I know a work around--will push out later.

**Comment by lokenx** [comment]
A restart of the application should update the packages to get this to work.
