### ISSUE TITLE
Linux install instructions

### ISSUE THREAD

**Issue by duramato** [lokenx/plexrequests-meteor#158]
Is there any kind of linux istall instructions?

**Comment by lokenx** [comment]
Depends how you're trying to run it.

Meteor Up ([GitHub](https://github.com/arunoda/meteor-up)) is a great automated solution for Ubuntu distributions. It handles everything including installing node.js and a MongoDB.

Alternatively you can use a start-up script such as below. You have to install node and MongoDB yourself though. An example can be found [here](https://gist.github.com/tmeasday/4333791) and [here](http://stackoverflow.com/questions/15657071/how-to-run-meteor-on-startup-on-ubuntu-server).

Lastly, [this](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-meteor-js-application-on-ubuntu-14-04-with-nginx) is a great, if long, article on deploying Meteor.

---

In the simplest terms, first install meteor from the terminal.

```
$ curl https://install.meteor.com/ | sh
```

Use git to download app 

```
$ git clone https://github.com/lokenx/plexrequests-meteor.git
```

Finally startup the app.

```
$ cd plexrequests-meteor
$ meteor
```

**Comment by lokenx** [comment]
If need more details let me know, can now use [Gitter](https://gitter.im/lokenx/plexrequests-meteor?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
