### ISSUE TITLE
Report issues for any content

### ISSUE THREAD

**Issue by MrCrunchwrap** [lokenx/plexrequests-meteor#163]
Maybe this doesn't belong in the scope of this application, but would it be possible to have users report issues for any media stored on Plex, not just requested media?

As far as I can tell, you could at least get whatever's currently in the library from CouchPotato, and possibly SickRage?

**Comment by lokenx** [comment]
I could load my DB with that the data of CouchPotato/SickRage/Sonarr but it works fine without. Requesting content that already exists alerts the user as such but it does get added into the app. At which point then can report an issue with it.

I'm also most likely going to add a report issue button right into the search side along side request as well (#129)
