### ISSUE TITLE
loop at /search

### ISSUE THREAD

**Issue by rix1337** [lokenx/plexrequests-meteor#167]
With the ROOT_URL variable I have published plexrequests at /plexrequests on my main server (where also plex is run at /plex) (Thanks again for the hint @lokenx)

When users navigate to /plexrequests all is working fine, except for the "Back" button of the browser.

Is there some script (js probably) inside the app that sets ROOT_URL inside js as the only available history entry?

It seems that function window.history.back(); refers to /plexrequests instead of any previously opened domain urls.

If so, could you please fix this?

This issue is minor, though annoying to my not-so-tech-savvy users whom I have installed plexrequests for in the first place.

**Comment by lokenx** [comment]
I'm not sure there's something I can fix there. I span up a local copy at `localhost:3000/plex` and the back button works as expected when navigating to `localhost:3000/plex/search` and `localhost:3000/plex/requests`.

The back button behaviour is however Meteor decided to implement it I haven't hard coded anything regarding it. What happens when they hit the back button?

**Comment by rix1337** [comment]
That was quick :D try if it works for you at https://rix.ninja
FILM-/SERIENWÜNSCHE? refers to plexrequests.

If it is a meteor side issue, i am going to give it a pass ^^

**Comment by lokenx** [comment]
Sometimes I am! I shall, will need a username to get in though, or temporarily return plex auth (so as not to share a username for people to get in lol)

**Comment by rix1337** [comment]
ill remove the url from my previous comment, and auth is turned off

**Comment by lokenx** [comment]
It seems to work when using the back/forward buttons to switch between `/search' and `/requests`. It does on occasion seem to get stuck on `/search` for some reason.

I did notice that the link in the top left doesn't adhere to the `ROOT_URL` if it's a sub-directory so will see if can fix that at least.

**Comment by rix1337** [comment]
I have reproduced your findings. If logged out back/forth buttons work fine. Once logged in, it's `/search` that gets stuck. 

So no general issue. Didn't noticed because I had already logged into plexconnect once.

**Comment by rix1337** [comment]
I've got an idea. When logged in the app automatically redirects from `/` (in my case `/plexconnect`) to `/search`. So the back button is working as intended. It's a simple loop where the browser sent back to `/` immediately is sent back to `/search`

**Comment by lokenx** [comment]
Yeah I was just going over my routing file and definitely a loop. Shall be fixed shortly (going to remove re-direct and just put some content on the page once logged in).

**Comment by rix1337** [comment]
That's awesome, thanks!
