### ISSUE TITLE
Require Plex Password On Sign-In

### ISSUE THREAD

**Issue by bassrock** [lokenx/plexrequests-meteor#168]
Hi,

I was wondering if it is possible to add plex passwords to the sign in process, because as of right now it with just a username it makes it possible to brute-force or just sign in by knowing user's usernames.

**Comment by lokenx** [comment]
This was a design decision made awhile ago, but it's up for debate! I didn't want to create new accounts for users, but maybe using their Plex.tv login is an option.

**Comment by bassrock** [comment]
Yea just the plex.tv credentials is what I was thinking. Just using the user's username just seems really insecure to me.

**Comment by jrdnlc** [comment]
+1 for this. I've had to delete a few requests a few days ago from someone that was using my own username.

**Comment by lokenx** [comment]
Checkout the `plex-auth` branch and let me know if it works for you.

**Comment by lokenx** [comment]
You now have to enable password logins, after plex auth is already enabled. This is for those that don't want to require passwords.

**Comment by bassrock** [comment]
It worked perfectly!

**Comment by lokenx** [comment]
Can you also test turning the password side off to make sure switching back and forth works? It's not a lot of lines of code but I want to make sure it works as intended before merging

**Comment by bassrock** [comment]
Yep it worked!

**Comment by lokenx** [comment]
Merged as of 1.2.
