### ISSUE TITLE
[Request] Canistreamit

### ISSUE THREAD

**Issue by MiTeePingWin** [lokenx/plexrequests-meteor#169]
Is it possible to integrate CanIStreamIt (http://www.canistream.it/) when making a request? There's a Python api someone built that might be helpful (https://github.com/bulv1ne/CanIStreamIt)

**Comment by unixjeff** [comment]
So what is the benefit of this over thetvdb?

**Comment by MiTeePingWin** [comment]
This tells you if an item is available on Netflix. No need to put in a
request if it's already available elsewhere, or the admin can choose to not
approve the request.

**Comment by lokenx** [comment]
Honestly, while it would be cool, I think this would be beyond the scope of the app.

**Comment by dualznz** [comment]
Yes i dont see there being a point in this, as this service is designed for plex, not netflix, defys the purpose

**Comment by MiTeePingWin** [comment]
Understandable. However, third parties are lazy and many subscribe to streaming services. A quick lookup while making a request will let the requester know that this may already be available elsewhere. The admin can also save cycles by telling the requester to go elsewhere instead.

Either way, we can go ahead and close this request if it's out of scope. Thanks for the consideration  :)

**Comment by cvockrodt** [comment]
I actually don't think this is out of scope and think it should be integrated
