### ISSUE TITLE
[Bug] CouchPotato Movies not showing as available

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#173]
I know with Sonarr you said it checks every hour or so.  Does CP have that same check?

It's been a few days now and the movie is still showing a red X on PlexRequest yet it's showing in the CP db.

Thoughts?

**Comment by lokenx** [comment]
It checks at same time. Does it show up under the Manage section of CouchPotato? If it's not in that section it's typically not considered done by CouchPotato.When I'm at computer next I'll give you a URL to check the status of an individual movie the same way Plex Requests checks.
		
        
		
		 ---- On Wed, 11 Nov 2015 22:16:09 -0500  notifications@github.com  wrote ----I know with Sonarr you said it checks every hour or so.  Does CP have that same check?
It's been a few days now and the movie is still showing a red X on PlexRequest yet it's showing in the CP db.
Thoughts?

**Comment by SmallwoodDR82** [comment]
that would be great.

It does show in Manage.  I'm curious though.  It's still in wanted as well because CP is still looking for a BR version.  So maybe the available only gets satisfied if CP has BEST for the movie?

**Comment by lokenx** [comment]
Yeah CP has to mark it as done, and that depends on your quality settings. I believe it gets marked as done when a quality with the `finished` checkmark gets downloaded.
```
http://192.168.0.1:505/api/abcdef12345/media.get?id=imdb

abcdef12345 is your API key
imdb is either an IMDB ID or a CouchPotato ID
```

**Comment by SmallwoodDR82** [comment]
is there any sensitive info from that API call?

If not I'll paste it.

**Comment by lokenx** [comment]
No i don't believe so, but the important part should be right at the top. Use [this](http://jsonprettyprint.com/) to make it more readable.

Example: 
```
{
  "media": {
    "status": "active",
    "info": {
```

**Comment by SmallwoodDR82** [comment]
{
  "media": {
    "status": "active",
    "info": {
      "rating": {
        "imdb": [
          6.3,
          9903
        ]

**Comment by lokenx** [comment]
So active means it's still looking for better/different versions. It can't be differentiated from stuff that isn't downloaded at all, so I only update on `"status": "done"`.

**Comment by SmallwoodDR82** [comment]
ok got ya. So my battle is with CP.

There is no BR version.  Bah!

**Comment by lokenx** [comment]
Yeah, maybe review your quality settings/profiles to find something that works better, your best bet unfortunately.
