### ISSUE TITLE
Notification for users

### ISSUE THREAD

**Issue by damiantje99** [lokenx/plexrequests-meteor#177]
Hi,

After the Approval/subtitles/audio etc. options, maybe you can add a option for users to notify them when a movie/show is approved or fixed. They should get the possibility to config this option. It could be an option to use pushbullet or mail.

**Comment by lokenx** [comment]
Currently this isn't possible. Because I chose to not create user accounts and allow users to use their existing Plex.tv logins there are no stored details for users besides the admin.

**Comment by damiantje99** [comment]
Alright, seems logic. Maybe you can add it as an option, so people can decide if they want to use Plex Authentication or custom users. In that way you can add a feature like notifying users.

**Comment by lokenx** [comment]
That would just get messy! What I am thinking is seeing if there's a way to use OAuth with Plex.tv. But for now this is out of scope , but will revisit if accounts can be setup with Plex.tv.
