### ISSUE TITLE
[request] on request submission set as pending

### ISSUE THREAD

**Issue by dualznz** [lokenx/plexrequests-meteor#178]
Hi

At the moment the request system states that on new request add to denied, coul;d this be changed to pending with a new icon like a - or something.

Then when the admin comes along he / she can then choose approve or decline.

also is there a way that we can remove the available feature as my plex server talks to a massive nas server with 120+tb and the requests app cant see if those moves are in my listings.

cheers

**Comment by lokenx** [comment]
Denied/Pending, same thing really, it's Boolean value either true or false! If you'd like find a nicer icon besides the `x` from [here](http://fortawesome.github.io/Font-Awesome/icons/).

Functionality wise it won't be changing currently. You can use the filter sort option on the right to narrow down what you're looking for (Search is being investigated).

There's no way currently to not show the available status. Are you not interfacing with Couch Potato, as that's where we pull status info from.

**Comment by dualznz** [comment]
ahh ok, no im not using couch potato as i have all my media stored on other server's within my home, and couch potato's download methosds are awfull, the quality is just yuk for me personally, oh, ill just do some magic and change the way it works on my end

**Comment by lokenx** [comment]
Ah, whatever works! Took me ages to get download quality settings right, helped being on private trackers!

I’m hoping to add a manual option to marking things as available down the road, so that may help you.

**Comment by lokenx** [comment]
Thought, you could just use CouchPotato to provide a list of what's available to PlexRequests, but don't do any of the actual downloading through it.
