### ISSUE TITLE
Unable to Approve new TV Serie (Sickrage)

### ISSUE THREAD

**Issue by TheVMaster** [lokenx/plexrequests-meteor#179]
I've connected Sickrage to Plex Requests and everything seems to work the way it should. I am able to request new series. When I click the 'Approve' button I receive an error 'Unable to approve [serie name], please try again!'.

**Comment by lokenx** [comment]
Can you check the server logs to see a more detailed error message? Does the test in the settings page work for SickRage?

**Comment by TheVMaster** [comment]
The Plex Request server logs, or the SickRage server logs? The test (on the settings page) works great and I can even Add a new TV serie to the 'Requests' list. But when I approve the serie it responds with the error.

**Comment by lokenx** [comment]
Plex Request, although SickRage may have something in it too. Not sure how you have it setup, but next version will have easier accessible/persistent logs.

You can add requests even if SickRage is having issues/isn' setup, so that's expected.

**Comment by TheVMaster** [comment]
Eh...where can I find the Plex Request logs (running it on Windows).

**Comment by lokenx** [comment]
Are you running it in a console window? Are you using a script? They're currently logging only to the console.

Is your SickRage using a self-signed SSL cert?

Worst case, could switch over to the `logging` branch, assuming you're up to date on master, and test the logs that way.

**Comment by TheVMaster** [comment]
I'm running it in the console windows. SickRage is not using SSL (although from the outside I'm connecting via SSL through a Apache reverse proxy). 

Here's the (console) log : 


C:\Apps\plexrequests>meteor
[[[[[ C:\Apps\plexrequests ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

I20151116-23:22:06.311(1)? Adding default settings
I20151116-23:26:03.028(1)? { [Error: failed [403] <?xml version="1.0" encoding="
UTF-8"?>
I20151116-23:26:03.028(1)?  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict/
/EN"
I20151116-23:26:03.028(1)?    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd
">
I20151116-23:26:03.028(1)?  <html xmlns="http://www.w3.org/1999/xhtml" lang="en"
 xml:lang="en">
I20151116-23:26:03.028(1)?  <head>
I20151116-23:26:03.028(1)?  <title>Access forbidden!</title>
I20151116-23:26:03.028(1)?  <link rev="made" href="mailto:admin@example.com" />
I20151116-23:26:03.028(1)?  <style type="text/css"><![CDATA[/*><![CDATA[/*><![CDATA[/*><![CDATA[/*><![CDATA[/*><![CDATA[/*><![CDATA[/*><![CDATA[/*><!--*/
I20151117-15:58:05.951(1)?      body { color: #000000; background-color: #FFFFFF
; }
I20151117-15:58:05.951(1)?      a:link { color: #0000CC; }
I20151117-15:58:05.951(1)?      p, address {margin-left: 3em;}
I20151117-15:58:05.966(1)?      ...
I20151117-15:58:05.982(1)? Error adding to SickRage

**Comment by TheVMaster** [comment]
PlexRequests is running on my Windows Plex host and SickRage (and CouchPotato) are running on a (different) Windows Host.

**Comment by lokenx** [comment]
What version of SickRage? I'm assuming you can add shows fine directly within SickRage?

Are they both in the same LAN, or does it go through the proxy?

**Comment by TheVMaster** [comment]
I am running this versioN : BRANCH: (master) / COMMIT: (c19526435dc15ba1bcd5827dd24d6a8e69c83e2b) 

They are both on the same LAN....

**Comment by lokenx** [comment]
Huh weird, did you try enabling the SSL option just to check.

**Comment by TheVMaster** [comment]
Yes tried that one. with the SSL option enabled I connect to a different FQDN (and over port 443) then with the SSL option disabled (and the port on default). 

Both give me the same issue :(

**Comment by lokenx** [comment]
And you are using the LAN ip address to point to SickRage? Only thing of note that I can see is something is blocking access: `Access forbidden!`

**Comment by TheVMaster** [comment]
NOpe....I am using the FQDN (Fully qualified domain name) to connect to Sickrage.

**Comment by lokenx** [comment]
Can you try just the IP? I'm worried it's something to do with your Apche setup.

**Comment by TheVMaster** [comment]
Tried the IP....same issue. SickRage is not running on apache, it is running on it's own (?) webserver software? The Reverse Proxy is not between the SickRage and PlexRequests systems.

**Comment by lokenx** [comment]
OK just wanted to make sure you they were talking to each other. Below is the API call to sickrage. Can you add your sever details, and try a TVDB of a show you're trying to add. And just enter the URL in a browser and let me know what you get back.

        http://192.168.0.1:8081/api/abcdef12345/?cmd=show.addnew&tvdbid=123456

**Comment by TheVMaster** [comment]
I receive the following error when I visit the url (http://192.168.0.1:8081/tvseries/api/1234aabb/?cmd=show.addnew&tvdbid=291517) 

Traceback (most recent call last):
  File "D:\Apps\SickRage\tornado\web.py", line 1390, in _execute
  File "D:\Apps\SickRage\tornado\web.py", line 2103, in prepare
HTTPError: HTTP 404: Not Found

But when I add /tvseries in the url (just like I configured it in PleqRequests) I receive a JSON file (to save/download).
http://192.168.0.1:8081/tvseries/api/1234aabb/?cmd=show.addnew&tvdbid=291517

**Comment by lokenx** [comment]
Are you running it out of a sub-directory, hence `/tvseries/`?

**Comment by TheVMaster** [comment]
Yes I am....

The content of the JSON file is : {"data": {"name": "Agent X (2015)"}, "message": "Agent X (2015) has been queued to be added", "result": "success"}

**Comment by TheVMaster** [comment]
the subdirectory is just to make sure everything works fine behind the reverse proxy (and all my usenet stuff behind one domain name).

**Comment by TheVMaster** [comment]
btw...couchpotato is also running from a sub-directory and is running just fine with Plex Requests ;)

**Comment by lokenx** [comment]
OK so what did you enter into URL to get the JSON response, that's what we want!

Wait, I think I see the problem! I think I put the directory after the API not before. Let me update and I'll let you now in a bit.

**Comment by lokenx** [comment]
OK, if you restart your app it should say a package updated, and give it a try after that!

**Comment by TheVMaster** [comment]
Eh....just restarted the application (shutdown meteor en started it again), but still same issue...

**Comment by lokenx** [comment]
Did it say a package updated?

**Comment by TheVMaster** [comment]
Nope :(

**Comment by lokenx** [comment]
Run `meteor update` in the project folder. Should see the below line (ignore the packages that can't update, they're locked to known working versions).

```
lokenx:sickragewrapper  upgraded from 0.0.6 to 0.0.7
```

**Comment by TheVMaster** [comment]
Now it says 'updating 3 packages'...and it indeed updated the sickragewrapper from 0.0.6 to 0.0.7

It is working now as expected! Thanks for the quick fix.
