### ISSUE TITLE
Separate page for issues?

### ISSUE THREAD

**Issue by damiantje99** [lokenx/plexrequests-meteor#180]
And my next issue! 

At the moment, users can only report issues when they added a movie or show. Maybe its an idea to let users create issues from the search. So when you have a show like "Game of Thrones" and for episode 2 of season 1 you have fault subtitles you can let users search for this episode and report an issue without adding the show. Same goes for the movies. Also it would be helpful for admins when users can select the problem, like fault subtitles or missing subtitles with the Language they missing. Therefore it would be easier to have a separate page for issues only. 

Note: If it isn't possible to add certain seasons or episodes, maybe you can add a text field or a small form, so they can specify the season and episode. 

Let me know how you think about this!

**Comment by lokenx** [comment]
Please refer to #129, updates will go in there regarding issues. But yes, it'll be changing to something like you've described.
