### ISSUE TITLE
Weekly limit 

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#181]
I would like the weekly like to be like per "app" becuase 25 on couch potato is not nearly as bad as 25 on sonarr.

So thinking like
Sonarr limit : 3
Couch potato limit: 10
Sickrage limit: 5 
Couchpotato2 limit: 5

**Comment by lokenx** [comment]
CouchPotato2? You running the two-couchpotato branch? That's really old and out of date...

**Comment by unixjeff** [comment]
That was for example, if that becomes an option in the future

**Comment by lokenx** [comment]
@rigrassm this would be a similar change as the approval splitting for movies and tv shows I pushed the other day. I believe the check only happens once during the request process but would need to confirm.

**Comment by rigrassm** [comment]
Just move the limits to each service and have it check based on type of the request

**Comment by rigrassm** [comment]
Question is should it be by provider(ie CP or Sonarr) or by content type?

**Comment by lokenx** [comment]
Type, [movies](https://github.com/lokenx/plexrequests-meteor/blob/master/server/methods/search/requestMovie.js#L10) and [tv](https://github.com/lokenx/plexrequests-meteor/blob/master/server/methods/search/requestTV.js#L9).

**Comment by rigrassm** [comment]
Be as simple as adding the field in the collections, the form fields and
change those lines from settings to {movies,tv}.

Working on learning how to live stream video right this second but once I
get that figured out I may jump on that real quick.

**Comment by lokenx** [comment]
Closing, will be merged this week, see #334
