### ISSUE TITLE
[Request] Add web root / path option for reverse proxy

### ISSUE THREAD

**Issue by fryfrog** [lokenx/plexrequests-meteor#182]
It would be great if you could add a web root / path option so that doing a reverse proxy is nice and neat. You've already got configurable sub paths for each application (since they support this), so you know of its existence.

Reasonable idea? Crazy idea? I'd appreciate it for sure.

**Comment by lokenx** [comment]
This is possible, checkout #88 for more details.

For a sub-directory you need to start meteor with (or pass an environmental variable on startup) `ROOT_URL="http://localhost/plex"`.

For a sub-domain, the reverse proxy would handle that in your config.

**Comment by fryfrog** [comment]
Did I miss this somewhere? Could you maybe add this as a FAQ entry for changing the path and/or port? :)

**Comment by lokenx** [comment]
It's not documented, but I shall add it.
