### ISSUE TITLE
Persistent admin link

### ISSUE THREAD

**Issue by Valaire** [lokenx/plexrequests-meteor#184]
I'm probably missing something obvious but I installed this app on Debian and ran it, created my admin account, set things up, and logged off the admin account.  I now cannot log back in as admin despite restarting the app.  The ability to sign in does not appear.

**Comment by Valaire** [comment]
Tried clearing cache, cookies, different browser, restarting meteor -- nothing.

**Comment by Valaire** [comment]
OK I found the admin login page by randomly trying the URL /admin.  You probably need to add some kind of consistent tab for finding the admin page because otherwise people will run into the same issue.

**Comment by lokenx** [comment]
The link is only visible when an admin is logged in, but I can see the use case for it being persistent.
