### ISSUE TITLE
Approving a TV series to Sonarr fails

### ISSUE THREAD

**Issue by hermy65** [lokenx/plexrequests-meteor#188]
Most of the time when someone requests a TV show and i go in to approve it i get a message saying it failed to approve. In the log i see this

[34mI20151127-08:33:41.983(-6)? [39mSonarr Series Post -> Match error: Expected string, got undefined

I am using the most up to date Sonarr and plexrequests

**Comment by lokenx** [comment]
Can you provide a few example shows? Do they work eventually, or they never are able to be approved?

**Comment by hermy65** [comment]
Ultimate Fighter is one, Vinyl was another and no, they never get approved. If i manually add the show to Sonarr and then click the Approve button then it approves without issue.

**Comment by lokenx** [comment]
Does the test button on the Sonarr page under Settings return success?

Also all the following fields are defined:

 - Server IP
 - Server port
 - API
 - Download quality profile
 - Root directory

**Comment by hermy65** [comment]
I blew away my config and now it seems to be working as intended. Will update if it happens again.
