### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by jkaberg** [lokenx/plexrequests-meteor#189]
So I tried takeing a stab at creating an Docker for plexrequests,

https://github.com/jkaberg/plexrequests-meteor
https://github.com/jkaberg/docker-plexrequests

But I've had a hard time wrapping my head around how the inner workings of meteor works. 

So I'm putting this one up there incase anyone else wants to take a stab at it.

PS: https://github.com/jkaberg/plexrequests-meteor seems to closest to functional. Unable to connect to the mongodb tho, IDK if we need to run another docker instance with mongo and connect to that?

**Comment by lokenx** [comment]
There is already a working docker version I believe. Maybe see if they can help out/or fork it if you want to add stuff.

https://github.com/aptalca/docker-plexrequests
