### ISSUE TITLE
Diffcult to config Sonarr in plex requests

### ISSUE THREAD

**Issue by whitecollar17** [lokenx/plexrequests-meteor#190]
Its very difficult to find the correct "Download quality profile ID". When you use a wrong ID, the serie add it in sonarr, but sonarr can't do anything because there is no quality profile linked to the serie.
You can't find it in sonarr, unless you do a try and error in plex request. I try to add 7 times a serie and change my profile id with +1 every time.
After eight times i found out my ID was 8.
is it possible to make a change in the admin panel that you can select the names of your quality profile instead of giving the ID (wat very hard and difficult to find?)

Also you can use a wrong or  invalid/ not existing ID and you get a sonarr error.
(It is a bug in sonarr also: https://github.com/Sonarr/Sonarr/issues/977 )

**Comment by lokenx** [comment]
I'll see if there's anyway to get this info from the Sonarr API. It's my biggest qualm with Sonarr in that it requires so many fields and doesn't support having defaults.

I'll try and get it added to 1.4 but it may have to wait until new year.

**Comment by Dahlgren** [comment]
Quality Profiles can be fetched from the `/api/profile` endpoint. See https://github.com/Sonarr/Sonarr/wiki/Profile for format
