### ISSUE TITLE
two characters Search

### ISSUE THREAD

**Issue by whitecollar17** [lokenx/plexrequests-meteor#191]
Search with two characters is not possible. 

Example: i like to add 24. But i need to give " " to find it otherwise, he doesn't search

![plex_search](https://cloud.githubusercontent.com/assets/2944704/11607719/1e428648-9b53-11e5-9646-f9359679bb7a.png)

**Comment by lokenx** [comment]
Huh never thought of two character shows! Search only triggers on 3 characters but guess I shall drop down to 2!
