### ISSUE TITLE
[Enhancement] More detailed logs

### ISSUE THREAD

**Issue by SmallwoodDR82** [lokenx/plexrequests-meteor#192]
Would be nice for the logs to be a touch more detailed.  

```
[34mI20151205-18:00:06.045(-8)? [39mSonarr Series Stats -> ESOCKETTIMEDOUT
[34mI20151205-18:00:08.049(-8)? [39mSonarr Series Stats -> ETIMEDOUT
```

Do we know if it hung on a certain series stat?

**Comment by lokenx** [comment]
Updated package as I mentioned in Gitter, let me know what it outputs now (I don't have Sonarr handy to test).

**Comment by SmallwoodDR82** [comment]
currently on 0.0.6 I will test.
