### ISSUE TITLE
[Request] show download progress requested film or serie

### ISSUE THREAD

**Issue by whitecollar17** [lokenx/plexrequests-meteor#193]
Hi,

In sonarr, you can follow the progress of the processing of a serie.
is is possible to show it also under "Requests"? 
Maybe the status: "Searching (sonarr/CP is searching for the serie or movie)" , "Downloading the serie / or movie", "Processing the file", "processed"

**Comment by lokenx** [comment]
That would require constant calls to Sonarr/SickRage/CouchPotato to keep up to date with that info and  I'm not sure if it's accessible from the APIs.

We do calls every 60 minutes to get up to date information. Is that too infrequent in your opinion?

**Comment by whitecollar17** [comment]
Sonarr is doing a call to nzbget every 1 minut. Maybe every 4 minut?

**Comment by lokenx** [comment]
Definitely don't see us doing that frequent calls. We are looking at adding user notifications in next version which would help with this. It's also possible to make the update frequency a user setting, however it'll still be the same level of info just more up to date.

It's been noted for the rewrite, thanks!
