### ISSUE TITLE
Wrong message when movie is on the watchlist of CP

### ISSUE THREAD

**Issue by whitecollar17** [lokenx/plexrequests-meteor#194]
When i request a movie, and the movie is on de CP watchlist (but the movie isn't downloaded) the message "movie is already on Plex shows up.
But isn't correct. The movie is not on plex but on the monitoring list of CP.
Maybe change the message in : Movie is allready on the monitoring list but not currently available

![wrong message](https://cloud.githubusercontent.com/assets/2944704/11614730/4595a164-9c4b-11e5-9d96-482ddddc4fe3.png)

**Comment by lokenx** [comment]
Just fixed this today! Update to 1.4.x

The popup is correct now, and the actual request button will show either requested or downloaded depending on CouchPotato status.
