### ISSUE TITLE
[Request] Choosing a Couchpotato quality level when approving a movie

### ISSUE THREAD

**Issue by Drewster727** [lokenx/plexrequests-meteor#195]
It's my understanding that PlexRequests just uses one particular quality level whenever a movie is approved and added to CP?

This is not ideal. Often times I'll get requests for older movies that do not have HD quality available. So if plexrequests adds a movie as "HD" or "1080p" then the movie will more than likely never be found. Before PlexRequests... when I added movies to CP manually, generally I would determine when the movie came out, let's say for example the movie came out pre-2000... I'll mark the quality level as "Best" to ensure it finds a copy, regardless of whether it's "DVD" quality or not, I want it.

I'm proposing that when the approver approves a movie, that there is a dropdown (queried from CP) with a list of the quality levels, and you choose one.

In addition, this same idea can be applied to TV shows as well, as an alternative to always defaulting to a specific quality profile.

Thanks.

**Comment by lokenx** [comment]
Right now we're just using whatever you have set as the default besides Sonarr which needs it explicitly stated.

I won't be changing this behaviour for this version, but I will strongly look into doing it for new rewrite. I'm closing this but have marked it in my private tracking for new version!
