### ISSUE TITLE
[Enhancement] You're all logged in!

### ISSUE THREAD

**Issue by Drewster727** [lokenx/plexrequests-meteor#196]
This may seem trivial, but I feel like the "You're all logged in!" page should not exist at all. If a user is already logged in it should default them to the "Search" page automatically, IMO.

Thanks!

**Comment by lokenx** [comment]
I agree! It was added recently because by putting a redirect in the back button behavior would get messed up and you'd get stuck on a page. I intend to look into how better to route things in the new version to handle this.

**Comment by Foebik** [comment]
I know in the past you shorten the timer on this page, I think it could even go shorter. 1 second, 1.5 seconds?

**Comment by dannyhanes** [comment]
^^ This. If I am already logged in just take me to /search. Thanks!

**Comment by DejaVu** [comment]
Further to this, I've been told by a Windows Phone user that clicking TV Shows in Search sends him to a "You're all logged in page". He cannot request TV Shows because of it on his phone.
