### ISSUE TITLE
Usage with systemd

### ISSUE THREAD

**Issue by icenine9** [lokenx/plexrequests-meteor#197]
I tried to add this to the wiki, but I guess it's locked down :) Here's what I would have added:

Plexrequests is easily run under systemd as a simple service under ubuntu and many other linuces. 

Step 1: 

Create the 'plexrequests.service' file in /etc/systemd/system:
-----------------------

[Unit]
Description=PlexRequest
DaemonAfter=network.target

[Service]
User=plex 
Type=simple
WorkingDirectory=/opt/plexrequests
ExecStart=/usr/local/bin/meteor
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target

-----------------------

Notes: 

-You may wish to edit the 'User=' entry to reflect which user will be running this daemon. 
-The 'WorkingDirectory' entry should point to where you installed plexrequests. 
-If meteor isn't installed to /usr/local/bin by default, change this location as well. Try running 'which meteor' from a bash prompt to find out where your instance of meteor lives.

After you have saved the plexrequests.service file, ensure any manually-started versions of plexrequests are killed/stopped, and enter the following commands: 

sudo systemctl daemon-reload
sudo systemctl enable plexrequests.service
sudo systemctl start plexrequests.service

Test your installation by visiting http://localhost:3000

That should be it!

**Comment by lokenx** [comment]
You got it to work :+1:

**Comment by jordanyeo** [comment]
Any tips on how to pass ROOT_URL to this script so I can run it through my reverse proxy? Thanks!

**Comment by catatonicChimp** [comment]
@jordanyeo did you figure out a solution to pass the root_url with systemd? I have the exact same issue having just updated to ubuntu 16.04...

**Comment by rigrassm** [comment]
`Environment=ROOT_URL=/subdir_path`

Add that into the systemd unit file and it should work. Double check the
actual variable name, I think that's it but it may be slightly different.
