### ISSUE TITLE
[Request] Certain Users don't require approval

### ISSUE THREAD

**Issue by causefx** [lokenx/plexrequests-meteor#198]
It would be nice if we could have a text box to input usernames for people that we will not require to have approvals on new requests :)

thoughts?

**Comment by lokenx** [comment]
A possibility, it can be added to the list!

**Comment by gen3ric** [comment]
An approval whitelist is a fantastic idea, because there are some people I trust not to abuse my setup and I don't want them to have to wait for me to be around to approve.

**Comment by zerorl985** [comment]
And if possible, a setting to select TV shows as the only media that requires approval.

**Comment by rigrassm** [comment]
Feature added with merge of pull request #351
