### ISSUE TITLE
[Issue] Server Timeout? Stall?

### ISSUE THREAD

**Issue by causefx** [lokenx/plexrequests-meteor#199]
Sup Everyone....  first off, thank you for this awesome app.  I love it!

OK, so I was messing around and was just testing some things out on the app running on a Windows 10 VM as I have a QNAP NAS and this will not run on there.

Everything was setup and good to go, everything was rocking out nicely...  SO i decided to see what would happen if someone entered their login info incorrectly or tried to make another admin account......

![login](https://cloud.githubusercontent.com/assets/16184466/11619818/32e663e6-9c69-11e5-9552-ebbd38519432.png)

After it told me only login was incorrect on the first test and the other said one admin allowed on the 2nd test, the app stopped working and would just try and load and load over again....

![loading](https://cloud.githubusercontent.com/assets/16184466/11619819/32e84e4a-9c69-11e5-849e-9ed0f650bde8.png)

So I logged into the VM to see the command prompt and restart the app...  This screenshot was take after a few tests but originally there wasn't any error listed there...
![cmdlog](https://cloud.githubusercontent.com/assets/16184466/11619816/32e5adfc-9c69-11e5-921f-e2a2d3211a37.png)

So I hit CTRL-C once and the error popped up and the app started working again.... lol... weird right?
![cmdlog2](https://cloud.githubusercontent.com/assets/16184466/11619817/32e5ce5e-9c69-11e5-9e6a-be272750de60.png)

just thought I would let someone know....

Thanks...

**Comment by lokenx** [comment]
Huh weird, not sure what happened there! Can you get it to crash reliably?

The logs are also available on the admin page too FYI.

**Comment by causefx** [comment]
crazy thing now, so it seems it doesn't do it anymore...   tomorrow I will restart the server and try again from scratch.

**Comment by causefx** [comment]
LOL, so i just tried to sign in with my plex account and i accidentally typed in the wrong password and it stopped the app again... i had to CTRL-C it again and got this:

![image](https://cloud.githubusercontent.com/assets/16184466/11620371/76c7ff2e-9c6f-11e5-9653-11f739e766b0.png)

**Comment by lokenx** [comment]
To login as a user or an admin? What version are you on?

**Comment by causefx** [comment]
login as a user, i'm on the newest version.

![image](https://cloud.githubusercontent.com/assets/16184466/11631350/dfc4cbde-9cbe-11e5-8715-c13a1b44b745.png)

**Comment by lokenx** [comment]
Do you get the notification pop-up that your credentials are wrong?

I have no idea what could be causing that, and I can't get it to do the same :confused:

**Comment by causefx** [comment]
I cant get it to work or should i say not work now....

I do get a notification.... its just weird...  Do you think it might be because i ad command prompt open still after running meteor?

**Comment by lokenx** [comment]
Nope that would have nothing to do with it as far as I know. Re-open if it arises again and you can reproduce it, otherwise I'll chalk this weirdness :8ball:
