### ISSUE TITLE
[Request] Allow login via e-mail address

### ISSUE THREAD

**Issue by Drewster727** [lokenx/plexrequests-meteor#201]
I've noticed a pattern with some of my users regarding an issue with logging into plexrequests.

Several of my users apparently login to plex web via their plex email and password, as opposed to their plex username and password. So they are thoroughly confused when they are unable to login to plexrequests.

Can we allow authenticating via plex email/password?

Thanks!

**Comment by lokenx** [comment]
You can't authenticate to the Plex.tv API via email unfortunately it only takes username. I'm trying to think of ways to better handle this but can't say for now.
