### ISSUE TITLE
Message "Movie is already on Plex"

### ISSUE THREAD

**Issue by DCPDad** [lokenx/plexrequests-meteor#204]
Hi!
Loving PlexRequests - makes the whole package that much more professional. Thank you.
I am seeing an incorrect message though: when adding a movie to PR I always see a notification in the lower right corner that says "Movie is already on Plex" even though it isn't.

Let me know if you need any more details.
TY!
![plex requests](https://cloud.githubusercontent.com/assets/8687743/11719509/f39f3894-9f0f-11e5-83d8-f123c1150810.jpeg)

**Comment by lokenx** [comment]
It's been fixed in 1.4.x , give the app an update and let me know!
