### ISSUE TITLE
Reset Admin Password

### ISSUE THREAD

**Issue by hematic** [lokenx/plexrequests-meteor#205]
So when i installed and set this up i made an admin password but never put it in my password manager. From what i can tell, there is no way to reset or change it now and i am locked out of the admin console. There should definitely be an option to do so.

Thanks for all your hard work!

**Comment by Drewster727** [comment]
+1

**Comment by lokenx** [comment]
Currently there's no way to reset the password (I know, I need to add it).

But there is a way to delete the user DB which will allow you to create a new one and you shouldn't lose any settings or requests as they're in separate databases.

This assumes the app is running on the same machine using `meteor` and it's development server.

```
meteor mongo
db.users.find().pretty()

// Should see a single user. Verify this is the admin account you made!

db.users.drop()

// Should output true if successful

exit
```

**Comment by hematic** [comment]
Thanks this is exactly what i needed :)

**Comment by lokenx** [comment]
No worries, sorry about that! Accounts were slapped together last minute so weren't fully developed, new version will fix this!

**Comment by Kryptonit3** [comment]
how do you run this?

**Comment by lokenx** [comment]
From the command line that the machine that the application is running on.

**Comment by Kryptonit3** [comment]
@lokenx could you possibly implement a change password field inside the admin panel with a confirmation input to prevent accidents?

**Comment by Kryptonit3** [comment]
@lokenx hey, just wanted to say I love this idea and am currently working on a PHP/Laravel/VueJS version.

![img](http://snag.gy/WgGVx.jpg)

**Comment by lokenx** [comment]
That's awesome, if you get it up to same features as mine I don't have any issue helping you bring it forward. I don't know PHP really but I love VueJS. 

I have started working on a python one as people kept asking for it, but it's still early days compared to your PHP one it seems.

**Comment by Kryptonit3** [comment]
The only thing I really have left to do is the api stuff for the different apps. Will tackle that later this week.

**Comment by lokenx** [comment]
Cool, let me know when repo is up!

**Comment by Kryptonit3** [comment]
Sure thing. I haven't the slightest clue how MeteorJS works or anything "NodeJS". I was running your app trying to see the calls in the console and couldn't find any ajax requests. I looked through the repo quite a bit and couldn't find any of the "gritty" stuff, like your API calls etc to see how you are formulating your requests and handling responses. 

I found a really cool TMDB php api from some guy on github, I wrapped his package up so it could be used in composer/packagist and it has helped quite a bit https://github.com/Kryptonit3/TMDB-Laravel

**Comment by lokenx** [comment]
Ah meteor doesn't work in the traditional way, it's all DDP based real time communication. It opens a socket to the server that you can call methods through instead of Ajax calls. It's used mainly in real time applications,  changes propagate instantly instead of having to make a call for new data.

Whenever you see Meteor.call(…) in the client folder that's calling a server side method similar to an Ajax request inside the server folder.

I'm sure PHP has something similar but in the node world the main way to do it is via sockets.io if want to check it out.

**Comment by Kryptonit3** [comment]
@lokenx I added you to the private repo. It is not done yet but a lot of the ground work is. I still need to interface a few more apis and write some more logic. email me at jesse.szypulski@gmail.com so we can talk more. I cannot seem to find your email.

It is visible to you until it is done (currently private). Curious to see what you think.

**Comment by jonfairbanks** [comment]
Was able to delete via mongo but wishing this was part of the UI. :smile:

**Comment by Rikumo1978** [comment]
No matter what I do, I cannot find a way to undo this. I've tried the mongo way, there is 0 guides online on how to accomplish this. I am officially locked out of your software until further notice? :(

**Comment by jonfairbanks** [comment]
Mongo DB -> `Users` collection -> Delete documents in collection. If you don't want to do it via command line, try using Robomongo.

**Comment by sogeniusio** [comment]
@Kryptonit3 - how far are you with this?

**Comment by hosquiat** [comment]
> @lokenx hey, just wanted to say I love this idea and am currently working on a PHP/Laravel/VueJS version.
> 
> ![img](https://camo.githubusercontent.com/86378e58fc86cfc0ba83bed22bd353803d4451da/687474703a2f2f692e736e61672e67792f57674756782e6a7067)

Kryptonit3 - how far are you with this
