### ISSUE TITLE
[Request] Custom Notification Messages

### ISSUE THREAD

**Issue by jrdnlc** [lokenx/plexrequests-meteor#209]
Custom formatted text for each type of notification. You can provide a set of parameters that can be used. 

Current format:

The Uninvited requested by  ng67_

Possible parameters:

The Uninvited requested by  {plex user email}
 The Uninvited {movie year} requested by {plex user email}
The Uninvited requested by  {plex user name} - if possible

Just an idea I would love to see it get implemented :D

**Comment by lokenx** [comment]
Cool idea, shall add to list for new version!

**Comment by rigrassm** [comment]
Submitted pull request to the Dev branch that incorporates this functionality. Still has some little bugs I need to work out and lots of optimization but it is stable enough for testing. Consider it in beta testing.

**Comment by jrdnlc** [comment]
@rigrassm Awesome can't wait until it's released!

**Comment by rigrassm** [comment]
@jrdnlc If you want to test it out you can clone it from my repo and do a git checkout new-tvdb. That branch has the custom notification, pushbullet channel support and a new TV search provider called TVMaze(much better search results than what TMDB gives). 

http://github.com/rigrassm/plexrequests-meteor

**Comment by rigrassm** [comment]
Feature has been implemented. The readme will be updated soon with examples.
