### ISSUE TITLE
Create test page for Sonarr

### ISSUE THREAD

**Issue by lokenx** [lokenx/plexrequests-meteor#21]

**Comment by jrudio** [comment]
Do you guys still need help with Sonarr? I think I can get a test page going.

**Comment by lokenx** [comment]
I just started it this afternoon, should see a update later tonight/early tomorrow you can use to start working on it if you'd like.

**Comment by jrudio** [comment]
Ok, sweet. What exactly are you working on? I have the test page working, but the design is barebones.

**Comment by lokenx** [comment]
Basic Sonarr support is done, still need to work out a few details.

The test page would be the same as the Couch Potato and SickRage test pages, just with the extra fields Sonarr requires.

**Comment by jrudio** [comment]
Nice. I recently had seen your project on the plex forums and that it was built with Meteor, so it really interested me. It sounds like you got most of it done. Is there anything I can do?

**Comment by lokenx** [comment]
Well for the test page, gotta write the Meteor call for checking whether Sonarr is up (it's empty now, refer to SR/CP functions) and then make new template pretty much same as SickRage on, but displaying the extra settings fields, doing a check whether there's a slash at the end (there shouldn't), and updating the things to check when stuff isn't working to be Sonarr specific.

Alternatively if you use PushOver, that's a heavily requested feature I've yet to implement (I don't have an account so need to get one setup first!)

**Comment by jrudio** [comment]
I'll work on the sonarr page, but looking at sickrage.html i'm just curious as to why there is an inline script for $(document).ready() ?

**Comment by lokenx** [comment]
It makes the two calls when the page loads to check the status:

`Meteor.call('checkSR')` for if we can communicate with SickRage
Meteor.call('checkSREnabled')` for if it's enabled or not

If there's an easier way to do this in the sickrage.js file please do so--I could never get it to work with updating the various DOM elements to show/hide depending on what the check's returned.

**Comment by jrudio** [comment]
Ok I have most of it down, but as far as the content of the page goes how do I word manual test? Because I believe you have to send the header X-Api-Key to test it.

**Comment by lokenx** [comment]
Bad at button presses... PR merged.
