### ISSUE TITLE
Requests are not waiting to be approved and notifications not sending.

### ISSUE THREAD

**Issue by wilsonic** [lokenx/plexrequests-meteor#211]
I'm not sure when this started, probably in the last month. Whenever someone requests new content they are automatically approved and sent on for download even though I have "Require approval of requests" check on. 

Notifications through pushbullet are also not working for requests though they do work when I "Test Pushbullet". 

The log page doesn't give me much to go on in terms of troubleshooting. Is there another place I can look to see exactly what's happening behind the scenes that may help me/us figure this out?

**Comment by gjunkie** [comment]
Notifications thru Pushbullet also not working for me. I don't have "Require approval of requests" enabled. Testing Pushbullet also works as expected.

**Comment by lokenx** [comment]
Can you open a ticket for Pushbullet if there isn't one already? I'm getting them while on holidays so not sure what's wrong. You've triple checked the API key, and nothing in logs?

Regarding approval, are they new shows? Is it movies? What provider for downloading if TV? What version of app and OS?

As much info as possible so I can look when back in the new year.

**Comment by lokenx** [comment]
Please provide some more details and what version you are on and we can re-open this.
