### ISSUE TITLE
Version: 1.4.1

### ISSUE THREAD

**Issue by nucshuco** [lokenx/plexrequests-meteor#212]
Im running plexrequests on windows 7. when i go to admin page and select about it shows im running Version: 1.4.1.
![image](https://cloud.githubusercontent.com/assets/8262089/12005806/c5273b56-ab6c-11e5-8876-311ec0ebb1ca.png)

but at
http://plexrequests.8bits.ca/changelog/
it shows v1.3.0 

![image](https://cloud.githubusercontent.com/assets/8262089/12005814/2aec2bfe-ab6d-11e5-94e2-25a4b5296b44.png)

I even deleted my install and started fresh. Same Version: 1.4.1 
Is this a bug? or did I mess something up?

**Comment by Drewster727** [comment]
I don't know for sure, but I'm pretty sure the website changelog just hasn't been updated to reflect 1.4.1

**Comment by lokenx** [comment]
Yeah, I sometimes forget there's a change log on the site, apologies I shall update it once back from holidays. For the mean time if you go to the releases section on GitHub there should be notes for most versions.
