### ISSUE TITLE
Error when running on RPi

### ISSUE THREAD

**Issue by my95z34** [lokenx/plexrequests-meteor#214]
Hello, I have found a version of meteor that is modified to run on the RPi, but when running PlexReqeusts, it errors out.  I know nothing about meteor and the like, so I figured I'd ask here if it was a meteor issue, or PR issue. 

Here's the output:  http://pastebin.com/h8SwsbRM

And here is the version of Meteor I'm using: https://github.com/4commerce-technologies-AG/meteor

I have tried this version: https://github.com/IGx89/meteor, but that errored out like this: http://pastebin.com/Pxwk3G2g

So, I guess it's probably a Meteor issue?  

Thanks in advance!

**Comment by lokenx** [comment]
This error:

```
Error: EACCES, open '/opt/meteor/.git/hooks/pre-commit.meteor-hook'
```

seems to be something to do with permissions, I don't think it's even got to the PR stuff yet.

**Comment by lokenx** [comment]
There was some discussion on the forums regarding this, if that doesn't help let me know and we'll re-open.

https://forums.plex.tv/discussion/151899/plex-movie-requests/p59

**Comment by my95z34** [comment]
Sorry, I forgot to reply to this a few days ago.  Life has been pretty crazy.  Anyway, I'll try out the procedure from the forum that you linked.  Thanks for that!
