### ISSUE TITLE
[Request] If the server is not set to require approval, it does not list the requests

### ISSUE THREAD

**Issue by dellipse** [lokenx/plexrequests-meteor#215]
The list of requests does not get populated by items that do not require approval. It would be nice to have the list still populated (or have it as an option) so the requester can check upon their request to see if it has been added, etc.

**Comment by jrdnlc** [comment]
Excellent idea. Also, if it gets denied have have the option to enter the reason and when the user checks the status it can show them why it was denied etc etc

**Comment by lokenx** [comment]
I'm confused what you're after. You don't want requests to populate the list if set to not require approval? I don't see the benefit to that, please elaborate!

**Comment by Foebik** [comment]
I think if you just have the filter default to not approved, it would solve this. But then you have the problem of people not thinking to change the filter to see the approved ones. Maybe have a separate tab for not approved would solve both problems

**Comment by lokenx** [comment]
Closing. Please provide more details as it's not 100% clear what you're after.
