### ISSUE TITLE
Available Status is Always X

### ISSUE THREAD

**Issue by thomaskendall** [lokenx/plexrequests-meteor#216]
Seems like the Available status is always set to X.  Does couchpotato, sickrage or sonarr have to be enabled for checking if the requested item is already available?

**Comment by Foebik** [comment]
Currently it uses the databases from those app to determine if something is available (downloaded). So yeah, if you dont have them enabled then it wont show. My question is if you dont have have any of them enabled how are you even using PlexRequest?

**Comment by thomaskendall** [comment]
As a simple plex request system.  Yes ultimately I want to connect it to couch potato and sickrage on my rp2's but not yet.  For now I guess I'll just connect couch potato and let it search that list, just seems like it should be searching plex for these results.

**Comment by lokenx** [comment]
It should be, and it will be! Work will be stating again on new version as I just got back from 3 weeks away.
