### ISSUE TITLE
[Request] API

### ISSUE THREAD

**Issue by brettyj** [lokenx/plexrequests-meteor#217]
Hi, 

Firstly great app! 

I wonder if it's possible for someone to build a REST api for this? I'd love to be able to approve / deny from a mobile app for example, but for this to happen developers need a API to work with. 

Thanks

**Comment by lokenx** [comment]
Currently Meteor works with web sockets and doesn't expose an API. I'm actually working on the new version that isn't using Meteor that will have a more traditional API back end and web front end, that other apps and such can hook in to.

Also, the website should reformat itself to be usable on mobile, does something in particular not work on the mobile side of things?

**Comment by brettyj** [comment]
Hi,

Nothing is wrong with the mobile view, I would just personally prefer to
use NZB360 as I can administer the Sonarr/Couchpotato/NZBGet setup from one
place, and I would love the potential to be able to get PlexRequests in
there where I can simply see a list of requests and can press one button to
approve or deny.

Thanks

**Comment by Foebik** [comment]
I dont currently have NZB360 installed right now. But if PlexRequest was somehow added to it (it's author would have to do it) then I could see myself using it again. PlexRequest would just need some API hooks that the NZB360 Author could use.

**Comment by lokenx** [comment]
Will have an API in new version, planning it out [here](https://github.com/lokenx/plex-requests/wiki/API).
