### ISSUE TITLE
Added items not changing to available

### ISSUE THREAD

**Issue by ScouseTS** [lokenx/plexrequests-meteor#219]
I just wanted to say this project is excellent and keep up the good work.

Is there anyway to manually change a requested show to available? Everytime I add a requested file (auto approved) the available status never changes, I can see it in my plex library and plex requests is linked to my plex account for the user auth.

I don't use any of the auto downloaders, I prefer to manually dl them so that I can prevent people filling my server up in next to no time.

Would be handy if I could get this working so I don't have to contact people and let them know their stuff is added, I've tried the dev and master version to no avail. I'm running plex requests on Windows Srv 2012 :)

**Comment by lokenx** [comment]
Currently you can't manually change the available status of items, sorry! However, the next version will be looking directly to Plex for available status of shows (not the downloading apps) so it'll work then for you, and others, that don't use auto-downloaders.
