### ISSUE TITLE
Reverse proxy support

### ISSUE THREAD

**Issue by gen3ric** [lokenx/plexrequests-meteor#220]
I'm using Apache2 to proxypass to PlexRequest, however it doesn't seem to be able to handle my URL path as none of the resources are able to load. 

Any suggestions on how to do this, or confirm whether or not you'll add a configurable field? CouchPotato and Sonarr have this option, making it very simple.

**Comment by lokenx** [comment]
I've mine behind an nginx proxy without issues (to a subdomain). Subdirectories should work as well. Refer to #68 as well. You need to pass the `ROOT_URL` variable on startup.

Give the issues a search as I think there's a few others regarding this.

**Comment by gen3ric** [comment]
Alright, I forgot to check closed issues. It'd still be nice to have an enhancement to make it a little easier but as long as the functionality exists (`ROOT_URL`) I see no rush. Although, perhaps it would make sense to include that in installation documentation.

**Comment by KrunchMuffin** [comment]
Sorry to post on a closed issue, but trying to figure out how to run meteor with root_url in windows. It doesn't work for me. 
`ROOT_URL=http://foo.com/requests meteor.bat`
`'ROOT_URL' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by lokenx** [comment]
I believe you need to use `set` before ROOT_URL on Windows.

Sorry replying to emails doesn't seem to be working for me.

**Comment by mattpulpfree** [comment]
Sorry to jump in here as well and open an old issues but didn't want to really open a new since it's not really a issue.
  i've got multiple reverse proxy's set up in nginx right now that looks like this

`server {
        listen       80;
        server_name  monolith.com, 192.168.1.3;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location /sickrage {
          proxy_pass http://127.0.0.1:8081;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
		
		location /web {
			proxy_pass http://127.0.0.1:32400;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		}
		location /plex {
			proxy_pass http://127.0.0.1/web;
		}
		
		location /couchpotato {
			proxy_pass http://127.0.0.1:5050;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		}`


Would I just add `$ ROOT_URL=http://site.url/subfolder meteor` above that? Will that affect anything else in my nginx reverse proxy?

**Comment by lokenx** [comment]
What do you mean above that? That is how you would start meteor up so it runs from the sub directory. I believe nginx configs have been posted before.
