### ISSUE TITLE
Issue with setting up Sonarr/CP integration when http authentication is enabled

### ISSUE THREAD

**Issue by nbisson** [lokenx/plexrequests-meteor#221]
Hey. Just wanted to say awesome work so far on this web app. I was contemplating making a system that would accomplish this but you did a better job in half the time!!!

Main issue is that I have sonarr/CP set up (host info and port info is working and verified) as well as http form authentication enabled for both. The problem is that I cannot access either of these services from PlexRequests. There doesn't seam to be authentication method with PlexRequests to connect to those services. Adding username and password textboxes for eace would solve the issue.

Thanks for the help and all the hardwork!

**Comment by lokenx** [comment]
You shouldn't require a username and password when talking to them, we use their API keys. I have a username/password on my Couch Potato install and there are no issues (don't use Sonarr so can't talk to them but I assume it's the same).

Have you entered your API key and verified it's correct? Does the test button work once you've entered everything and hit save?

**Comment by nbisson** [comment]
My mistake. It looks like my directories were incorrectly set so it was triggering a failed test. Maybe a user prompt for an incorrect setting would help people set this up. 

Thanks for the troubleshooting!

**Comment by lokenx** [comment]
Glad it worked, and yes things will be different in new version!
