### ISSUE TITLE
Error adding to SickRage

### ISSUE THREAD

**Issue by Cruv** [lokenx/plexrequests-meteor#222]
I have been dealing with this issue for about a month. Anytime I try to add a show to SickRage via PlexRequests I get the error:
"Error adding to SickRage"

I have tested the SickRage api settings and get "Success!" but it still will not let me approve a show. What info can I provide to get some help from you guys?

Thanks for your time and great work!

EDIT: I should say that it was working up until some time in November after a SickRage update.

Here is my Sickrage commit:
BRANCH: (master) / COMMIT: (9226ba5efba06fb9defc5272f03dae5d6d1c4145) 

and I am on version 1.4.2 of PlexRequests as I have tried uninstalling and reinstalling today just to see if that would fix it.

**Comment by duramato** [comment]
@Cruv That SR commit is on the old repo , i would recommed switching the SR repo and see if the issue is present there too (most likely it wont be)

**Comment by Cruv** [comment]
I'll give it a try and report back. I had heard that their project splintered into another group but didnt think to switch. Thanks @duramato

**Comment by Cruv** [comment]
It worked! Thanks for your help.

**Comment by duramato** [comment]
@Cruv Glad to help
