### ISSUE TITLE
Request are not processing

### ISSUE THREAD

**Issue by relay7565** [lokenx/plexrequests-meteor#224]
I just setup PlexRequests.  I tried to request a movie and see these errors in the log:

```
I20160109-23:32:44.584(-5)? { [Error: ETIMEDOUT] stack: [Getter] }
W20160109-23:32:44.587(-5)? (STDERR) error: Error getting IMDB ID: Unabled to get external ids [503]
```

The request button doesn't change from *Requesting*.  No errors are reported to the requesting page.

**Comment by Foebik** [comment]
I just started getting that last night as well.
These are the two movies I can't approve. Others are working as expected so I think this might be a IMDB issue.

Halo 4: Forward Unto Dawn
Halo: The Fall of Reach

**Comment by lokenx** [comment]
That sounds Iike the TVDB API is having some issues (a second call to it is required to get the IMDB ID).

I'm planning on moving to the OMDB going forward which should cut down on API calls, just trying to figure out plot summaries and posters.
