### ISSUE TITLE
Admin Always Available After Registering

### ISSUE THREAD

**Issue by kiteboy** [lokenx/plexrequests-meteor#227]
Hi
Possibly user error somewhere but no matter what I do Admin is still available and able to register multiple accounts
Ive removed the plexrequests folder and uninstall meteor and reinstalled from scratch and tried again.
Registered an admin account.....stop plexrequets.....restart......admin option is still there???

This is on Ubuntu Server 14.04

**Comment by lokenx** [comment]
What do you mean it's still there? The login/sign-up form will always be there, but when you try and create the second account it'll bounce back and stop you.

**Comment by kiteboy** [comment]
Sorry being a complete dick - thought it would go and not even have the option to register another account- apologies!

**Comment by lokenx** [comment]
No worries, was easier just to do it this way!
