### ISSUE TITLE
Sickrage requests fail to approve

### ISSUE THREAD

**Issue by Cringely** [lokenx/plexrequests-meteor#229]
Able to get SickRage test to complete successful, but requests stall out app and log shows "error - Error adding to SickRage"

Do any more detailed logs exist to troubleshoot? I've tried different shows and verified that couchpotato integration works fine.
![image](https://cloud.githubusercontent.com/assets/759077/12315382/4c20ed20-ba48-11e5-9ee9-eb94a038d1ac.png)

**Comment by duramato** [comment]
What version of SickRage are you running? @Cringely

**Comment by Cringely** [comment]
The latest commit from the master branch.

http://i.imgur.com/x1oByi2.jpg

**Comment by duramato** [comment]
Thats the old SR repository thats broken ,try switching to the new one http://www.github.com/SickRage/SickRage and see if that presists.. (Most likely wont)

**Comment by lokenx** [comment]
@Cringely what @duramato said! The old repo is broke for some reason--not sure what happened but people should be moving to the new one (ignoring the silly messages from the disgruntled creator).
