### ISSUE TITLE
[Request] German/Multilanguage Metadata

### ISSUE THREAD

**Issue by Jonn3y** [lokenx/plexrequests-meteor#232]
Hey,

i like the PlexRequests-Tool. But it gets only english metadata from themoviedb.org.
I'm able to search the german title, but I only get the english metafile:

Example:
Search: "Das Beste kommt zum Schluss" 
What I get: "The Bucket List" + English Poster + ...

<img width="973" alt="screenshot" src="https://cloud.githubusercontent.com/assets/11927089/12350287/75713c96-bb76-11e5-9777-eea0bd4a0aec.png">

URL-Difference: 
https://www.themoviedb.org/movie/7350-the-bucket-list?language=en  (What I get)
https://www.themoviedb.org/movie/7350-the-bucket-list?language=de ( What I want)

Is it possible to insert a option to set a language, so the script shows a different language than english?!
Would be awesome!

--
Jonn3y

**Comment by zobe123** [comment]
I've created a german fork here: https://github.com/zobe123/plexrequests-meteor, maybe this is what you lookin for.

**Comment by lokenx** [comment]
That would work. Could also find a way to create a variable that the admin can set for this.

**Comment by lokenx** [comment]
Not currently looking to implement, but can revisit with new versions! @zobe123 fork could also work for you. Not sure what branch he's working off (dev is old/stale) but hopefully it helps!
