### ISSUE TITLE
Sonarrwrapper does not have method 'profilesGet' for fetching profiles.

### ISSUE THREAD

**Issue by Collisionc** [lokenx/plexrequests-meteor#234]
Just need to accept the pull request from here:  https://github.com/lokenx/sonarrwrapper/pull/1

**Comment by Dahlgren** [comment]
Yes, profile selection won't work without it

**Comment by lokenx** [comment]
My bad I had the pr locally merged hence worked for me. Should be good now, may just need a restart/update.

**Comment by brettyj** [comment]
I've updated to the latest Master as of 18/01/2016 - 12:45 UTC - and restarted the app and I'm still getting this:

20160118-12:44:47.275(0)? Exception while invoking method 'sonarrProfiles' TypeError: Object [object Object] has no method 'profilesGet'
I20160118-12:44:47.275(0)?     at [object Object].Meteor.methods.sonarrProfiles (server/methods/admin/sonarrProfiles.js:3:1)

**Comment by dshokouhi** [comment]
@brettyj I had the same error and synced the latest changes from this morning and it is working fine now, I suggest you update to the latest and try again as well.

**Comment by lokenx** [comment]
Yeah, I forced the version update on the master branch in case it wasn't updating itself for you. Let me know if it doesn't work and we can re-open.

**Comment by brettyj** [comment]
This time the Quality Selector was populated, so once I saved that, it began to work fine.

Cheers

**Comment by abien** [comment]
Is it me - or could this still be an issue when using the app via docker?

**Comment by lokenx** [comment]
You mean in the sense that the versions aren't being updated? Or what you thinking?

**Comment by abien** [comment]
I fired up a new instance of plexrequests via docker yesterday evening. Couldnt get the sonar integration to work. In the Admin Backend, the "Download quality profile" Dropdown is empty & i cant aprove a request in the request tab. It causes the profilesGet error.

**Comment by lokenx** [comment]
So the docker way isn't pulling in most up to date stuff even though I've updated the master branch to use the newest versions.

You using the docker file or how you doing it exactly? I don't use docker but maybe the guys who set it up could see what's up.

@jkaberg @aptalca

**Comment by abien** [comment]
I would guess so. Here is basically what i did:
$> git clone https://github.com/lokenx/plexrequests-meteor.git
$> (added ROOT_URL to docker-compose.yml)
$> docker-compose up

version.txt shows 1.5.0

**Comment by aptalca** [comment]
That's not my docker container.  docker-compose.yml is pointing to jkaberg's docker image. His image was last pushed 4 days ago. It's may be the issue. I'm not sure. 

I had nothing to do with that file.  My container is merely a wrapper that installs both meteor and plexrequests from their github sources. It updates both every time the container is started. Instructions for mine are on the following page:  https://hub.docker.com/r/aptalca/docker-plexrequests/

**Comment by jkaberg** [comment]
As noted in https://github.com/lokenx/plexrequests-meteor/pull/238 @lokenx need's to setup an automated docker build @ hub.docker.com against this repo and update https://github.com/lokenx/plexrequests-meteor/blob/master/docker-compose.yml#L4 accordingly
