### ISSUE TITLE
Updated to emergency push, now I get a lot of exceptions...

### ISSUE THREAD

**Issue by alternativesurfer** [lokenx/plexrequests-meteor#236]
This is what I see being logged in my plexrequests window now that I've updated to the newest version 
```
[[[[[ C:\plexrequests ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

I20160118-08:32:05.069(-8)? Exception while invoking method 'sonarrProfiles' Typ
eError: Object [object Object] has no method 'profilesGet'
I20160118-08:32:05.069(-8)?     at [object Object].Meteor.methods.sonarrProfiles
 (server/methods/admin/sonarrProfiles.js:3:1)
I20160118-08:32:05.069(-8)?     at maybeAuditArgumentChecks (livedata_server.js:
1698:12)
I20160118-08:32:05.069(-8)?     at livedata_server.js:708:19
I20160118-08:32:05.069(-8)?     at [object Object]._.extend.withValue (packages/
meteor/dynamics_nodejs.js:56:1)
I20160118-08:32:05.069(-8)?     at livedata_server.js:706:40
I20160118-08:32:05.069(-8)?     at [object Object]._.extend.withValue (packages/
meteor/dynamics_nodejs.js:56:1)
I20160118-08:32:05.069(-8)?     at livedata_server.js:704:46
I20160118-08:32:05.069(-8)?     at tryCallTwo (D:\Users\Administrator\AppData\Lo
cal\.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\
promise\lib\core.js:45:5)
I20160118-08:32:05.069(-8)?     at doResolve (D:\Users\Administrator\AppData\Loc
al\.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\p
romise\lib\core.js:171:13)
I20160118-08:32:05.069(-8)?     at new Promise (D:\Users\Administrator\AppData\L
ocal\.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules
\promise\lib\core.js:65:3)

```

**Comment by lokenx** [comment]
Can you restart the application? It's not picking up an update for the Sonarr package.

**Comment by alternativesurfer** [comment]
That did it, thanks!

**Comment by dshokouhi** [comment]
Hmm I tried to restart sonarr and plexrequests but I am still getting the same exception.  Am I doing anything wrong?

**Comment by lokenx** [comment]
Hmm. In your `.meteor` folder inside the project, what's the sonarrwrapper version which you can get from the `versions` file. It should be `0.0.8`.

**Comment by dshokouhi** [comment]
it is showing up as 0.0.7

**Comment by lokenx** [comment]
The versions are suppose to get checked at startup and updated themselves. I've forced it to update on the master branch to see if that helps.

**Comment by dshokouhi** [comment]
Excellent worked perfectly! no more errors and my quality profiles are being pulled in.  Thank you so much!

**Comment by geekjoe02** [comment]
updated running .0.0.8 and still not pulling in quality options in the config.  Its like there is a drop down box that wont drop down.  I tried restarting both sonarr and plex requests.  Any suggestions on what im doing wrong.  I am on windows and sonarr lives on the pc that plex requests is on but the library lives on a drobo NAS.

**Comment by geekjoe02** [comment]
The error I am getting now is new though... Sonarr Series Post -> Match error: Expected number, got undefined

**Comment by lokenx** [comment]
OK that last error is something unrelated about not getting a tvdb id which isn't being caught. Try a different show?

**Comment by lokenx** [comment]
But the dropdown is populating with anything? Any ideas @Dahlgren

**Comment by geekjoe02** [comment]
The dropdown is not populating at all and i tried 5 shows all the same error message

**Comment by geekjoe02** [comment]
Ok guys.. rebooted.. restarted the app.. and the drop down started working.  We are up and running..

I am gonna drop a few bucks in the paypal!

Thanks for the help.

**Comment by Dahlgren** [comment]
Great :)

**Comment by lokenx** [comment]
Glad it's working! Note to self, move this feature to the new version when I get to the Sonarr integration :thought_balloon:

**Comment by alternativesurfer** [comment]
I am getting the original Sonar error once more.
I have it disabled, and do not run Sonar on my machine.

And what are these "quality profiles" I see people referencing above?

**Comment by lokenx** [comment]
Can you do an update of the application, even if it says there isn't an update. You're sonarrwrapper package must still be out of date for some reason. A restart wouldn't hurt either. It should be `0.0.8` and can be confirmed in `.meteor/versions` line starting with `lokenx:sonarrwrapper`.

They're part of Sonarr. When adding a show via the API you need to specify the quality of the show but using the correct ID number which isn't visible from the Sonarr interface. So to help people @Dahlgren added a dropdown that auto populates them. However currently it does it for any user regardless if they use Sonarr or not.

**Comment by lokenx** [comment]
Please post if there's still an issue here. I've ensured the versions for packages in the master branch is kept up to date properly going forward.
