### ISSUE TITLE
init.d script or something to make it run in the background/daemonized.

### ISSUE THREAD

**Issue by mescon** [lokenx/plexrequests-meteor#237]
So far I haven't found anything on Google, meteor --help doesn't say anything about it and the nodejs forever utility doesn't work.

It's annoying to have to dedicate a shell to this (even if it is in tmux/screen).

**Comment by duramato** [comment]
You will need to use [MeteorUp](https://github.com/arunoda/meteor-up)

**Comment by jkaberg** [comment]
Or you can use docker-compose which will isolate the app in an container aswell, simply do ```docker-compose up```, add ```-d``` for daemon mode

**Comment by lokenx** [comment]
@mescon the forever utility will work if you build the application into a node js one and then install the dependencies as usual. You'll need to install Mongodb yourself and pass env variables for it to the startup script.
