### ISSUE TITLE
"Sonarr quality profile" and "Request changing to not approved after adding"

### ISSUE THREAD

**Issue by jadsaffar** [lokenx/plexrequests-meteor#240]
after the update, i cannot select quality profile from the settings page for Sonarr.

also when the movie has been added, the requests change to not approved and not available. if i manually approve them again then both approved and available are marked with a check.

**Comment by lokenx** [comment]
Can you check the version of `lokenx:sonarrwrapper` in `.meteor/versions` file please? It should be 0.0.8.

I don't follow your second point entirely. All movies become unapproved/unavailable?

**Comment by m1e1w1** [comment]
I feel this is where i should add in what ive got.

I updated, to version 0.0.8 for sonarr, and i was able to get quality profiles to work. what i still cant get working after a few reboots is adding a tv series to sonarr from plex requests. I get a show requested, and when attempting to approve it i get an error unable to add "name of show" please try again.
I checked the logs file and there are no recorded errors for this. very similar start from the original question i think.

**Comment by lokenx** [comment]
Tracking in #244
