### ISSUE TITLE
PlexRequests and Sonarr Integration Issue

### ISSUE THREAD

**Issue by only1alive** [lokenx/plexrequests-meteor#242]
I followed the (awesome) guide for automating Plex found here: http://justanotherpsblog.com/plex-automation/, which goes over setting up CP, Sonarr, and lastly, PlexRequests. I got everything up-and-running after a few days of tinkering, and everything is looking good except for the TV Shows in PlexRequests. Movie requests from CP work correctly, but when requesting TV Shows, choosing a show and clicking "Request" just spins, showing 'Requesting..." forever. I have tried newer shows that do not have many episodes in case that was the issue. The PlexRequests logs only show: "error Error adding to Sonarr 2016/01/19 17:00:42"
The CLI of PlexRequests show:

Sonarr Series Post -> failed [400] [
   {
     "propertyName": "ProfileId",
     "errorMessage": "Profile does not exist",
     "attemptedValue": 1
   }
 ]
(STDERR) error: Error adding to Sonarr

Any help would be greatly appreciated! Please let me know any info that you may need from me.

**Comment by lokenx** [comment]
Can you ensure you're up to date? We recently changed the profileId field for Sonarr to be a dropdown that get's pulled in from your Sonarr install as it's not clear what number to use.

If you aren't getting this dropdown then you haven't updated to the latest. If you don't want to update, you need to try different numbers in that field until once matches one of your quality settings in Sonarr.

**Comment by only1alive** [comment]
I have tried to update (Windows) by following the upgrade steps in the blog: http://8bits.ca/posts/2015/installing-plex-requests-on-windows/

But, it doesn't look like it actually updates the app.


"Updating

When a new version comes out, a bug release is pushed, or you just want to update to the latest copy it’s super simple. Stop the meteor process from the command line with ctrl + c. Open up Git GUI and from the main screen you should see the repository we made earlier. If not, select Open Existing Repository and point it towards the folder where Plex Requests is installed. In the new window select the Remote menu, highlight the Fetch option and select origin. A new window should open that shows you the progress and status of any updates that have been applied, and once complete show Success. If that’s the case you’re all done, Plex Requests is now updated to the latest version!"

All of those steps checked out, but I'm still on version 1.4.2.

**Comment by lokenx** [comment]
Ugh that does happen to people and I've no idea why. What does a `git status` or `git pull` from the command prompt tell you?

Some people backup their data (`./meteor/local/db`) and re-download newest version and restore data.

**Comment by only1alive** [comment]
C:\Automation\PlexRequests>git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   packages/npm-container/.npm/package/.gitignore
        modified:   packages/npm-container/.npm/package/README
        modified:   packages/npm-container/.npm/package/npm-shrinkwrap.json

no changes added to commit (use "git add" and/or "git commit -a")

C:\Automation\PlexRequests>git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

**Comment by only1alive** [comment]
I backed up my db and installed the latest release from scratch. I am now seeing the drop-down profile list. I tested a TV series and it worked without issue.

Thanks for the help!
