### ISSUE TITLE
[REQ] Channel

### ISSUE THREAD

**Issue by Keelan** [lokenx/plexrequests-meteor#246]
Would be awesome to build a native plex channel. Since now we can share channels to all shared users. That way they can make requests within the plex clients.

--- 

Channels installed on your plex server that hooks into you plexrequest install, which you can share via plex to your shared users.channels are installed on a server level not a client level. So installed once, shared once. Channels aren't just video e.g. sick beard, couch potato, tract.tv channels are all fronts to other tools outside of plex. 

---

Example, I own a server with plex and plex requests. I install plexrequest channel on my server. I share plex request channel to my shared users. They hope on their favourite plex client and see this channel and can type shows/movies and make requests. The plexrequest grabs the logged in user adds the request to plexrequest from X user.

---

 It's just away within a plex client to request rather than using another tool e.g. browser. It's more "native" and integrated. It's all still processed via the software you built but has another way besides there browser to interface too it. Logical next step IMO.

**Comment by bobloadmire** [comment]
ay bb, this would be nice too see.

**Comment by lokenx** [comment]
Can definitely be attempted. Need the new version though as it exposes an API that can be used for this or other things, currently it's pure websocket based which isn't accessible from other apps.

**Comment by lokenx** [comment]
In case you missed it, [here you go](https://github.com/ngovil21/PlexRequestChannel.bundle)!

**Comment by Keelan** [comment]
Be nice if you guys can collab?

**Comment by Keelan** [comment]
Ah I see I was just hoping any requests would be funnelled or show up in
the Web app too that way it's all within one system. But I understand.
Either way both awesome approaches!
