### ISSUE TITLE
IMDB and TVDB Errors out the wazoo

### ISSUE THREAD

**Issue by JHeat** [lokenx/plexrequests-meteor#247]
Howdy,

First off I want to say that this app has been a lifesaver and I'm super stoked that your released it. With that said it has been working fine for a couple of months but now I'm constantly getting IMDB/TVDB errors when trying to add stuff. Not sure what changed or what happened but I've kept the config untouched. Below is the OS, Platform and the log output:

OS: Unraid
Platform: Docker

Updating repository
HEAD is now at 312c5f8 Sonarr timeout increased (#244)
Updating 312c5f8..b30b763
Fast-forward
docker-compose.yml | 1 +
1 file changed, 1 insertion(+)
Using the master branch
Your branch is up-to-date with 'origin/master'.
This project is already at Meteor 1.2.1, the latest release.

Changes to your project's package version selections from updating package
versions:

aldeed:autoform upgraded from 5.7.1 to 5.8.1
aldeed:collection2 upgraded from 2.5.0 to 2.8.0
aldeed:collection2-core added, version 1.0.0
aldeed:schema-deny added, version 1.0.1
aldeed:schema-index added, version 1.0.1
aldeed:simple-schema upgraded from 1.3.3 to 1.5.3
aslagle:reactive-table upgraded from 0.8.18 to 0.8.23
fortawesome:fontawesome upgraded from 4.4.0 to 4.5.0
mdg:validation-error added, version 0.2.0
momentjs:moment upgraded from 2.10.6 to 2.11.1
raix:eventemitter added, version 0.1.3
softwarerero:accounts-t9n upgraded from 1.1.6 to 1.1.7
useraccounts:bootstrap upgraded from 1.12.4 to 1.13.1
useraccounts:core upgraded from 1.12.4 to 1.13.1

The following top-level dependencies were not updated to the very latest
version available:
* iron:core 1.0.8 (1.0.11 is available)
* iron:router 1.0.10 (1.0.12 is available)
* twbs:bootstrap 4.0.0-alpha (4.0.0-alpha2 is available)

Newer versions of the following indirect dependencies are available:
* iron:controller 1.0.8 (1.0.12 is available)
* iron:dynamic-template 1.0.8 (1.0.12 is available)
* iron:layout 1.0.8 (1.0.12 is available)
* iron:location 1.0.9 (1.0.11 is available)
* iron:middleware-stack 1.0.10 (1.0.11 is available)
* iron:url 1.0.9 (1.0.11 is available)
* mdg:validation-error 0.2.0 (0.4.0 is available)
* softwarerero:accounts-t9n 1.1.7 (1.2.2 is available)
To update one or more of these packages, pass their names to `meteor update`.
Jan 28 19:37:09 5b4e5d996ce4 syslog-ng[82]: syslog-ng starting up; version='3.5.3'
[[[[[ /config/plexrequests-meteor ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
[34mW20160128-19:39:50.169(-7)? (STDERR) [39m[35merror: Error getting IMDB ID, none found![39m
[34mW20160128-19:39:56.494(-7)? (STDERR) [39m[35merror: Error getting IMDB ID, none found![39m

**Comment by lokenx** [comment]
What's the content you're requesting? It could be that TVDB doesn't have an IMDB available for the content.

**Comment by JHeat** [comment]
Penguins of Madagascar: Operation Vacation (2012)

Makes sense because it does in fact not show up in the TVDB. I just now realized that the search is hitting themoviedb.org to populate the search. Is there a reason why it goes there to search but then references TVDB for the ID?

**Comment by lokenx** [comment]
There's a bunch of posts regarding this buried deep somewhere. The gist is that their search API (not the search on the website) had bad results, like missing major shows. Try it on Sonarr/SickRage for `CSI` to see what I mean (assuming they haven't moved to something else).

TheMovieDB allowed us to search both with proper results, it just didn't always have the IMDB/TVDB for stuff and required multiple API calls to get this info. Next version will use the new TVDB API and either TMDB or OMDB, depending.
