### ISSUE TITLE
[Request] Admin Login sync with plex server login

### ISSUE THREAD

**Issue by loeschj** [lokenx/plexrequests-meteor#249]
Would it be possible to build it so that that same plex login that is used on the server, also is used to login to the admin section?

**Comment by lokenx** [comment]
Not in the current implementation, but that is the way we intend to go forward yes.

**Comment by alias1** [comment]
Closed by new feature?

**Comment by lokenx** [comment]
Not in this version, adding to next which is currently in different repo and on my person todo list.

**Comment by alias1** [comment]
Coolies :)
