### ISSUE TITLE
[request] SSL-Support

### ISSUE THREAD

**Issue by In0cenT** [lokenx/plexrequests-meteor#250]
The only thing I'm missing from Plexrequest ist the missing SSL support. Isnt there a way to get SSL support without using nginx?

Thanks for your work!

**Comment by lokenx** [comment]
Without nginx I'm honestly not sure, but shall look into!

**Comment by Kryptonit3** [comment]
https://github.com/arunoda/meteor-up#ssl-support

maybe that?

**Comment by In0cenT** [comment]
This is rather something for the developer than the user isnt it?

**Comment by Kryptonit3** [comment]
Yes

**Comment by lokenx** [comment]
Not sure what you mea developer vs user? It's for the person running the app? You can either put it behind nginx yourself and setup ssl, or Meteor Up makes things easier by handling all of that stuff for you (still have to supply the cert obviously).

I haven't come across anyway for Meteor itself to serve over SSL.

**Comment by dellipse** [comment]
Have you looked at this?
https://atmospherejs.com/nourharidy/ssl

**Comment by lokenx** [comment]
Interested package, fully open to PR to integrate this, however I don't have the time right now. I think it is still preferred to use a forward facing web server/proxy such as nginx for handling this, using something like Let's Encrypt for free SSL certs.
