### ISSUE TITLE
Sonarr and Couchpotato API error

### ISSUE THREAD

**Issue by seanap** [lokenx/plexrequests-meteor#251]
Just installed Sonarr and Couchpotato, and they are working just fine.  Trying to install plexrequests, stuck at "Test Sonarr Server" and "Test Couchpotato".  I checked "enable", put in localhost (and I've tried the local IP), left the port default, pasted the api key and it keeps saying "Failed"
![image](https://cloud.githubusercontent.com/assets/17012946/12730123/47a1415a-c8f8-11e5-8ee8-6976de7d9ac7.png)

I'm on a new install of Windows Server 2012R2, Installed python 2.7, Git, meteor, couchpotato, sonarr.

**Comment by lokenx** [comment]
Can you confirm there's no trailing spaces or anything like that in the API key from copying/pasting?

**Comment by seanap** [comment]
Confirmed, no trailling spaces, made sure I was using ctrl+a.  Just did a system restart, restarted meteor/plexrequests, and still isn't working.   Both couch potato and sonarr are installed in the default directories, I shouldnt have to use "Sonarr Sub-Directory" right?

**Comment by icebal** [comment]
i had to enter all the details, save the settings and then the test button would work

**Comment by lokenx** [comment]
@icebal yes it pulls from the db so you need to save before testing--annoying I know.

@seanap the sub-directory should be left alone unless you access sonarr through a sub directory when getting to the web interface.

Like `http://10.0.0.1:8888/sonarr`

**Comment by icebal** [comment]
I figured as much, just passing along the info :)
Would it be better to have the test button pop up after saving?

**Comment by lokenx** [comment]
Let me know if there's still an issue here and we'll re-open!

**Comment by tripflex** [comment]
Yeah confirmed that you have to save/update settings first otherwise this will not work ... may be best to disable the test button unless settings have been saved, had i not found this issue I would have spent a little while trying to figure out what the problem was ...
