### ISSUE TITLE
Issue when authentication is enabled

### ISSUE THREAD

**Issue by tidusjar** [lokenx/plexrequests-meteor#253]
When user authentication is enabled and a user attempts to log in, I get a HTTP 500 error in the ui and this in the console:

```
I20160203-20:47:33.324(0)? Exception while invoking method 'checkPlexUser' TypeError: Cannot read property 'length' of undefined
I20160203-20:47:33.324(0)?     at [object Object].Meteor.methods.checkPlexUser (server/methods/authentication/plexAuthentication.js:67:1)
I20160203-20:47:33.340(0)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160203-20:47:33.340(0)?     at livedata_server.js:708:19
I20160203-20:47:33.340(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160203-20:47:33.340(0)?     at livedata_server.js:706:40
I20160203-20:47:33.340(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160203-20:47:33.340(0)?     at livedata_server.js:704:46
I20160203-20:47:33.340(0)?     at tryCallTwo (C:\Users\Jamie\AppData\Local\.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:45:5)
I20160203-20:47:33.340(0)?     at doResolve (C:\Users\Jamie\AppData\Local\.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:171:13)
I20160203-20:47:33.340(0)?     at new Promise (C:\Users\Jamie\AppData\Local\.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:65:3)
```

I only want people to access this when they have access to my Plex library

**Comment by lokenx** [comment]
Did you enter your Plex server token correctly or use the form to get it ?

**Comment by tidusjar** [comment]
I tried both and I get the same error.

**Comment by lokenx** [comment]
Is your library currently shared with any users? It appears to not be retrieving any users from your server.

**Comment by tidusjar** [comment]
I have a pending user. That must be the problem. On saving this setting shouldn't there be a check for any other plex users?

**Comment by lokenx** [comment]
I don't follow, check for other users?

**Comment by tidusjar** [comment]
Ok, This is now more of a suggestion. When you are on the settings page and you enable user authentication. When pressing the save/update button, shouldn't we preform a check to see if they have any users on Plex and if they don't, don't let them enable the setting to prevent this error I was having?

**Comment by lokenx** [comment]
Ah! I was going to do a check to first see if the friends list is empty and if it is handle properly versus now just assuming there's someone on it yes.

That would mean you could enable it but then not have anyone login because it's not shared with them, but that's safer than letting anyone login when you didn't intend it.

**Comment by tidusjar** [comment]
Well I think if the friends list is empty, display a notification to the user and don't allow them to enable User Authentication until they have a user in the friends list?

**Comment by tidusjar** [comment]
The reason why I cannot log in is because I only had 1 friend on Plex. If I have 2 friends on Plex the Authentication on Plex Requests works fine.

**Comment by lokenx** [comment]
Can you post the results of the below URL with your Plex token? Make sure to remove any personal identifiable information! And that you only have 1 user shared so it errors out when trying to login.

`https://plex.tv/pms/friends/all?X-Plex-Token=abcd1234`

**Comment by tidusjar** [comment]
```
<MediaContainer friendlyName="myPlex" identifier="com.plexapp.plugins.myplex" machineIdentifier="3dd845699912j380ff0a224a0c251e1e4bc3c0d9" totalSize="1" size="1">
<User id="8113690" title="USERNAME1" username="USERNAME1" email="USERNAME1@USERNAME1.com" recommendationsPlaylistId="bc0c6754e6818b23" thumb="https://plex.tv/users/f85f928f72d21a77/avatar">
<Server id="3214946" serverId="5818242" machineIdentifier="a54d1db669799868cd704b791f331eca6648b952" name="Jamie's Microserver" lastSeenAt="1454793033" numLibraries="2" owned="1"/>
</User>
</MediaContainer>
```

**Comment by tidusjar** [comment]
@lokenx This is still an issue. I have just downloaded the latest version from Master and I am getting:

> Invalid Login. Please try again!

**Comment by lokenx** [comment]
With the single user shared to still? Hmm, I'll look at it again today for you, sorry!

**Comment by tidusjar** [comment]
Yeah! Not a problem :+1:  If I can assist please let me know.

**Comment by lokenx** [comment]
Sorry I haven't gotten back to you, been fighting with Meteor on Windows for testing to no avail :cry:

**Comment by tidusjar** [comment]
Not a problem, I am aware that you will be doing this in your spare time, it's your project :) I'm just raising some bugs :+1:

**Comment by lokenx** [comment]
Still not sure why this is broken, but since you've your own awesome .net version I'll close for now unless another user runs into it as well.

**Comment by janipewter** [comment]
This bug still exists. I have set up plexrequests and just spent 6 hours trying to figure out what was going on because with authentication turned on, it would not let me log in with my own account. I have now shared my library with someone and it works perfectly!

**Comment by rigrassm** [comment]
Pull Request #340 Fixes the issue, Checkout origin/fix-plex-auth to test.
