### ISSUE TITLE
[Request] Support for Plex Share Restrictions

### ISSUE THREAD

**Issue by some-guy-23** [lokenx/plexrequests-meteor#254]
Didn't see any issues that brought this up yet. It would be awesome if there was integration with sharing labels. I don't want to share my entire library with every user, so I have labels for each one to determine what to share.

https://support.plex.tv/hc/en-us/articles/204232573-Restricting-the-Shares

It would be nice if you could setup a label mapping in PlexRequests (e.g. userA -> labelA). Then when userA requests content, if it is already on the server, simply add "labelA" to it.

Alternatively, for now, it would also be nice to have the option to still get request notifications even when the content is in the library. This way if a user (who doesn't have the item shared with them) requests something already in the library, I'll still get notified via Pushbullet and can add the label manually.

**Comment by lokenx** [comment]
I think this may be beyond the scope of what I'd be interested i doing with the app. I don't even know where to pull that info from Plex, and we currently don't check against Plex for content but the download providers.
