### ISSUE TITLE
Error adding to SickRage in unRaid Docker

### ISSUE THREAD

**Issue by mrsdoubtfire613** [lokenx/plexrequests-meteor#256]
Hey!

My issue is the same as Issue #222:  When myself and those who use my unRAID server for Plex have been unable to request TV Shows through Sickrage/Sickbeard.  Everyone is receiving "Error adding to SickRage" when requesting a show is attempted.  I do not know when this stopped working as no one has attempted TV shows in a few weeks.

The version pulled by the docker is 1.5.3 on the Master branch.  I don't know how to check the commit version or switch to a different branch through the Docker.  Anything on my end that could be done?

Thanks for all of the hard work, I do love this program.

Cheers,
Philip

**Comment by lokenx** [comment]
What branch of SickRage are you running? We only have master right now, dev is out of date, and that's the latest from the other day so you'd be up to date.

Does the SickRage test work from the settings page?

**Comment by mrsdoubtfire613** [comment]
I have Alpha 507 of Sickbeard (another Docker).  And yes, the SickRage test is successful.

**Comment by lokenx** [comment]
Does it use the SickBeard repo/or SickRage? And there are two SickRage repo's...

The [old](https://github.com/SiCKRAGETV/SiCKRAGE) repo which is now just the original creator (who was MIA for a long time). The rest of the team have moved to their own repo [here](https://github.com/SickRage/SickRage) and is more actively developed.

The old one is having issues, not sure if he changed the API or what, but the new repo with the team is working to my knowledge.

@duramato can chime in as I believe he is part of the team.

**Comment by mrsdoubtfire613** [comment]
It uses the SickBeard repo.  I've been using it for years and just preferred to keep using it.

Did a little more testing.  Looks like PlexRequests might not be at fault. When I submit a TV Shows request, I get the following in my Sickbeard log:

`2016-02-09 12:16:36 WARNING  CP Server Thread-10 :: API :: 172.17.42.1 - SB API Disabled. ACCESS DENIED
2016-02-09 12:16:36 WARNING  CP Server Thread-9 :: API :: 172.17.42.1 - SB API Disabled. ACCESS DENIED`

I do, however, have API enabled and verified that I am giving PlexRequests the correct API key.  I also installed a second Sickbeard Docker that pulls from the Alpha Dev branch (I can't control which branch is pulled on either Dockers) and I get the same error.

So, I installed a SickRage Docker which pulled version 42.1 from the master branch and I was able to request shows with no issue.  Looks like I'll be submitting a ticket to midgetspy.  Until then, I'll leave SickRage running.

**Comment by duramato** [comment]
@mrsdoubtfire613 try checking the sickbeard config (with SB shutdown) there may have happen some issue that it didnt saved the setting 
PlexRequests should work fine with both SB and SR since they have the same api , with SR having a few more methods
And TBH you wount be disapointed with SR :P (Not a biased opinion at all xD)
