### ISSUE TITLE
Bad link when using webroot

### ISSUE THREAD

**Issue by Bybou** [lokenx/plexrequests-meteor#257]
When you use a webroot like http://XXX.XXX.XXX.XXX/requests the link "login" top of the right on the page is not good.
When you click on the url "login" top right of the page it's not the good URL. It's only http://XXX.XXX.XXX.XXX. I think it has to be http://XXX.XXX.XXX.XXX/requests

**Comment by lokenx** [comment]
Did you pass in a ROOT_URL variable on startup to let it know it's not running out of the root directory?

**Comment by Bybou** [comment]
I use plexrequests with a container. This one exactly => https://hub.docker.com/r/aptalca/docker-plexrequests/. And i use the parameter -e ROOT_URL="http://localhost/requests".
It's working fine.
Just the link "login" is not good.
