### ISSUE TITLE
Automatic update before starting

### ISSUE THREAD

**Issue by HammyHavoc** [lokenx/plexrequests-meteor#258]
How would I go about automating checking GitHub for an update then downloading it? Thinking that something along the lines of Git's bash prompt on Windows or running some form of command when Meteor is launched, but looking for the de-facto way of doing this.

**Comment by lokenx** [comment]
A `git pull` (maybe a `git fetch` first?) would do it before starting up meteor.

**Comment by lokenx** [comment]
Closing, unless you need more assistance!
