### ISSUE TITLE
Emby/LDAP Support

### ISSUE THREAD

**Issue by untotren** [lokenx/plexrequests-meteor#259]
Can you please integrate either Emby or LDAP auth :) LDAP/SSO would be best obviously :)  I love this software so much I just don't use plex anymore.  I know the Emby community would absolutely love this, even if they may not support it directly.

**Comment by lokenx** [comment]
I've been asked about Emby before, I feel like it would be best to fork and add Emby in place of the Plex parts. I don't use or intend to use Emby unfortunately so I'm not the one to do this. If someone from that community is interested get in touch and I can help fork things.

**Comment by nesrine19992** [comment]
hi 
how i can integraire ldap (active diretory) with plex media server
