### ISSUE TITLE
SickRage and CouchPotato Hostname error

### ISSUE THREAD

**Issue by thamilton91** [lokenx/plexrequests-meteor#261]
I am a bytesized-hosting user struggling to make the connection between PlexRequests and CouchPotato / SickRage.

I've tried everything from localhost, 127.0.0.1, to my server url (d57r0.bytesized-hosting.com) with all the correct port numbers and even subdirectory ("sickrage" or "couchpotato") but PlexRequests will not make the connection between them.

Any ideas?

**Comment by lokenx** [comment]
Hmm interesting. So they're all installed on the VPS/Seedbox itself?

For Couch Potato, can you go to the settings and click the docs link by the API key setting. Should take you to `/docs`.

The second paragraph should give a link to an example API call. Can you let me know what that link is, please remove your API key though as we don't want that!

**Comment by lokenx** [comment]
Please let me know if there's still an issue or what we can do to help and I'll re-open this!

**Comment by lokenx** [comment]
We need to know the response from that API call, so put the URL in the browser and let me know what's returned!

**Comment by lokenx** [comment]
OK so that shows that Couch Potato API is working. Have you entered the correct info in the admin section, **hit save**, and then hit *test*? The hitting save first is important!

Is new content not being added to Couch Potato, or is newly downloaded content (via Couch Potato) not being marked as Available.

**Comment by cpark02** [comment]
By save you mean clicking "Update Settings" correct?

And I haven't gone further than this because I was trying to figure out why
testing it brings an error.

Thanks for helping me by the way.

**Comment by lokenx** [comment]
Yes sorry update settings, and then let know response.

**Comment by rigrassm** [comment]
Yes, you need to first click "Update Settings"(after filling in the
connection information) and once those save successfully run the test.

If it connects you'll get a green bar with the success message and you're
all set.

**Comment by cpark02** [comment]
It just keeps giving me an error. I've tried a variety of different host names and ip addresses. The server port matches the one on my seedbox. API is the same and I made sure there weren't any spaces.

Where can I go to view the logs? I checked the logs on Plex Request but it doesn't show any info about my specific tests. 
I also VNCed to the server and the plex requests terminal doesn't show any errors as well.

**Comment by rigrassm** [comment]
OK, so CouchPotato is on a different server correct? And you can run the
API call using something similar to the URL below? Make sure to try running
the API call from the server where Plex requests is hosted.

    domain.com:<port>/api/.....

Try using curl from your PR server and see if you get a response back.

**Comment by cpark02** [comment]
![capture](https://cloud.githubusercontent.com/assets/17714832/21554678/6e5101a4-cdc6-11e6-8fac-53c5d1ac9234.JPG)

Something like this?

**Comment by lokenx** [comment]
Can you try that but with localhost or 127.0.0.1 assuming CP and PR are on
same server

**Comment by cpark02** [comment]
I tried it with 127.0.0.1 and it provided the exact same response

**Comment by rigrassm** [comment]
Both PR and CouchPotato are running on the same computer right?

Can you provide us with the settings that you are trying to use?

**Comment by cpark02** [comment]
Yes they are on both the same computer

I'm not sure if this is the settings your need but here are some.

![capture](https://cloud.githubusercontent.com/assets/17714832/21554946/a085e99e-cdc8-11e6-846a-f5d36d969400.JPG)
![capture1](https://cloud.githubusercontent.com/assets/17714832/21554948/a3835ec4-cdc8-11e6-8e04-a7450799fe4e.JPG)
![capture3](https://cloud.githubusercontent.com/assets/17714832/21554957/ae3c137e-cdc8-11e6-8557-941469dabc8a.JPG)

**Comment by lokenx** [comment]
In your one screenshot you seem to have CP in a sub folder, but don't have
that in your settings, try that?

**Comment by cpark02** [comment]
Oh I didn't know that. Can you tell me what I need to type into PR sub-directory text box exactly? I tried couchpotato but that didn't work.

**Comment by lokenx** [comment]
It would be /couchpotato if that's what you use in browser, the helper text
should say if you need or don't need any slashes.

**Comment by cpark02** [comment]
So I tried /couchpotato, couchpotato, and /couchpotato/ but all dont seem to work :(

**Comment by cpark02** [comment]
So I got sickrage to work with me

![capture](https://cloud.githubusercontent.com/assets/17714832/21557479/8f598dec-cde1-11e6-98b8-910f3a928a70.JPG)


I tried changing the host name to the same for couchpotato but still getting the error :\

**Comment by lokenx** [comment]
Hmm that's odd that one works. And you've saved before testing? No stray spaces, right port number, API with no spaces, `/couchpotato`, is app up to date? SSL?

**Comment by cpark02** [comment]
Yeah to everything...

One weird thing is that when I type in "(IP Address):10435" isn't it supposed to show my sickrage page? All that shows is

![screen shot 2016-12-29 at 6 27 42 pm](https://cloud.githubusercontent.com/assets/17714832/21558792/88a54564-cdf4-11e6-972b-4b83e61ed9b6.png)


"(IP Address):19815" goes to my coachpotato

Not sure if this matters or not haha

**Comment by lokenx** [comment]
Yeah that’s really weird…is sick rage at `/sickrage` ? But you can navigate to couch potato without `/couchpotato`?

Something doesn’t add up then!

**Comment by cpark02** [comment]
I can only reach sickrage at "(username).juno.bysh.me/sickrage"

But for coachpotato I can reach it at "(IP Address:19815)" or "(username).juno.bysh.me/couchpotato"

**Comment by cpark02** [comment]
So I reinstalled couchpotato from fresh and for some reason it's working now.

I can't tell if it was a bad port or if it was API key.

I'm sorry if this was such a simple solution and to have wasted your time. Thank you for all your help, really.

**Comment by lokenx** [comment]
No worries, glad got it working!
