### ISSUE TITLE
Add support for other sources (eg. OMDb)

### ISSUE THREAD

**Issue by alias1** [lokenx/plexrequests-meteor#263]
It would be cool to be able to check other sources such as IMDB or [OMDb](http://www.omdbapi.com/), as I've found (generally with anime) themoviedb to not always have everything.

Being able to directly input the IMDB ID would be useful too.

Looking at the [TMDB API](http://docs.themoviedb.apiary.io/#reference/tv/tvidexternalids) and [the source](https://github.com/lokenx/plexrequests-meteor/blob/master/server/methods/search/requestTV.js#L18) it's looks like it shouldn't be hard to search by IMDB id?

**Comment by lokenx** [comment]
Well IMDB can't technically be checked as they don't provide a public API to my knowledge. The OMDB is cool and I'm looking to use it in a different version, but I won't be adding it to this version of Plex Requests, sorry.

**Comment by alias1** [comment]
How about the last part with the tmdb search API you're currently using, looks like it has support to search by IMDB id?

Sent from Outlook Mobile




On Wed, Feb 17, 2016 at 5:17 PM -0800, "loken" <notifications@github.com> wrote:












Well IMDB can't technically be checked as they don't provide a public API to my knowledge. The OMDB is cool and I'm looking to use it in a different version, but I won't be adding it to this version of Plex Requests, sorry.
