### ISSUE TITLE
Cannot approve TV Show

### ISSUE THREAD

**Issue by tidusjar** [lokenx/plexrequests-meteor#264]
I am unable to approve the TV show Fringe.

Error:
> Sonarr Series Post -> Match error: Expected number, got undefined

Repro:

- Request the TV Show Fringe (All Episodes).
- On the Requests, Approve the TV Show Fringe
- Error in the UI: Unable to approve Fringe, please try again!

**Comment by lokenx** [comment]
Can you delete the request and re-add? It seems to be having issues getting a valid TVDB ID number for some reason.

**Comment by tidusjar** [comment]
Nope I deleted and re-added a few times and it's still an issue.

**Comment by lokenx** [comment]
You're install/setup is just having no luck! There's been a little code cleanup past couple days, can you make sure you up date? I'm going to check in on that auth issue for you too!

**Comment by geekcroft** [comment]
I'm having the issue with the TV show "Spooks"

**Comment by lokenx** [comment]
@geekcroft are any shows going through?

**Comment by geekcroft** [comment]
Tried a couple more, and no.

If I disable approvals, they fail upon request. If I enable approvals they fail upon me approving.

**Comment by lokenx** [comment]
It's having issues talking to TheMovieDB API then. Does the console log or log page on admin side say anything?

**Comment by geekcroft** [comment]
Nope, just the "Sonarr Series Post -> Match error: Expected number, got undefined" error

**Comment by lokenx** [comment]
Can you try the below URL from the machine running Plex Requests? Just want to make sure you can hit their servers. It should complain about no API key provided.

http://api.themoviedb.org/3/configuration

**Comment by geekcroft** [comment]
Yeah, I get "Invalid API Key: You must be granted a valid key" from Firefox running on the box

**Comment by lokenx** [comment]
Can you update to 1.7.2, changed a bit of logic in the TMDB package, see if it helps/errors out with more useful information.

**Comment by geekcroft** [comment]
@lokenx did a "git pull" to update (I presume that is correct) and tried to re-approve a TV series - but still not working

" I20160302-11:24:37.656(1)? Sonarr Series Post -> Match error: Expected number, got undefined"

Is the error logged

**Comment by geekcroft** [comment]
Oddly, if I add the series to Sonarr and then go to approve it then approves?

**Comment by lokenx** [comment]
Hmm that's interesting, that means it's gotten the TVDB ID as that's what it checks against Sonarr. Do you have all the fields filled out under the Sonarr settings? Including quality profiles?

The only optional ones are the sub-directory and SSL.

**Comment by geekcroft** [comment]
Aha!

So, when initially setting up the Profile's option was blank (with no dropdown options) - however now I have gone back in and there are some available profiles to pick. I have chosen my usual (HD-720p) and I seem to be able to accept new shows. 

Thanks for all your help!

**Comment by lokenx** [comment]
Ah OK that makes more sense!

**Comment by geekcroft** [comment]
Just out of curiosity (I hope this doesn't re-open it) but I wonder whether that part of the UI needs a little tweak - as I said it let me setup and test Sonarr without prompting to fill out the Quality and then "defaulted" to "ALL" - but didn't seem to actually be honouring the default it had set?
