### ISSUE TITLE
SickRage issue

### ISSUE THREAD

**Issue by emerycough** [lokenx/plexrequests-meteor#266]
When I try to request a show, it errors trying to add to sick rage with

STDERR: error: Error adding to sickrage

I have tried all the suggestions I have found on here, such as enabling SSL (This broke it further)
I have also used the repo that someone provided in another issue 

It works on the test function in the admin section

I'm at a loss on how to get it to work

Any ideas?

Regards

**Comment by lokenx** [comment]
There are no other errors in the logs or in sickrage?

What branch of sickrage are you on? The old branch is known not to work, not exactly sure what the guy did when the team migrated to new branch. New branch is [here](https://github.com/SickRage/SickRage).

**Comment by emerycough** [comment]
Using the branch that you linked

Can't see any errors on sickrage, sickrage works when I request shows on it perfectly

**Comment by lokenx** [comment]
Good!

**Comment by emerycough** [comment]
Sorry, maybe I worded that wrong
Plex requests still errors
If i go to sickrage directly, it works fine

**Comment by lokenx** [comment]
Oh my bad! So you've moved to the new branch? Can restart both apps, delete old request, and try it again? And let me know what's in both app logs?

**Comment by emerycough** [comment]
Hi
That is correct

I can't seem to locate log files from sickrage
Although plex requests in the log has a timestamp and says "error adding to sickrage"

**Comment by lokenx** [comment]
That's all? What version you running? Are you looking at logs from command prompt or log page under admin section.

Sickrage locks are found under one of the icons in top right, believe it's one next to the settings one.

**Comment by emerycough** [comment]
It says version 1.6.0 (PlexRequests)
All it says in the log is 
error 	Error adding to SickRage	 2016/02/18 20:17:07
That is both on the webpage and under admin/logs

As I went  to log into Sickrage to check the logs, it said There is a newer version available (you're 3 commits behind)— Update Now

As I updated, and tried again, it worked fine.

Weird.


Thanks for your help

Regards
