### ISSUE TITLE
Running behind an Nginx Reverse Proxy

### ISSUE THREAD

**Issue by Jovetic** [lokenx/plexrequests-meteor#269]
Hi!  Thanks for this program, it is awesome. I want to get it working perfectly behind an Nginx install, I managed to get it working but it does take a performance hit. In order to get it working I set a root url that I can forward to. This causes some issue when clicking links, it can take up to 15 seconds for the page to load. Any ideas how I can sort this please? We see some 404's below, which I assume are hardcoded to / instead of /plexrequests

C:\Sites\plexrequests>Set ROOT_URL=http://localhost:3000/plexrequests

C:\Sites\plexrequests>meteor
[[[[[ C:\Sites\plexrequests ]]]]]

=> Started proxy.
=> Started MongoDB.
npm-container: updating npm dependencies -- winston...
=> Started your app.

=> App running at: http://localhost:3000/plexrequests
Type Control-C twice to stop.

W20160217-19:40:24.923(0)? (STDERR) error: Adding default settings
I20160217-19:41:13.999(0)? Sonarr Profiles Get -> ESOCKETTIMEDOUT
I20160217-19:42:04.226(0)? Sonarr Profiles Get -> ESOCKETTIMEDOUT
I20160217-19:42:19.810(0)? Sonarr Profiles Get -> ESOCKETTIMEDOUT
I20160217-19:43:12.343(0)? Sonarr Profiles Get -> ESOCKETTIMEDOUT
I20160217-19:43:34.915(0)? Sonarr Profiles Get -> ESOCKETTIMEDOUT
I20160217-19:47:16.643(0)? { [Error: ESOCKETTIMEDOUT] stack: [Getter] }
I20160217-19:47:35.259(0)? { [Error: ESOCKETTIMEDOUT] stack: [Getter] }
I20160217-19:47:54.539(0)? { [Error: ESOCKETTIMEDOUT] stack: [Getter] }
I20160217-19:48:08.269(0)? { [Error: ESOCKETTIMEDOUT] stack: [Getter] }
I20160217-19:48:22.626(0)? { [Error: ESOCKETTIMEDOUT] stack: [Getter] }
I20160217-19:48:53.463(0)? { [Error: failed [404] <html>
I20160217-19:48:53.463(0)? <head><title>404 Not Found</title></head>
I20160217-19:48:53.463(0)? <body bgcolor="white">
I20160217-19:48:53.463(0)? <center><h1>404 Not Found</h1></center>
I20160217-19:48:53.463(0)? <hr><center>nginx/1.9.11</center>
I20160217-19:48:53.463(0)? </body>
I20160217-19:48:53.463(0)? </html>
I20160217-19:48:53.463(0)? ] stack: [Getter] }
I20160217-19:48:54.350(0)? { [Error: failed [404] <html>
I20160217-19:48:54.351(0)? <head><title>404 Not Found</title></head>
I20160217-19:48:54.351(0)? <body bgcolor="white">
I20160217-19:48:54.351(0)? <center><h1>404 Not Found</h1></center>
I20160217-19:48:54.351(0)? <hr><center>nginx/1.9.11</center>
I20160217-19:48:54.351(0)? </body>
I20160217-19:48:54.352(0)? </html>
I20160217-19:48:54.352(0)? ] stack: [Getter] }
I20160217-19:48:54.428(0)? { [Error: failed [404] <html>
I20160217-19:48:54.429(0)? <head><title>404 Not Found</title></head>
I20160217-19:48:54.429(0)? <body bgcolor="white">
I20160217-19:48:54.429(0)? <center><h1>404 Not Found</h1></center>
I20160217-19:48:54.429(0)? <hr><center>nginx/1.9.11</center>
I20160217-19:48:54.429(0)? </body>
I20160217-19:48:54.430(0)? </html>
I20160217-19:48:54.430(0)? ] stack: [Getter] }
I20160217-19:49:07.165(0)? { [Error: ESOCKETTIMEDOUT] stack: [Getter] }
I20160217-19:54:50.863(0)? { [Error: ESOCKETTIMEDOUT] stack: [Getter] }

**Comment by lokenx** [comment]
What's your nginx config look like? The Sonarr profile things are expected if you don't have Sonarr configured. Need to upgrade things to only check that if it's enabled.

**Comment by Jovetic** [comment]
Thank for getting back to me.

`
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
		listen       80;
        listen       443 ssl;
        server_name  domain.co.uk, 192.168.0.203;


        ssl_certificate      domain.crt;
        ssl_certificate_key  domain.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;
		

        charset koi8-r;

        #access_log  logs/host.access.log  main;

location /sonarr {
		proxy_pass http://127.0.0.1:38082;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /couchpotato {
        proxy_pass        http://127.0.0.1:38083/couchpotato;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /deluge {
        proxy_pass        http://127.0.0.1:38081/;
        proxy_set_header  X-Deluge-Base "/deluge/";
        proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /sabnzbd {
		proxy_pass http://127.0.0.1:38080;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}

location /headphones {
		proxy_pass http://127.0.0.1:38084;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}

location /plexpy {
		proxy_pass http://192.168.0.203:1818;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}

location /plexrequests {
		proxy_pass http://localhost:3000;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}

location /web {
		proxy_pass https://192.168.0.1:32400;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


 }
`

**Comment by lokenx** [comment]
You need to use triple \``` (back-ticks) for code blocks, or everything indented by 4 spaces (which is annoying).

It seems OK but I'm not sure if you're suppose to pass to `/plexrequests` or not. I'll need to setup some test VM's to check. But try adding that to the nginx config and see what it does.

**Comment by Jovetic** [comment]
Thanks for getting back to me.  I'm not sure what you want me to add, /plexrequests is already in the config.

**Comment by lokenx** [comment]
The proxy_pass variable in nginx for Plex Requests

**Comment by mescon** [comment]
I already have this working. You just need to do:
``proxy_pass http://localhost:3000/plexrequests`` or whatever you set as ``ROOT_URL``.

Assuming of course both Nginx and PlexRequest is running on the same machine.

**Comment by lokenx** [comment]
Yeah that's what I assumed too, thanks @mescon. Hopefully @Jovetic can test and let us know!

**Comment by Jovetic** [comment]
Thanks all. I will test as soon as i get home. Appreciated.

**Comment by Jovetic** [comment]
Thanks all, I had a similar issue with PlexPy which I sorted and used the same config on this which worked. _Host

location /plexrequests {
    proxy_set_header Host** $http_host;**
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://127.0.0.1:3000;

**Comment by lokenx** [comment]
Glad it's working, closing ticket then!
