### ISSUE TITLE
Move url configuration for notifications to settings 

### ISSUE THREAD

**Issue by leonkunert** [lokenx/plexrequests-meteor#270]
Move the configuration for the notification providers pushbullet and pushover to the settings. Problem is that the settings default values are written to the database at initial startup.

**Comment by rigrassm** [comment]
@lokenx care to expand on this? Thought this was how it works?

**Comment by lokenx** [comment]
See PR #268 . I think with the schema/migrations that we've since added, the change can be made as @leonkunert originally wanted as it should update the DB of existing users according with default values.

**Comment by rigrassm** [comment]
Ahh ok, this can be closed out then.
