### ISSUE TITLE
Update Releases Page

### ISSUE THREAD

**Issue by lokenx** [lokenx/plexrequests-meteor#272]
Have been neglecting the release page because I forgot about it, needs to be updated and a method of keeping up to date figured out.

**Comment by Arcanemagus** [comment]
Tagging old releases can be done with a script like [this](https://gist.github.com/Arcanemagus/6aa80a3cb63b1e188e91).

Just checkout the specific commit, and feed that script a version number (`vX.Y.Z`) and it will create a tag that has the proper time stamp (the hard part).

**Comment by lokenx** [comment]
Tag releases are part of Git? Huh had no idea! I'll try with the next bump, thanks!

**Comment by Arcanemagus** [comment]
Note that when pushing them back up you should use `git push --follow-tags`, a normal `git push` doesn't push tags to the remote.

**Comment by lokenx** [comment]
Thanks, noted!

**Comment by lokenx** [comment]
And thanks for the Plex API docs, didn't realize it was you!

**Comment by Arcanemagus** [comment]
I just cloned them off Google Code before they were lost forever :stuck_out_tongue:.
