### ISSUE TITLE
Please delete your misleading post from Emby Community

### ISSUE THREAD

**Issue by untotren** [lokenx/plexrequests-meteor#273]
Please remove your post from Emby Community it can be found here:
http://emby.media/community/index.php?/topic/24527-emby-verison-of-plex-requests/

You made very clear indications that Emby would be an absolute possibility then go ahead to even ask users what features they would like.  Then I come to github just to request the exact functionality that YOU mentioned and you said you wouldn't do it.

Don't even bother coming to a community if you're just going to talk shit. Nobody likes the music man.  Delete your post now.

**Comment by icebal** [comment]
> I've been asked about Emby before, I feel like it would be best to fork and add Emby in place of the Plex parts. I don't use or intend to use Emby unfortunately so I'm not the one to do this. If someone from that community is interested get in touch and I can help fork things.

that sounds awfully like hes saying he is more than glad to help get things going. as per the post you referenced, an Emby user was asking about it, and one of the devs said if you have questions, to ask and he could help answer them. in no way did he say there was a possibility to add it to **PLEX**request. Another thing, the other Emby users shot the idea down, as it "aids to piracy". a fork would be a must.

**Comment by lokenx** [comment]
My comment on Emby:

> Hey all, dev of Plex Requests here!
 
> Some quick questions, what is Emby? It seems to be similar to Plex, or am I missing something? What is it that you want Plex (neh Emby) Requests to do exactly?
 
> Regarding the legal nature of Plex Requests, if you want to be technical, it doesn't do anything illegal. It merely acts as the middle man. The various download providers that it ties into are doing the illegal stuff so to speak. If you don't enable/setup integration to those services, it's merely a request list that you can provide to users. The manner of obtaining the media is entirely up to you, and used in this capacity is entirely legal (assuming the obtainment of the media is legal).
 
> I'm currently working on re-writing large parts of the application, which in turn would make it much easier to simply use as a request site you can self host that users can send requests in and you can manage them as you please.
 
> If you've any questions please let me know, or open up an issue over on GitHub!

No where in that comment did I say or make very clear indications that Emby would be an absolute possibility. I put forth an interest and a request for information and insight. Those are two entirely different things. Based on the minimal feedback provided it didn't seem a road worthy to go down.

Then, when an issue opened up I responded with the above quote after looking things through and comparing to the free time I have for OSS. Again no promises or explicit mentions that I would do anything regarding Emby. Merely that I am open and willing to work with and assistance someone who is interested in pursuing this ideal, however personally it's a road I a not interested going down, as mentioned already.

I'm sorry, but no shit was talked, and no posts should be deleted, I stand behind them. The fact that this is an issue makes me sad honestly :disappointed:
