### ISSUE TITLE
No more releasing ?

### ISSUE THREAD

**Issue by JigSawFr** [lokenx/plexrequests-meteor#274]
Hi, i've just see that there is no more release done on your repo.
Problem is that some docker images use releases to update to latest version
Ex: https://github.com/linuxserver/docker-plexrequests
Can you update releases page on your side @lokenx ?
Thanks you so much !

**Comment by icebal** [comment]
lokenx has a issue for this at  #272

**Comment by lokenx** [comment]
Yeah sorry about that, it just slipped my mind and got way behind! I've an issue open and will create a new release for the current one, I'll try and see if I can do old ones.

Sorry!
