### ISSUE TITLE
Set an item as available from Plex Library integration and admin page

### ISSUE THREAD

**Issue by lukezona** [lokenx/plexrequests-meteor#276]
Hi, I'm using Plex Requests from a few days and I don't use Sonarr, CouchPotato or anything else because I'm from Italy and I need italian audio and I can't find it easily with these programs.

But I was wondering if there's a way to integrate it with PlexPy (it notify each movie/episode added) or the Plex Library (maybe with a token?) and let it check if the movie/episode is available on the PMS..

If that's impossible (or too difficult) at least I'd like to have the possibility to set as "Available" a movie/episode that I have manually downloaded.

If it's already possible excuse me but I didn't find it in the wiki.

Thanks a lot

**Comment by lokenx** [comment]
The goal is to look directly to Plex, dealing with a few issues that could arise, but I'm looking to get this out the door ASAP.

**Comment by lokenx** [comment]
You can now mark movies manually as available, and I've started work on a branch that looks to Plex for status.
