### ISSUE TITLE
Running on RPi

### ISSUE THREAD

**Issue by manderso7** [lokenx/plexrequests-meteor#277]
I got this running on a raspberry pi, minibian jessie. Had to do the following
Clone `https://github.com/4commerce-technologies-AG/meteor.git`
set a symlink to meteor/meteor to /usr/local/bin/meteor
installing meteor required adding a -k to the curl lines in the meteor/meteor script to bypass ssl issues
Also, plexrequests relies on SASS, so clone `https://github.com/fourseven/meteor-scss.git` to plexrequests\packages\scss, make sure everything is owned as the correct user. Running meteor in the plexrequests directory takes a while but the end result is pretty cool. Thanks for the work!

**Comment by lokenx** [comment]
Probably best written up and added to the wiki for others? 

https://github.com/lokenx/plexrequests-meteor/wiki/Installation

**Comment by manderso7** [comment]
Cheers, done.
