### ISSUE TITLE
Can't login as admin outside localhost

### ISSUE THREAD

**Issue by lukezona** [lokenx/plexrequests-meteor#285]
Hi, 

I'm trying to log in as an admin from the external IP (accessing it through an Apache server that connect "request.mydomain.it" to localhost:3000) but it blocks the form and in the console it start showing:

`I20160229-14:23:08.039(1)? Sonarr Profiles Get -> ESOCKETTIMEDOUT`
`I20160229-14:23:13.504(1)? Sonarr Profiles Get -> ETIMEDOUT`
`I20160229-14:23:18.880(1)? Sonarr Profiles Get -> ESOCKETTIMEDOUT`
`I20160229-14:23:26.353(1)? Sonarr Profiles Get -> ETIMEDOUT`
`I20160229-14:23:44.713(1)? Sonarr Profiles Get -> ESOCKETTIMEDOUT`
`I20160229-14:24:21.651(1)? Sonarr Profiles Get -> ETIMEDOUT`
`I20160229-14:24:34.347(1)? Sonarr Profiles Get -> ESOCKETTIMEDOUT`
`I20160229-14:24:46.345(1)? Sonarr Profiles Get -> ETIMEDOUT`
`I20160229-14:25:03.608(1)? Sonarr Profiles Get -> ETIMEDOUT`
`I20160229-14:25:15.561(1)? Sonarr Profiles Get -> ETIMEDOUT`
`I20160229-14:25:45.375(1)? Sonarr Profiles Get -> ETIMEDOUT`
`I20160229-14:26:02.835(1)? Sonarr Profiles Get -> ETIMEDOUT`

I can log in as an user and make requests, it's only an admin page problem.

I haven't configured Sonarr, CouchPotato and SickRage

Even if I try from a browser on the server (I'm connected with RDP to my Windows server and I have an Ubuntu VM where everything run, I made a port forwarding so I can access on localhost:3000 the Meteor app) on localhost:3000 it works, but it doesn't if I try through the subdomain.

It looks like a Sonarr problem that occurs only when I try to log in using an Apache server to have a domain connected (request.mydomain.it)

I have to do something or is a meteor related problem that you can fix?

I hope to have explained my issue correctly.

**Comment by lokenx** [comment]
The Sonarr error you are seeing is because that method is called regardless if Sonarr is setup or not, so in your case it would error out as you haven't configured it yet. It's entirely unrelated, and will be fixed going forward.

Have you ever been able to login to the admin form? Keeping in mind the admin login and your Plex login for requests are not the same or tied together.

**Comment by lukezona** [comment]
I can login to the admin form on localhost:3000 (from a browser on the server where I have meteor running), but when I try to do it through a domain (request.mydomain.it) it stop working correctly, the button goes gray and I can't click anywhere.

I access plexrequests from the outside using an Apache server that link my domain to localhost:3000 (where I can login as an admin without problems, it doesn't load all the requests in the Request page but I think is an RDP problem)..

**Comment by rigrassm** [comment]
Make sure your proxy pass settings in Apache are set correctly. It may be an issue with the app not getting the correct session info from the browser.

Don't get me wrong, I love Apache and it works great but it's honestly a bit overkill for running a reverse proxy for a web app with such low traffic. I switched to Nginx a few months back and it is much more responsive and much less resource hungry than Apache is.

Just a suggestion though, they both work great.

**Comment by lokenx** [comment]
Closing, but if need more help/still an issue let me know and can re-open.
