### ISSUE TITLE
Broke my Plex Request :Issue :Help

### ISSUE THREAD

**Issue by rickcab1** [lokenx/plexrequests-meteor#287]
So somewhere along the line I think I broke my Plex Requests.  I thought I would wait till the Python version come out but the constant emails now from friends is killing me!  So I tried to uninstall everything and reinstall again but it looks like i am having same issues.  Here is what i get when trying to reinstall and launching the app:

![image](https://cloud.githubusercontent.com/assets/14242464/13414984/e02ee106-df0b-11e5-8cad-00fff2341b97.png)

**Comment by lokenx** [comment]
I think you need to re-install Meteor or the Fourseven package. I believe it's saved in your `AppData/Local/.meteor/packages` folder.

**Comment by lokenx** [comment]
Let me know if assistance is still needed with this, and we can re-open.
