### ISSUE TITLE
(STDERR) error: Error getting TVDB ID, none found!

### ISSUE THREAD

**Issue by ohy3a** [lokenx/plexrequests-meteor#291]
Hi Folks,

Was able to serve TV search requests last night but now, for no reason I can see it's just throwing the above error no matter what I try to add.

For example, I add "Cops", it will show the results.  When I click request I get the red banner at the bottom asking me to try again later.

I built a new VM thinking it was that but the same error followed me.  Couchpotato search requests are fine.  

I don't use Sonar, so can't confirm whether it's working.

I'm new at posting faults, if you need logs etc please let me know what ones.

**Comment by ohy3a** [comment]
FYI. I've tried multiple shows I know exist in the TVDB.

**Comment by skalvaro** [comment]
Branch: master
Version: 1.7.2
I get the same on various shows.

**Comment by ohy3a** [comment]
Forgot to include that:

Branch: master
Version: 1.7.2

**Comment by skalvaro** [comment]
@lokenx Thanks, confirmed to be working.
