### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#296]
Current install Apple TV and XBOX are not displaying there icon I checked the page source and the image HTML is missing, ROKU and others are listed.

**Comment by lokenx** [comment]
Sorry I need a bit more info: what icons precisely? Are you browsing the page from an Apple TV/XBox? But it works on a Roku, which I don't think has a web browser.

**Comment by unixjeff** [comment]
On the now playing bar on the main or index page

**Comment by rigrassm** [comment]
Are you sure this is plex requests you're having issues with or is it the actual Plex app?

**Comment by lokenx** [comment]
Or maybe PlexPy @unixjeff ?

Closing, re-open if it's related to Plex Requests

**Comment by unixjeff** [comment]
![plexwatch](https://cloud.githubusercontent.com/assets/751756/13906882/dad1f174-eeb7-11e5-8c45-b506198a4bc8.png)

looks to be a plex request issue, the icons appear to be missing

**Comment by lokenx** [comment]
That appears to be [PlexPy](https://github.com/drzoidberg33/plexpy), give the guys over there a shout for help!
