### ISSUE TITLE
[Question]What are the core features?

### ISSUE THREAD

**Issue by jrudio** [lokenx/plexrequests-meteor#297]
Hi!

I'm planning on making a Go port, and I was wondering if the features listed in the readme are considered "core features"? Is there any not listed there? I would like to keep the features on par with this repo.

Thanks!

**Comment by lokenx** [comment]
- Look to using TV Maze or TVDB for TV searches over The Movie DB
- Look into making issues more usable
- Move to checking against PMS instead of download providers for availability (planning on adding this, just need to update third party package)

**Comment by jrudio** [comment]
Thanks for quick response!

:grinning:
