### ISSUE TITLE
[Request] Being able to limit search result to blu-ray released movies only

### ISSUE THREAD

**Issue by zin105** [lokenx/plexrequests-meteor#300]
Would be nice if I can limit to search results, and therefor requests, to movies released on blu-ray or other home "medias". Kinda sucks when people request movies that are still only available at the cinema.

**Comment by unixjeff** [comment]
The more relises on you setting in couchhpotato. You can limit what is download in couchpotato, and it will just sit there until the street date not grabbing "cams,TS,TC or others

**Comment by zin105** [comment]
While that is true, I'm not using CouchPotato with PlexRequests. I'm using it to see what people want and then manually getting it. I'm looking to not even being able to request unreleased content. Maybe instead of a request button it would countdown until Blu-ray release date or show status on the "scene".

**Comment by lokenx** [comment]
Interesting ID, however I'm not sure if the data returned from the API provides this info on that request. That may require an individual request for each movie to get more detailed information which would get excessive and slow things down.

We're switching to the TV Maze API which @rigrassm is more familiar with, so maybe he can chime in when he get's a chance!

**Comment by jrdnlc** [comment]
@lokenx When is the next update and what features are coming? It's been a while.

**Comment by lokenx** [comment]
I'm hoping to add the plex integration for availability once my pull request gets merged into a different package. I'm also going to be merging a big PR soon to add some new things in.

I know updates have been slow, I've simply been short on time lately--and most of it was spent on complete re-writes (Python, Node). The python one is slowly coming along, but most of the work is done by @rigrassm.

**Comment by rigrassm** [comment]
Yeah, for TV shows that's not going to be something that will be very feasible. I'm sure it's possible but the amount of code, logic and third party lookups required just don't seem to be beneficial enough to justify it. For that it's as simple as googling the request and to see if it's been released but to have that built it would mean hooking into new resources and then applying filters to every search item. That would dramatically reduce the responsiveness of search results and increase resource usage unnecessarily.

**Comment by rigrassm** [comment]
Since this doesn't really fit within the scope of this project I'm going to close this issue.
