### ISSUE TITLE
Cleanup from #293

### ISSUE THREAD

**Issue by lokenx** [lokenx/plexrequests-meteor#301]
- [x] Update README regarding search changes
- [x] Update README regarding custom notifications
- [x] Update changelog

**Comment by rigrassm** [comment]
I'll right there custom notifications section tonight. As for the new search changes, I'll go ahead and write the readme section for that two but I'm going to open an issue for the missing TVDB id's.I noticed that if I manually query the API it is actually returning an ID in the response so I'm thinking it's something in my code that's not grabbing it for some reason.

**Comment by rigrassm** [comment]
Write**

**Comment by lokenx** [comment]
You can edit your comments :)

**Comment by rigrassm** [comment]
I was on mobile and was too lazy to switch to desktop mode lol.

**Comment by rigrassm** [comment]
See Pull request #322 for README Updates
