### ISSUE TITLE
Automatically Approved

### ISSUE THREAD

**Issue by damiantje99** [lokenx/plexrequests-meteor#303]
Hi,

When someone requests a movie or show. It automatically approves the requested media. But the option "Require approval of requests" is enabled. Is Plex authentication required to be able to approve requested by hand?

Hope to hear from you,

Damian

**Comment by lokenx** [comment]
Huh, not 100% sure but I believe it may be. I'll get back once checked code!

**Comment by damiantje99** [comment]
Currently i'm on v1.8.3. I've enabled Couchpotato and Sonarr. I recently reinstalled it again, so it didn't happend before.
