### ISSUE TITLE
Unable to use Plexrequests behind reverse proxy

### ISSUE THREAD

**Issue by TheVMaster** [lokenx/plexrequests-meteor#304]
I'm unable to use Plexrequests behind a reverse proxy (Apache). All my other services (Sickrage / NZBGet / Couchpotato) do work, but Plexrequests won't..I only see a blank page (with plexrequests code in hit in the source of the page)...any idea how to fix it?

**Comment by rigrassm** [comment]
Tried clearing the browser's cache or tried a different browser all together? I have mine running behind Nginx and it's working as expected.

**Comment by lokenx** [comment]
Are you running from a subdomain, root, or sub directory? Did you pass the `ROOT_URL` variable through on startup?

**Comment by TheVMaster** [comment]
I'm running it from a subdirectory. I don't think i passed the ROOT_URL variable through...eh....where can I do that?

**Comment by TheVMaster** [comment]
I have it working....just configured a subdomain. Not entirely what I was looking for, but that works (i found it after searching on ROOT_URL and plexrequests on Google).....

**Comment by lokenx** [comment]
Search the issues, I believe believe have got it up and running!
