### ISSUE TITLE
Bug? "match error Expected number, got object"

### ISSUE THREAD

**Issue by whitecollar17** [lokenx/plexrequests-meteor#307]
When i try to add a serie, i got the error: match error Expected number, got object

In plex requests i got the error: "Couldn't submit request, please try again!"

Got it with this shows:
The Story of God
BrainDead (2016)

![image](https://cloud.githubusercontent.com/assets/2944704/14089626/1b2f8996-f536-11e5-98af-d96ed0aed03c.png)

**Comment by rigrassm** [comment]
Latest commits fix this issue. Was having problems with the new TVMaze implementation that are now resolved.
