### ISSUE TITLE
Iron:router error on Iphones?

### ISSUE THREAD

**Issue by streat90** [lokenx/plexrequests-meteor#308]
I am not sure if this is an error with Plex Requests or my apache/mod_cache settings but I am getting this error on my iphone. No difficulty accessing the page from a desktop or android. Any thoughts?
Thank you!

<img width="321" alt="screen shot 2016-03-29 at 10 25 01 am" src="https://cloud.githubusercontent.com/assets/5766531/14111413/9f6a8a50-f598-11e5-8735-4ac3ce97aa82.png">

**Comment by lokenx** [comment]
Are you using a sub domain or sub directory? I've seen this happen when routes don't get handled/rewritten properly.

**Comment by streat90** [comment]
I gave it it's own domain name, I figured it was probably my fault! I have attached my apache config for this particular domain below.
Thank you
[ApacheConfig.txt](https://github.com/lokenx/plexrequests-meteor/files/194117/ApacheConfig.txt)
!

**Comment by lokenx** [comment]
I'm not an Apache user but what is this line for

```
        RewriteRule ^/?(.*) https://READACTED/search/$1 [R=301,L]
```

**Comment by rigrassm** [comment]
Pretty sure that line takes everything after the / and adds /search before it. That's likely the culprit here

**Comment by rigrassm** [comment]
@streat90 any update on this?

**Comment by rigrassm** [comment]
Been a month since last contact. Issue was likely due to faulty HTTP server config. Gonna close for now, @streat90 comment here if the issue persists and I will reopen it.
