### ISSUE TITLE
Cover-art not appearing for TV Show requests

### ISSUE THREAD

**Issue by alternativesurfer** [lokenx/plexrequests-meteor#311]
Just updated to the most recent version of PlexRequests.
TV requests are no longer showing the poster, however Movie request posters still display correctly.

![untitled](https://cloud.githubusercontent.com/assets/10135929/14185919/c0897d88-f730-11e5-9d88-36d1fd72c498.png)

**Comment by rigrassm** [comment]
Can you get the URL of one of those broken poster links and post it here? Just right click it and copy the image address

**Comment by alternativesurfer** [comment]
MYIPADDRESS:3000/vYvOeb9T2ubewx2aOCR1wWMblM4.jpg

**Comment by lokenx** [comment]
@rigrassm TV Maze requests have the full URL saved to the DB, TVDB ones only have the path (as I was merely passing the info through not manipulating it). They should have had the full path but I created it without the thought of it being changed.

@alternativesurfer if you make a new request for a TV show it should show the poster correct?

**Comment by rigrassm** [comment]
I submitted pull request #312  that fixes the issue by updating the old TV poster_paths to be full URL's so that they will display correctly..

**Comment by alternativesurfer** [comment]
@lokenx Yes, requesting new shows displays the correct poster.
