### ISSUE TITLE
TV search throws error

### ISSUE THREAD

**Issue by notinhell** [lokenx/plexrequests-meteor#313]
I've updated to 1.8.5 and then 1.8.6 and when I try to search for any TV show I see a 'No Results Found' on the page and the logs show the error 

W20160402-13:19:35.886(-4)? (STDERR) error: tvmaze Error -> Method 'tvmaze' not found [404]

This error has been the exact same through the last two updates.

**Comment by stramel** [comment]
I too am unable to add any tv shows through plex requests.

**Comment by lokenx** [comment]
Does the admin page logs section show any other logs as well?

**Comment by lokenx** [comment]
Can you also verify that your `.meteor/packages` file has `rigrassm:tvmaze` in it, should be at the end.

Should be the same as [this](https://github.com/lokenx/plexrequests-meteor/blob/master/.meteor/packages) one.

**Comment by notinhell** [comment]
The admin page logs show the exact same error as from terminal, but the rigrassm:tvmaze was not present in the packages files. I've added it to the bottom and restarted and all seems well now.

**Comment by lokenx** [comment]
Huh your install must have gotten out of sync somewhere. Out of curiosity, what does `git status` from the command line/terminal in the root folder of the project give back?

**Comment by stramel** [comment]
@lokenx Updating to the latest version worked for me! Thanks!
