### ISSUE TITLE
non-ssl images from tvmazecdn.com

### ISSUE THREAD

**Issue by a5m0** [lokenx/plexrequests-meteor#315]
When using ssl reverse proxy images load insecurely from tvmazecdn.com

Branch: master
Version: 1.8.6

**Comment by lokenx** [comment]
That probably needs to be changed in @rigrassm TV Maze package.

**Comment by rigrassm** [comment]
OK, just looked at it. Yes, the tvmaze package is where the change should be implemented. I've actually updated the package to return HTTPS URLs for posters which will affect all searches and request submissions going forward. To solve the issue for requests already made(URLs are already stored as HTTP) I can submit a PR that changes it to HTTPS before requesting the poster.

You can run `meteor update rigrassm:tvmaze` now and search results/new requests will use HTTPS.

**Comment by a5m0** [comment]
Update worked for me thank you! Please feel free to close.

**Comment by rigrassm** [comment]
Good deal. Just committed the tvmaze package version change as well as converting existing http urls to use https instead.
