### ISSUE TITLE
Unable to search specific show

### ISSUE THREAD

**Issue by miketweaver** [lokenx/plexrequests-meteor#317]
I'm searching for a TV Show and it doesn't appear:
https://i.imgur.com/PBpDpun.png

While running tail on the logs, I get this every time I search "MacGyver":

`{"level":"error","message":"tvmaze Error -> Cannot call method 'replace' of undefined","timestamp":"2016-04-04T20:24:11.166Z"}`

That show does appear in the database:
https://www.themoviedb.org/tv/2875-macgyver

Other shows work alright, as far as I've seen.

**Comment by rigrassm** [comment]
@miketweaver fixed the issue. just run `meteor update rigrassm:tvmaze` and you should be good to go.
