### ISSUE TITLE
[Reqest] Add Web-App compatibility 

### ISSUE THREAD

**Issue by DejaVu** [lokenx/plexrequests-meteor#318]
Opening Plex Requests compared to other websites apps on Android doesn't allow a full immersive experience after adding the link to the home screen.

I believe the fix, to remove the browser bar completely is here - http://stackoverflow.com/questions/21018750/add-to-homescreen-button-in-android-does-not-show-website-as-a-web-app

Would really love this implemented and appears reasonably easy to do. I may even fork and attempt it myself this afternoon. :)

**Comment by rigrassm** [comment]
Done! Good suggestion!
