### ISSUE TITLE
ROOT_URL in systemd

### ISSUE THREAD

**Issue by Kolmain** [lokenx/plexrequests-meteor#319]
I'm trying to (and have) reverse proxy PlexRequests on my Ubuntu 15.10 server through my IIS server and slap SSL on it, but I have to use the ROOT_URL variable when starting PlexRequests (which hogs my console). How can I adapt my systemd script to run meteor using the ROOT_URL variable?

**Comment by rigrassm** [comment]
I would assume you could just add something like 
`export ROOT_URL=<something>` 
at the beginning of the script you're running. That should set the environment variable for your script.

**Comment by Kolmain** [comment]
I'm running it as a systemd service:

```

[Unit]
Description=PlexRequest
After=network.target

[Service]
User=plex 
Type=simple
WorkingDirectory=/opt/plexrequests
ExecStart=/usr/local/bin/meteor
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target

```

**Comment by rigrassm** [comment]
Create a script that exports the root url and then runs `/usr/local/bin/meteor`. Make it executable, and put the path to the script in ExecStart.

**Comment by rigrassm** [comment]
Scratch that. I forgot you can set Environment variables in systemd unit files. just do:
`Environment=ROOT_URL=<whatever>`

**Comment by Kolmain** [comment]
Ok I'll give that a go thanks. Ill let you know how it works in a few.

**Comment by Kolmain** [comment]
I get a MongoDB error now oddly enough... An unspecified uncaught exception...

**Comment by rigrassm** [comment]
Probably need to set that path too something like
`Environment=NODE_ENV=production MONGO_URL='mongodb://localhost'`

May have to check that variable, not sure if its the exact one you need set.

**Comment by rigrassm** [comment]
More correctly:
```
Environment=NODE_ENV=production
Environment=MONGO_URL=mongodb://localhost
Environment=ROOT_URL=http://localhost:8080
Environment=PORT=8080
```

**Comment by Kolmain** [comment]
That addition made it crash out with a very long STDERR.

**Comment by rigrassm** [comment]
Those may not be exact, id search for the environment variables needed for mongo to run and set them in the format above. I know i've researched this topic before and getting it going correctly can be a pain.

I personally just use tmux(or screen) to run the process and not take up a console.

**Comment by Kolmain** [comment]
How do you automate it to start at server boot though?

**Comment by rigrassm** [comment]
Thats the part I never nailed down specifically. i'll be back in a few and explain what I had found.

**Comment by Kolmain** [comment]
Thank you!

**Comment by rigrassm** [comment]
Give this a once over, seems they got it figured out. You just have to get all the little things set up just right.

https://www.reddit.com/r/Meteor/comments/24kgs8/how_to_start_my_meteor_application_using_systemd/

**Comment by Kolmain** [comment]
So I replicated that and it started and then went straight to failed... the last line of the start script was

ROOT_URL=https://domain.tld/requests meteor --port 8080

**Comment by rigrassm** [comment]
did you `export ROOT_URL`?

Also, with bash scripts, you should put each command on a new line.

**Comment by rigrassm** [comment]
What does it say when you run systemctl status <meteor-app>.service?

**Comment by Kolmain** [comment]
No, I didn't export it. How you you reccomend I do it? Do I export ROOT_URL before calling ` meteor ` ?

**Comment by rigrassm** [comment]
Yes, you need to export it. 

```
export ROOT_URL=<your-stuff>`
meteor --port 8080
```
Keep in mind you may need to also export the mongo paths too in that script.

**Comment by Kolmain** [comment]
So you're saying I'd need to do 
```

export NODE_ENV=production
export  MONGO_URL=mongodb://localhost
export  ROOT_URL=http://localhost:8080
export  PORT=8080

```

**Comment by rigrassm** [comment]
The PORT export wouldnt need to be necessary if you're running 
`meteor --port=8080`

**Comment by rigrassm** [comment]
But otherwise yes, that looks about right.

**Comment by rigrassm** [comment]
Oh, and you will need to `cd` into the apps directory before running meteor.

**Comment by Kolmain** [comment]
This is crashing the app:

```

!/bin/bash

cd /opt/plexrequests

export NODE_ENV=production
export MONGO_URL=mongodb://localhost
export ROOT_URL=http://localhost:8080
export PORT=3000

meteor --port=3000

```

**Comment by Kolmain** [comment]
I got it to launch with this:

```

!/bin/bash

cd /opt/plexrequests

export ROOT_URL=http://domain.tld/requests

meteor

```

But when I navigate to it, it says: `Unkown path`

**Comment by rigrassm** [comment]
See, I remember this being a pita to get going and it's mostly due to connecting to the mongo DB. You may try using 127.0.0.1 instead of localhost.

**Comment by rigrassm** [comment]
This is a Meteor issue though, not one caused by the app. I would also look into using a program called forever, seen a few people get things going with that too.

**Comment by rigrassm** [comment]
Nice!

**Comment by rigrassm** [comment]
@Kolmain post the script and the systemd unit file if you could. Would love to test it out.

**Comment by Kolmain** [comment]
```
[Unit]
Description=PlexRequest
After=network.target

[Service]
User=plex 
Type=simple
ExecStart=/home/username/starPlexRequests.sh
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target
```

```
!/bin/bash

cd /opt/plexrequests

export ROOT_URL=http://domain.tld/requests

meteor
```

**Comment by lokenx** [comment]
Could you also just put `ROOT_URL` before meteor...?

`ROOT_URL=http://domain.com/requests meteor`

**Comment by Kolmain** [comment]
Nope, adding ROOT_URL before meteor didn't work, it had to be exported?...

**Comment by lokenx** [comment]
Ah OK, what about after? I know it works just from the command line, but within a script it may be different.

**Comment by Kolmain** [comment]
No dice, this was the only way I could get it to work via script.
