### ISSUE TITLE
API to Add Request

### ISSUE THREAD

**Issue by Kolmain** [lokenx/plexrequests-meteor#321]
I'm working on a Skype bot for my homelab, and adding content to Plex is one of the ideas I'm currently working on. Is there any way I can POST/GET a request to like `http://plexrequestsurl/api/tv/Mad%20Men` to add Mad Men to the TV requests for my users?

**Comment by lokenx** [comment]
Currently no, Meteor is based on web-sockets and a REST API isn't currently feasible, sorry!

**Comment by Kolmain** [comment]
How would I interact with it via web-sockets?
