### ISSUE TITLE
Error getting IMDB ID: Unabled to get external ids [503]

### ISSUE THREAD

**Issue by slyguy77** [lokenx/plexrequests-meteor#323]
I am unable to request any movies. When i hit request, the button turns orange and the litlle animated circle turns, but it fails with error "couldn't submit the request, please try again" This issue has present for the past couple of versions for me. I have installed Plex request on my Linux box and my unraid and the issue remains.. Both are on the same network on sepparate machines behind an Asus router. I have two colleagues that are able to request movies just fine. One of which has the same internet provider as me. I'm at a loss as to what could be causing this. Any thoughts!

**Comment by rigrassm** [comment]
From the terminal running Meteor, can you post what it says when you make the request? Also the log, version of Linux you're running, and weather CP is on the same machine as plex requests.

**Comment by rigrassm** [comment]
Any update in this issue?

**Comment by rigrassm** [comment]
Gonna close this for now, if you are still having the issue let us know. if you could post your logs and system information too that would be great.

**Comment by slyguy77** [comment]
Sorry for the wait.. I have a 2 month old and a 3 year old at home so my time to sit at my PC is very limited. However, here's what you asked for. 

=> App running at: http://localhost:3000/
I20160417-12:47:32.551(-4)? { [Error: getaddrinfo ENOTFOUND] stack: [Getter] }
I20160417-12:48:36.046(-4)? { [Error: ETIMEDOUT] stack: [Getter] }
W20160417-12:48:36.100(-4)? (STDERR) error: Error getting IMDB ID: Unabled to get external ids [503]

**Comment by rigrassm** [comment]
Have you updated recently? There was an issue a while back where IMDb changed things up and caused a break similar to this.

When you get a chance do the following:

1. Stop Meteor
2. Make a copy of your plexrequests-meteor application directory
3. CD into the app folder and run `git pull origin master `
4. run `meteor` and try making a request

It sounds like your app may have gotten out of sync with the current version. 

PS. Wasn't trying to rush you I promise, got two kids of my own that keep me more than busy lol.

**Comment by slyguy77** [comment]
No worries. I lose so much track of time with the kids that so much stuff falls behind. People often think I'm ignoring them.lol..

I went ahead and updated like you suggested but I still can't make movie requests. I realized already that it was a version behind but I didn't think much of it since I have the latest Plex requests docker installed on my unraid box and I still can't make movie requests on that instance either. 

Here's the log from the meteor terminal session. 
=> App running at: http://localhost:3000/
I20160419-11:22:00.834(-4)? Collection2-Migrations been activated for the tv collection
I20160419-11:22:00.840(-4)? It will now start track the associated schema versions
I20160419-11:22:00.843(-4)? Collection2-Migrations been activated for the movies collection
I20160419-11:22:00.844(-4)? It will now start track the associated schema versions
I20160419-11:22:00.845(-4)? object with id Wja8fycW2WqWNDkiu is not valid. trying to migrate..
I20160419-11:22:00.845(-4)? notificationErrorTEXT required
I20160419-11:22:00.846(-4)? notificationErrorTitle required
I20160419-11:22:00.847(-4)? Updated document Wja8fycW2WqWNDkiu to a valid object
I20160419-11:22:00.848(-4)? Collection2-Migrations been activated for the settings collection
I20160419-11:22:00.849(-4)? It will now start track the associated schema versions
I20160419-12:06:23.937(-4)? { [Error: ETIMEDOUT] stack: [Getter] }
W20160419-12:06:23.952(-4)? (STDERR) error: Error getting IMDB ID: Unabled to get external ids [503]

**Comment by hikarukujo** [comment]
Getting similar things on a fresh install I just performed, lots of 502 bad gateway errors on imdb id pulls.

```
I20160421-16:16:15.581(-5)? { [Error: failed [502] <html>
I20160421-16:16:15.581(-5)?  <head><title>502 Bad Gateway</title></head>
I20160421-16:16:15.581(-5)?  <body bgcolor="white">
I20160421-16:16:15.582(-5)?  <center><h1>502 Bad Gateway</h1></center>
I20160421-16:16:15.582(-5)?  <hr><center>nginx</center>
I20160421-16:16:15.582(-5)?  </body>
I20160421-16:16:15.583(-5)?  </html>
I20160421-16:16:15.583(-5)?  ] stack: [Getter] }
W20160421-16:16:15.583(-5)? (STDERR) error: Error getting IMDB ID: Unabled to get external ids [503]
```

**Comment by lokenx** [comment]
@hikarukujo Hmm interesting, sounds like TheMovieDB is having issues responding to your requests (within the 4 second timeout window) or it doesn't like the movie you're searching for.

Could we know what your searching for? Could you try some main stream blockbusters?

**Comment by hikarukujo** [comment]
I thought that at first, was looking for something I knew I didn't have. But I was searching "Star Trek" in that example above and trying to add Into Darkness and it was failing. It seems better now, I wonder if tmdb was under high load?

**Comment by lokenx** [comment]
Entirely possible, or scheduled maintenance or the like. Please report back if you have issues again!

**Comment by lokenx** [comment]
@slyguy77 are you still have issues?

**Comment by slyguy77** [comment]
It works! What changed? Was the issue with IMDb? If so then why wouldn't there be more people with the same issue? 

Anyhow,  I'm glad it's up and running. 

Thanks for the help.

**Comment by hikarukujo** [comment]
Zero issues now today, looks like it was something transient on tmdb or imdb causing issues with the lookups. Maybe it was regional if it didn't affect others?

**Comment by lokenx** [comment]
@slyguy77 not IMDB, [TheMovieDB](https://www.themoviedb.org/) is the movies provider, so they could have had intermittent issues. Hard to say as we have no visibility into it.

**Comment by rigrassm** [comment]
For what its worth I saw no issues either. It was probably their end.

**Comment by lokenx** [comment]
Safe to close, but please report if it occurs again!

**Comment by morbidpete** [comment]
Having this same issue again as of this morning. Maybe an issue with IMDB again? I'll post back later if anything changes

**Comment by ampadmos** [comment]
I know this is an older thread, but I am having this issue as well.

**Comment by jeffp1717** [comment]
I'm having this issue on a fresh install as well.
