### ISSUE TITLE
Couchpotato Error when using Server Hostname

### ISSUE THREAD

**Issue by motonuke** [lokenx/plexrequests-meteor#328]
Couchpotato integration throws an error when using hostname to connect (hosted on another server). IP works fine. This started happening within the last few updates.

**Comment by lokenx** [comment]
Hmm I don't think we changed anything regarding. Can you confirm the machine can do a regular DNS lookup for the machine it's trying to connect to for CouchPotato? Just to confirm it's PlexRequests and not the machine that is having issues resolving the name.

**Comment by motonuke** [comment]
Yes, DNS resolution is working on the host and inside the container (docker running on Ubuntu 14.04). Here is the odd part, and why I submitted an issue, is that the Sonarr config works just fine using a hostname. Happy to send logs, etc, but it wasn't obvious (to me) how to enable logging or turn logging levels higher. Thanks!

**Comment by rigrassm** [comment]
Is CP running behind a reverse proxy(nginx, apache) by chance?

**Comment by motonuke** [comment]
@rigrassm No reverse proxy anywhere internally. My setup is pretty straightforward:

WHS2011 box running CP (from source) and Sonarr. I have another ESXi box, with an Ubuntu VM installed. Inside this VM is a docker container running PlexRequests. Network is all 1 flat /24. 

From within PlexRequests, Sonarr will use a hostname just fine, but CP doesn't work.

I do notice when I get a connection test failure, this is logged on the console (viewed when using "docker attach...") of the docker container:

{ [Error: ESOCKETTIMEDOUT] code: 'ESOCKETTIMEDOUT' }

This isn't logged on a successful test.

**Comment by rigrassm** [comment]
Are you using local DNS hostnames?

**Comment by lokenx** [comment]
And does CP have any logging errors when trying to connect? And you are hitting **Update Settings** after changes

**Comment by motonuke** [comment]
@rigrassm Yes, Local DNS provided through my router (pfSense). The name and domain are resolved by pfSense. Now that you mention this, I thought of something else that may be interfering. I'm using OpenDNS as my first 2 DNS servers, and the local resolver as the 3rd. Local resolution seems to work fine on most other devices, but maybe it's interfering here?
@lokenx I'll have to check the CP logs. Yes, hitting Update Settings after each change.

**Comment by rigrassm** [comment]
Willing to bet there local DNS is the issue. Try making it the first in line and see if that helps out. Also, check your router logs and see if you can see anything that looks off

**Comment by rigrassm** [comment]
@motonuke any luck getting this going?

**Comment by motonuke** [comment]
@rigrassm Made some progress. I overrode the DNS settings for the OS and it's working now. 

It's strange that Sonarr worked but CP didn't. 

Not sure if you want to pursue further within the code, but the issue for me is resolved.
