### ISSUE TITLE
[Error: connect ECONNREFUSED] stack: [Getter]

### ISSUE THREAD

**Issue by Cruv** [lokenx/plexrequests-meteor#330]
As of a few days ago I get the error

[Error: connect ECONNREFUSED] stack: [Getter]

Any ideas? I have tried updating using Remote>Fetch>origin and it said success but I still get a message that there is an update available. PR says I'm on 1.8.3. Is that current? Should I blow this installation away and try from scratch?

**Comment by rigrassm** [comment]
1.8.9 is the latest. If you're on Windows using the Git GUI, the Fetch option doesn't work correctly and you'll need to perform a pull.

I'd backup your .meteor/local/db folder beforehand to be safe.

**Comment by lokenx** [comment]
1.9 was merged the other day so it should update to that once you `git pull`. The about page should now also show the latest changes.

**Comment by Cruv** [comment]
Thanks gentleman. Glad to know I wasn't crazy (this time at least). I have updated and it seems to be working. Great work!
