### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by wookienz** [lokenx/plexrequests-meteor#331]
[scott@localhost plexrequests-meteor]$ meteor
                                                                                   
/home/scott/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
undefined

[scott@localhost plexrequests-meteor]$

Am i missing some dependencies?

thanks.

**Comment by wookienz** [comment]
Downgraded to Meteor 1.2.1. Fixed.

**Comment by lokenx** [comment]
Yeah 1.3 is still a bit all over the place, newer versions of 1.3.x seem to be fixing issues but not 100% sure yet. See #314
