### ISSUE TITLE
[Request] Allow users to request tv shows, movies, or both per user

### ISSUE THREAD

**Issue by PhAzE-Variance** [lokenx/plexrequests-meteor#332]
Add ability for different users to have different options. Some users can only request movies while others can only request tv shows, or both movies and tv shows.

The main reson behind this is tv shows can be huge and i wouldnt want everyone i allow on to add shows while family members i would allow.

**Comment by rigrassm** [comment]
You can already require approval based on if it's TV or movies. Right now, without full featured user accounts this would not be very feasible.
