### ISSUE TITLE
[Request] Allow use of base url for reverse proxies

### ISSUE THREAD

**Issue by PhAzE-Variance** [lokenx/plexrequests-meteor#333]
Can support be added to allow a base url to the gui so that a reverse proxy can be used. An example is
Http://192.168.1.3:9077/request -> http://domain.com/requests

All of the Web pages will need to become a sub directory of the base url.

**Comment by lokenx** [comment]
A base url should be possible using the `ROOT_URL` environmental variable, typically passed during startup or in a startup script.

```
➜ ~/Development/apps/plexrequests-meteor (sonarr-profiles) ROOT_URL=http://localhost/requests meteor
[[[[[ ~/Development/apps/plexrequests-meteor ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost/requests
```

Using `/requests` would look funny mind you for the requests page; domain.com/requests/requests.
