### ISSUE TITLE
[Request] SMS notifications

### ISSUE THREAD

**Issue by stohle** [lokenx/plexrequests-meteor#337]
so im wondering if theres any chance of integrating a SMS gateway API?

a user request something, admin get pushbullet notification or another service, admin approves item requested. user get text saying " [item name] approved by admin. ETA [from sabnzbd/deluge api]. when the item is avaliable. the user get a text with " [item name] is now available at [Plex server name].

I have not checked all the required api's if this is possible. its just an idea i had.

**Comment by duramato** [comment]
Do you know of any free sms api/provider? I remeber one french provider that ofered an sms api for their costumers, free.fr but besides that dont remeber

**Comment by stohle** [comment]
Doesnt have to be a free provider. As long as they have an api its all good. I googled and found a ton of providers. It all comes down to pricing. One provider had pay per sms. 0,031 norwegian krone. Which is.. Nothing. Most sms gateway providers are made for businesses and they cost a pretty sum of 400 norwegian krone a month with 50k sms. Which isnt alot of money but not even close to worth it for me or anybody else for that matter

**Comment by rigrassm** [comment]
I'm going to be adding IFTTT maker soon which should address most notification needs including SMS. It'll open up many new options, not just notifications.

**Comment by rigrassm** [comment]
Pull request #346 would allow for this through utilizing [IFTTT Maker](https://ifttt.com/maker).

**Comment by rigrassm** [comment]
Going to close this as I don't see direct SMS support being implemented since this can be done through ifttt for free.

If someone comes along with a free service that has an API I'll definitely consider it.
