### ISSUE TITLE
Can't connect to remote Couchpotato Installation

### ISSUE THREAD

**Issue by mrgerrm** [lokenx/plexrequests-meteor#339]
I have a seedbox with Couchpotato installed on it. It's working normally with rutorrent. I've tried putting in all the settings for Plex Requests but it just says error! and when I look at the logs there is nothing there. I've also setup Sonarr locally and it's working just fine with Plex Requests.

I can't find a solution to this issue. Anyone have any ideas?

**Comment by rigrassm** [comment]
Are you using a domain name or IP address? Is CouchPotato behind a reverse proxy like Nginx or Apache?

**Comment by mrgerrm** [comment]
Ohhh, those are good questions. For sure I'm using a domain name. Not sure about a reverse proxy. I can ask my provider. If it is behind a reverse proxy then what would I need to do?

**Comment by rigrassm** [comment]
I would just use the IP address and port tbh. They may have to open up the port you need as well. There's tons of variables in play here and your best bet is going to be with talking to your provider.

**Comment by mrgerrm** [comment]
Ok, I'm going to submit a support ticket now. Don't close this thread (if you have the ability to) I would like to be able to ask more questions regarding this should they come up.

**Comment by mrgerrm** [comment]
Just wanted to update and say that I never got this resolved but instead installed CP locally alongside Sonarr and now everything is working perfectly. I think the local installation is a better solution due to the fact if I change my seedbox then I don't lose my CP information, nor do I have to transfer it etc

**Comment by rigrassm** [comment]
@mrgerrm its probably best to separate your seed box from your other services for that and other reasons as well. As far as the issue with connecting, it was likely something on the seedbox providers end, they can be pretty locked down. Since you got it up and running though i'll close this ticket. Good luck and enjoy!
