### ISSUE TITLE
[REQUEST] Category/Directory support SickRage/Sonarr

### ISSUE THREAD

**Issue by Thr3d** [lokenx/plexrequests-meteor#347]
Would be neat with the ability for admin to pick Directory/Path for a request to be added under when approved. And possibly limited support for "Customize Options" in SickRage and "Series Type" in Sonarr (specifically flagging a show as Anime).

Thanks! :neckbeard:

**Comment by lokenx** [comment]
Think you're looking for #200!

**Comment by Thr3d** [comment]
Cool! Saw that but wasn't sure if it would only be for CP.

**Comment by lokenx** [comment]
The idea would be to do it for all--I like to keep feature parity between the services (to the chagrin of some).
