### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by kfulgham** [lokenx/plexrequests-meteor#351]
Your app is crashing. Here's the latest log:

> No change detected for the collection tv
> No change detected for the collection movies
> No change detected for the collection settings
> 
> /Users/homemedia/.meteor/packages/meteor-tool/.1.3.2_4.1h7nta1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
> 						throw(ex);
> 						      ^
> Error: A method named 'TMDBSearch' is already defined
>     at packages/ddp-server/livedata_server.js:1548:15
>     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
>     at Server.methods (packages/ddp-server/livedata_server.js:1544:7)
>     at app/server/methods/helpers/movies/TMDBSearch.js:6:8
>     at app/server/methods/helpers/movies/TMDBSearch.js:96:4
>     at /Applications/PlexRequests/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:283:10
>     at Array.forEach (native)
>     at Function._.each._.forEach (/Users/homemedia/.meteor/packages/meteor-tool/.1.3.2_4.1h7nta1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
>     at /Applications/PlexRequests/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:133:5
> Exited with code: 8
> Your application is crashing. Waiting for file change.
> 

I've tried deleting and re-installing Plex Requests but nothing is working.

**Comment by rigrassm** [comment]
Backup your .meteor/local/db folder, delete the plexrequests-meteor folder,
execute

```
git clone https://github.com/lokenx/plexrequests-meteor
cd plexrequests-meteor
meteor
```

Once it starts, stop it with a ctl+c and copy your .meteor/local/db folder
back into the application's folder

**Comment by rigrassm** [comment]
Ever resolve your issue?

**Comment by kfulgham** [comment]
Thanks for checking back with me. I had do a complete remove and fresh install. Luckily setup is quick and easy. 

Cheers.
