### ISSUE TITLE
Synology app

### ISSUE THREAD

**Issue by enter1010** [lokenx/plexrequests-meteor#353]
Hello,
Thanks for you job. I don't know if I'm in the good section, sorry if it is not the case. 

I want to know if it is possible to generate a Synology app to simplify the installation on this device ? 

Thanks in advance.

**Comment by Jeradin** [comment]
You can use the docker app in DSM to install this package: https://github.com/aptalca/docker-plexrequests

It works great and how I one click installed Plex Requests on my Synology.

**Comment by lokenx** [comment]
I think the below also works, someone said it auto updates as changes get pushed and what not...but I use neither and can't attest to which works better!

https://hub.docker.com/r/lokenx/plexrequests-meteor/

**Comment by enter1010** [comment]
It's perfect, thanks !
