### ISSUE TITLE
[Request] Reverse Proxy

### ISSUE THREAD

**Issue by bkoch53** [lokenx/plexrequests-meteor#354]
So far reverse proxy with Nginx has been a pain and doesn't return anything but white page. I have all of my other services going through a reverse proxy but plexrequests doesn't play nice.. If this could be integrated in the menu or have better support, it would help a lot.

**Comment by rigrassm** [comment]
Weird, I have mine running behind an Nginx reverse proxy too and have never
had any issues. Post your Nginx config and I'll take a look and see if I
can find anything

**Comment by bkoch53** [comment]
```
 # No Works
  location  /plexrequests/ {
    proxy_pass  http://192.168.0.19:3000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect  default;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
  }
```

**Comment by rigrassm** [comment]
Is Nginx running on the same server as plexrequests? If so, change the
192.168.0.19:3000 to 127.0.0.1:3000.

**Comment by bkoch53** [comment]
Nope, it's a different server. I wanted to have a dedicated proxy server.

**Comment by rigrassm** [comment]
Have you checked that you allowed incoming connections on the plexrequests
server?

**Comment by bkoch53** [comment]
Without the proxy, it works great. Can hit it from 192.168.0.19:3000 and from mydomain.com:3000. So I believe so.

**Comment by rigrassm** [comment]
Try setting it to be the root directory ("/") instead of /plexrequests/,
see if that gets it working.

**Comment by bkoch53** [comment]
So that work but I can't leave it root. Any ideas as to why it would only drop when redirected?

**Comment by rigrassm** [comment]
May be a Meteor issue, I use subdomains instead of directories so I haven't
come across the issue.

**Comment by bkoch53** [comment]
Ah I see. Well thanks for the help anyways. Below I found some errors in the Nginx logs. It's like its ignoring the redirect and searching the local system.

`2016/05/16 20:22:27 [error] 11295#0: *4 open() "/usr/share/nginx/html/packages/service-configuration.js" failed (2: No such file or directory), client: ip.ip.ip.ip, server: mydomain.com, request: "GET /packages/service-configuration.js?4940b1e4138b53dafd1a46ae719ad64bec87e957 HTTP/1.1", host: "enigmanetworks.tech", referrer: "https://mydomian.com/plexrequests/"`

**Comment by bkoch53** [comment]
My original request still stands, it would still be cool to have this functionality built in.

**Comment by lokenx** [comment]
If you're using a sub dir instead of subdomain you need to pass meteor the `ROOT_URL` environment variable on startup so it's paths get adjusted accordingly.

```
ROOT_URL=http://localhost/plex meteor

=> App running at: http://localhost/plex
```

**Comment by bkoch53** [comment]
Neat! I didn't know about this. Thanks!

**Comment by nbisson** [comment]
Hey guys! I'm having issues running plexrequests behind an apache reverse proxy similar to @bkoch53 original post. Apache proxy & PlexRequests are running on the same unRAID server (via Docker apps) with the same IP and using sub directories. 

When I pass these variables & restart both containers...
> ROOT_URL=http://localhost/plex meteor

=> App running at: http://localhost/plex
> 

... my webpage shows up as a blank page with 'Unknown path' listed (this occurs both on the local IP as well as the proxy address.

Any suggestions?

**Comment by bkoch53** [comment]
Could you post your configs for us?

**Comment by Doonga** [comment]
`ROOT_URL=http://localhost/plex meteor`

You can't have that space there. Try an underscore or just remove the space.

In your apache config, make sure you have a location that matches /plexmeteor (or plex_meteor) depending on what you made the ROOT_URL.

**Comment by bkoch53** [comment]
"ROOT_URL=http <http://localhost/plex>:// <http://localhost/plex>localhost
<http://localhost/plex>/ <http://localhost/plex>plex <http://localhost/plex>
meteor" is specifying an environmental variable then launching meteor. It
won't exists in the Apache config.

**Comment by Doonga** [comment]
Ohh! Ok, I thought he was trying to make his context root "plex meteor". Never mind!

**Comment by nbisson** [comment]
@bkoch53 @Doonga Thanks for the help. Removing the space was the issue (slam face into keyboard).

My end set up was `ROOT_URL=http://localhost/plexrequests'` with the apache config the same.

Any ideas on being able to access plexrequests via local IP without going through the proxy?

**Comment by Doonga** [comment]
Easiest way would be to go straight at what you have in your ProxyPass line. Although this is kinda ugly in the browser. :) Using your example above: http://192.168.1.51:3000/plexrequests. If you want the pretty URLs you need to run it through the proxy. Most routers have NAT reflection where you can use the public IP internally and it'll work as if you were coming in from the internet. If that's the case, then that's your best bet as there's no harm in running through the proxy from the internal network. Plus you get the pretty URL and you can use the same bookmark locally and on the internet. Not all routers do that though, so your milage may vary. There's also some DNS trickery you can do to make this work if your router can't do NAT reflection, but that's a rather long explanation. Split-DNS is what it's called if you're interested in Googling that. That's definitely advanced, I have no idea of your experience level so I'll let you figure out what you want to try or not. :)

**Comment by nbisson** [comment]
@Doonga gotcha. I normally use the IP:port for management but wanted to set up reverse proxy to set up minmux... I just needed that extra /plexrequests to access via local IP... Thank you!
