### ISSUE TITLE
PlexRequest won't start as Daemon

### ISSUE THREAD

**Issue by damiantje99** [lokenx/plexrequests-meteor#359]
Hi,

I'm trying to run PlexRequest as Daemon. So I followed you're guide. Everything went fine, no errors while creating or starting the services. But when I start it, nothing happens. It just acts like its everything is fine, but the PlexRequest service won't appear in service --status-all and the page itself won't load.

Am I doing something wrong?

Hope to hear from you.

**Comment by damiantje99** [comment]
Found the solution. 

Was getting this error:

`Error: EACCES, unlink '/opt/plexrequests/.meteor/local/db/mongod.lock'
    at Object.Future.wait (/home/administrator/.meteor/packages/meteor-tool/.1.1.10.sfu42q++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as unlink] (/tools/fs/files.js:1334:20)
    at findMongoAndKillItDead (/tools/runners/run-mongo.js:318:11)
    at launchOneMongoAndWaitForReadyForInitiate (/tools/runners/run-mongo.js:400:7)
    at launchMongo (/tools/runners/run-mongo.js:656:7)
    at [object Object]._.extend._startOrRestart (/tools/runners/run-mongo.js:756:19)
    at [object Object]._.extend.start (/tools/runners/run-mongo.js:714:10)
    at /tools/runners/run-all.js:168:26
    - - - - -`

Fixed by setting user to Root.

**Comment by rigrassm** [comment]
@damiantje99 What distribution are you using and are you using systemd to run as a daemon? You shouldn't have to(nor should you) run the app as root.

**Comment by damiantje99** [comment]
Hi, 

Im running Ubuntu 16.04. I start the service with 
systemctl start plexrequests.service

But when I set a user in the service config other then root, I'm getting the error I mentioned earlier.

How can I run this as administrator user then?

**Comment by rigrassm** [comment]
You can set the daemon to run as a set user and group using the User=usr & Group=grp unit file settings. You need to make sure that whatever user you run meteor as has rw rights to the entire application. You'll still have to start the program using sudo systemctl <service> but it will run as the user you specified in the unit file.

Example of my setup, the user `plex` has ownership of the  `/apps/plexrequests-meteor` directory.

```
[Unit]
Description=PlexRequests Daemon

[Service]
WorkingDirectory=/apps/plexrequests-meteor
Type=simple
User=plex
Group=plex
ExecStart=/usr/local/bin/meteor

[Install]
WantedBy=multi-user.target
```

**Comment by lokenx** [comment]
If you're running on Ubuntu, also checkout [MUP(X)](https://github.com/arunoda/meteor-up), super awesome automated deployment--what I use personally.

**Comment by rigrassm** [comment]
Going to close this issue since it was resolved
