### ISSUE TITLE
<Request> Decline request with reason

### ISSUE THREAD

**Issue by Foebik** [lokenx/plexrequests-meteor#361]
Title pretty much sums it up. There is times where I don't want to approve something, so I delete it. The user just adds it back thinking something went wrong. This goes on until I just leave it sitting there like I never saw it in the first place because I didn't approve it. If I could decline it with a small field for text as to why I declined it, that would be perfect.

**Comment by lokenx** [comment]
Closing as it's the same as #133 , also a open PR for this by @Qw-in.
