### ISSUE TITLE
Error: A method named 'setTestVARS' is alre ady defined

### ISSUE THREAD

**Issue by alternativesurfer** [lokenx/plexrequests-meteor#362]
Updated to the latest push today, upon restarting received this error and the app would not launch.

http://pastebin.com/WzH4qAqa

**Comment by rigrassm** [comment]
How did you update. The windows git GUI program is notorious for not behaving correctly using git fetch. You need to do a git pull instead.

Before you update, make sure to backup your database beforehand to be safe. If you still have the issue, go ahead and just delete the application and pull down a fresh copy from github. starrt it up for the first time and let it get to the point where it's running then shut it down, copy your DB folder back into it and then restart.
