### ISSUE TITLE
Bug: Sending all request as approved.

### ISSUE THREAD

**Issue by D1ag0nall3y** [lokenx/plexrequests-meteor#366]
Whenever one of the users adds a TV or Movie, I have noticed that it automatically marks it as approved.

None of these users are set to auto approve.
The general settings requires approval for both tv and movies.

I have tried switching each of the options on and off and no configuration will correctly setup a request from a user with it not approved.

**Comment by lokenx** [comment]
Are you adding the requests, or the users themselves from their own machines?

What's your exact settings for auth/requests?

**Comment by rigrassm** [comment]
Any update on this @D1ag0nall3y?

**Comment by D1ag0nall3y** [comment]
Sorry, I guess it didn't post my reply. I have since moved to the .net version because it supported all my feature request and didn't have the bus I was having on the meteor release. I understand they are not developed by the same developer.

However, thus occurred when others logged in and submitted the request. It would just auto approve.

The settings were set to where everyone but myself required authorization. No one was in the whitelist. 

Experience: user logs inn and submits request
I check request page from admin and it shows check mark next to approved.
End user also sees this check mark.

**Comment by rigrassm** [comment]
@lokenx, were you able to reproduce this bug? I tried with my setup and couldn't replicate.

**Comment by D1ag0nall3y** [comment]
I was able to reproduce with 3 users logins. Though there may have just been something installed wrong. Feel free to close. If I find the time to reinstall, I will try and see if I can replicate and comment back here.

**Comment by andrewchumchal** [comment]
I am having this same issues. I have tried 3 different machines and different user all of the request get approved with me saying so. Please help
