### ISSUE TITLE
Issue with pushbullet notifications?

### ISSUE THREAD

**Issue by ammmze** [lokenx/plexrequests-meteor#370]
Is anybody else having issues with the pushbullet notifications? I am new to plex requests and was trying to setup pushbullet notifications but when i attempt to test the settings, it fails with the error `Access token is missing or invalid.`. I'm using a freshly generated access token from the [settings page](https://www.pushbullet.com/#settings/account). The logs don't show any more...

```
plex-requests_1      | error: Pushbullet notification error: Access token is missing or invalid.
```

**Comment by rigrassm** [comment]
Make sure you click update settings before you click test. if you did that,
make sure there is'nt a trailing space at the end of the key, had that
happen to me before when copying it.

**Comment by ammmze** [comment]
Ah...gotta save it first...that works. Thanks
