### ISSUE TITLE
e-mail as username

### ISSUE THREAD

**Issue by Rogue136198** [lokenx/plexrequests-meteor#371]
Currently the authentication rejects when I use my email rather than my username for plex. The system can support email as a format because my sisters account works fine because her username is her email. 

If this could be addressed in a future release it would be appreciated.

**Comment by lokenx** [comment]
Hmmm I don't think emails should work, the Plex API wants a username. However, it's not greatly documented and could have changed. I'll have a check!

**Comment by Rogue136198** [comment]
Yes her username is her email. Same data but in different fields. I would prefer to use emails since my family all know their emails but not the username plex assigned them (yes most of them are just the part of the email before the @ except for my sister and me who has a custom forum name)

**Comment by lokenx** [comment]
Ah OK. Well originally you couldn't authenticate with an email address so we went forward with usernames. I don't know if it's worth the hassle to redo all of that code to work with emails/both, but will keep this open.

**Comment by cknolla** [comment]
Also requesting this feature -- this was the cause of my inability to login with my Plex user account (since I use email address in every other application, I didn't even realize a non-email username existed).

**Comment by rigrassm** [comment]
Gonna revisit this since it looks like it doesn't matter if you use an email or username when I was manually testing the sign_in.json endpoint.

**Comment by JagandeepBrar** [comment]
I've added support for this in pull request #502.

**Comment by JagandeepBrar** [comment]
Added support in pull requests #502.

**Comment by lokenx** [comment]
Believe this is done by rigrassm in https://github.com/lokenx/plexrequests-meteor/releases/tag/v1.21.0
