### ISSUE TITLE
Admin Access Redirected

### ISSUE THREAD

**Issue by itserrick** [lokenx/plexrequests-meteor#374]
When in the Admin center of plex requests, I am able to login and it shows the general section. I'm able to update settings on that page just fine but once I click on a different tab (authentication, couch potato, about, etc.) it redirects the page to regular Plex Requests login. And if that page is logged in as well it says you're already logged in! and allows requests. 

I tried meteor update. Reinstalling plex request from scratch, same issue comes up

**Comment by itserrick** [comment]
Issue solved itself... strange

**Comment by stohle** [comment]
Clearing browser cache fixed the same issue for me. (Commenting a possible
solution for others who might have the same problem)
15. jun. 2016 06:58 skrev "itserrick" <notifications@github.com>:
