### ISSUE TITLE
FATAL ERROR: JS Allocation failed - process out of memory

### ISSUE THREAD

**Issue by Foebik** [lokenx/plexrequests-meteor#375]
So starting on Tuesday afternoon I started getting alerts from my server that my PlexRequest page was down. I started it back up and it would crash again within a few minutes. I restarted the computer and ran meteor in a cmd promt to see what was going on. I notice that there was 8 updates it wanted to download (Im currently on 1.3). After downloading them it would it would crash again.

I download the latest updates to PlexRequest (was 4 commits behind) hoping it would help. Same issue. I backup and delete the local folder, this kinda helped. The 8 updates would download and the request would be up for a few minutes before I got the the below error.

FATAL ERROR: JS Allocation failed - process out of memory

Doing my own research I found everything from a memory leak, failed to close an ejs block and the file was js code, Issue with Meteor itself; to  heap size & RSS size are not set high enough.

When it fails I still have around 4gb of RAM available. Unfortunately I know less than nothing on how to fix meteor/JS applications. Any Ideas?

**Comment by lokenx** [comment]
What's your environment details?

What happens when you spin up a clean new app in a different folder entirely?

**Comment by Foebik** [comment]
Windows 7
8gb ram
swap file enabled

I created a new folder and downloaded the latest and greatest of PlexRequest. 
Tried running it by command line, it started to download and install those 8 packages.
During that time it must of been somewhat up as I got an email from StatusCast saying it was back up  (StatusCast just pings the port and creates a offline ticket if it is unreachable). But it never finishes and it silently crashes (no error). Doesn't even kick me back to the prompt like it usually does when it was crashing.
I'm thinking one of those 8 packages is messing me up. 

I went out and came back, the CMD prompt looks just like below for the last 2 hours. The spinning dos line that shows its working is even frozen.
Watching my Network traffic each time I tried this, it appears that the 8 packages are downloaded successfully. And a few times they must of install correctly, just to later crash.
![fail](https://cloud.githubusercontent.com/assets/6633492/16139223/2e173164-3413-11e6-8851-bb16d4aa3f94.JPG)

I ran it a second time and it seem to go through. Going to let it run over night like this and see if it crashes again.
![success](https://cloud.githubusercontent.com/assets/6633492/16139502/1a225f0a-3416-11e6-8586-0f2abc3dcfbc.JPG)

**Comment by Foebik** [comment]
Looks like it crashed silently again. No change in the cmd (same as the last image in the last post). But it is defiantly not responding anymore.

**Comment by lokenx** [comment]
My email reply that never seems to come through:

> Hmm I'm not sure what's changed, we haven't added any packages but it's possible one of them is trying to update. Can you try a meteor update in test one? To both update meteor as well as the packages in app.
> On mobile so can't lookup exact commands, sorry!

**Comment by Foebik** [comment]
Yep, I know the commands. I can try when I get home this evening.

Im not sure if it actually has anything to do with your app specifically. It started having issue all on its own and I hadn't done a GIT pull for quite a while. Maybe one of the packages that your app uses got updated and is now causing errors.

Anyhow, Ill let you know after I run a full meteor update tonight.

**Comment by Foebik** [comment]
So I tried the above. Didn't work. I tried removing Meteor and reinstalling. Even more errors. I could even get Kadira Debug installed to help. So I think Meteor got borked for me, which is unfortunate. 

I'm trying out the .Net version now and it seems to be running ok.
