### ISSUE TITLE
Excessive Sonarr API calls

### ISSUE THREAD

**Issue by Taloth** [lokenx/plexrequests-meteor#377]
Sonarr Dev here.

I've got a user that's having some performance issues. During my investigation I noticed quite a bit of API calls from plexrequests every hour.
His db is quite large, so the `/api/series` call takes over 2 seconds. This means that the hourly plexrequests update cycle takes ~14min.
However, plex requests seems to query the `/api/series` endpoint, and then `/api/series/{id}` endpoint for each series separately.

First, the separate `/api/series/{id}` call is not necessary, since the `/api/series` endpoint contains all statistics.
Secondly, it might be a good idea to cache `/api/series` response, at least for a minute or two. That ought to reduce the apicalls from 400+ to less than a dozen.
Finally, also saw an erroneous `/api/series/undefined` call in the log.

Incidentally it's also causing a huge memory leak in Sonarr on his hardware. Not reproducible on my end atm, but I'll continue to investigate, obviously no concern for plexrequests. (If plexrequests it turned on it grows to 4GB MEM within a day, while it takes weeks without.)

```
16-6-11 11:00:03.2|Debug|Api|[GET] /api/series/: 200.OK (2717 ms)
16-6-11 11:00:03.8|Debug|Api|[GET] /api/series/593: 200.OK (293 ms)
16-6-11 11:00:06.0|Debug|Api|[GET] /api/series/: 200.OK (2194 ms)
16-6-11 11:00:06.5|Debug|Api|[GET] /api/series/594: 200.OK (212 ms)
...
16-6-11 11:01:37.0|Debug|Api|[GET] /api/series/: 200.OK (2657 ms)
16-6-11 11:01:37.7|Debug|Api|[GET] /api/series/653: 200.OK (285 ms)
16-6-11 11:01:40.3|Debug|Api|[GET] /api/series/: 200.OK (2570 ms)
16-6-11 11:01:40.8|Debug|Api|[GET] /api/series/undefined: 404.NotFound (0 ms)
16-6-11 11:01:43.4|Debug|Api|[GET] /api/series/: 200.OK (2639 ms)
16-6-11 11:01:44.1|Debug|Api|[GET] /api/series/655: 200.OK (289 ms)
16-6-11 11:01:46.4|Debug|Api|[GET] /api/series/: 200.OK (2329 ms)
16-6-11 11:01:47.0|Debug|Api|[GET] /api/series/275: 200.OK (295 ms)
...
```

**Comment by thezoggy** [comment]
also to note that plexrequests queries sonarr/cp/sr for each show/movie on each hour. thus if you have large collections.. you see excessive use each hour... for the short term I've changed this from 1 to 12 hours:

https://github.com/lokenx/plexrequests-meteor/blob/master/server/startup/cronjobs.js

https://github.com/lokenx/plexrequests-meteor/blob/master/server/methods/cronjobs/updateSonarr.js#L10

**Comment by lokenx** [comment]
I didn't think the `/api/series` end point included episode information for the shows? I think we did it that way because we didn't have Sonarr ID's so used that to get the list of ID's to then get more detailed info.

However if the info is available in the main call we can remove the subsequent ones. That would make it a single call every hour which shouldn't be an issue? (And people complained the hour wasn't frequent enough :expressionless: )

**Comment by Taloth** [comment]
The /api/series endpoint doesn't contain the individual episode details, but it does contain the series-wide and season statistics your using.

**Comment by lokenx** [comment]
Sorry for the delay, been dealing with some IRL stuff. I had a quick look and I need to adjust the Sonarr wrapper package to help fix this. Currently it's what's actually checking Sonarr for each request. So I'm going to change it to just accept an array of shows and then to get the list and return array of info back.

**Comment by rigrassm** [comment]
What do you say about just moving the Sonarr, SickRage and CouchPotato
wrappers into the main package since they are pretty specific to our
applications use case?

**Comment by lokenx** [comment]
@rigrassm yeah that would make sense! Can send a PR for it or I'll spin out a branch. I'm just dealing with bunch of stuff IRL at the moment, barely have a moment in front of the computer

**Comment by rigrassm** [comment]
@lokenx Same here, in the middle of starting a new job lol. I know I worked
on it a bit before but i think I sidelined it for some reason.

**Comment by rigrassm** [comment]
Issue has been addressed over multiple pull requests. Issue should have been resolved for a while now.
