### ISSUE TITLE
Error: "Couldn't submit request, please try again" for TV shows

### ISSUE THREAD

**Issue by cjdbury** [lokenx/plexrequests-meteor#378]
Movies work fine, but every time I try to request a TV show, I get that error message.  I don't know much about the meteor environment or really how Plex Requests works, but I'll try to provide any more information that may be needed

**Comment by rigrassm** [comment]
What do the logs say? Are you using Sonarr? If so, make sure to set a
quality profile and update your settings.

**Comment by cjdbury** [comment]
I am using Sonarr, and per your suggestion I went into the settings and set a quality profile which fixed the issue.  Not sure how I missed that before.  Thanks man!

**Comment by Qw-in** [comment]
Seems Resolved, so I'll close this
