### ISSUE TITLE
Docker improvement: Store config in a volume

### ISSUE THREAD

**Issue by rossdargan** [lokenx/plexrequests-meteor#381]
Could you improve the docker container so all the settings were stored in a volume. This allows us to easily tear down the container, and bring it back up without losing settings.

**Comment by lokenx** [comment]
Honestly, don't use Docker personally and not sure how to go about this--but if you or someone else is more versed in it please open a PR!

Out of curiosity which Docker are you using, I believe there's a few floating around.

**Comment by rossdargan** [comment]
Ah - for the DB the volumes are /data/db, and /data/configdb. I'll do a PR if you want on the docs?

**Comment by romracer** [comment]
Its as simple as adding this under the mongo container in the docker-compose.yml:

```
volumes:
  - /mnt/path/on/host:/data/db
```

No need for configdb as that's only if you're running MongoDB as a config server (you're not doing that probably).

**Comment by lokenx** [comment]
Added in #403
