### ISSUE TITLE
Unable to connect to CouchPotato

### ISSUE THREAD

**Issue by cyberjacob** [lokenx/plexrequests-meteor#383]
Fresh install of plexrequests and meteor on Ubuntu 14.04. After inputting the CouchPotato details and hitting save, the test button immediately changes to "Error".

Checking the console logs, I can see the following is generated each time I hit test:

    I20160710-15:46:13.987(1)? { [Error: getaddrinfo ENOTFOUND] stack: [Getter] }

I've tried using the local and global IPs, as well as 127.0.0.1 and localhost, however they all give the same error.

**Comment by lokenx** [comment]
Do those IP's/localhost resolve when run locally on the machine? Is your host/hostname files all appear good? DNS setup?

**Comment by rigrassm** [comment]
Make sure you are saving the settings by clicking the orange update
settings button at the bottom of the page before trying to test.
