### ISSUE TITLE
Sonarr Series Post -> Match error: Expected string, got undefined

### ISSUE THREAD

**Issue by Gamechiefx** [lokenx/plexrequests-meteor#385]
Sonarr pulls were working and then at some point they just died. looking at the logs i see the error:

I20160713-10:43:25.168(-4)? Sonarr Series Post -> Match error: Expected string,
got undefined

please let me know if there are any other logs i would need to post to help in troubleshooting

**Comment by Gamechiefx** [comment]
can anyone help?

**Comment by lokenx** [comment]
Sorry didn't see this notification! Is this happening on requests? All requests, certain requests? Certain users? What version are you running?

**Comment by rigrassm** [comment]
Make sure you're hitting the orange update settings button first before
trying to test. Also retrieve the profiles before hitting update settings
if you haven't done so already.

**Comment by Gamechiefx** [comment]
Hello 
So i clicked the get profiles button
I clicked updated settings then clicked requests
tried to approve several shows and was unable to.
It gave me the same error message shown above in the logs.

for all request it appears this is happening 
I am just trying for myself (admin)
Branch: master
Version: 1.15.0
sonarr Version: 2.0.0.4230

**Comment by lokenx** [comment]
Hmm, I'll have a look where that error is thrown and see what's up. I may create a new branch with some debug output for you to switch to and try so can get some more info from things!

**Comment by Gamechiefx** [comment]
Hello

So i reinstalled meteor and git to see if i could get the error to clear and i am still being presented with the error.

**Comment by rigrassm** [comment]
Try cloning a fresh copy of Plex requests from github,  configure sonarr
and test the requests. I've seen a couple cases where meteor was holding on
to cached code that was causing an error like this.

**Comment by lokenx** [comment]
This was fixed a couple of patch versions ago!
