### ISSUE TITLE
State whether a request needs to be approved in the notification

### ISSUE THREAD

**Issue by speedyflipper** [lokenx/plexrequests-meteor#387]
I currently receive a notification whenever something is requested. I only need to approve TV shows but occasionally I'm not sure if something requested is a TV show or Movie. It would be nice if the notification specified whether the request needs to be approved or not

**Comment by rigrassm** [comment]
You can customize the notification text in settings and use  the <type> tag to include the type(movie or TV show) of media requested.

There are other tags available to help create dynamic notifications. Check out the notifications section of the readme for the full list.
