### ISSUE TITLE
[bug] Can't connect Sick Rage

### ISSUE THREAD

**Issue by CptChaos** [lokenx/plexrequests-meteor#388]
I've secured my Sick Rage install also with a username and password. Plex Requests doesn't have fields for it to add in the settings. I've copy/pasted the API key correctly already and made sure spaces were removed.

**Comment by lokenx** [comment]
It shouldn't make a difference, mine is secured by username/password as well. Have you ensured you've hit save before hitting the test button?

The IP address and port info are correct, in addition to API key? SSL turned on if being used?

**Comment by CptChaos** [comment]
Retried an install on localhost (first attempt wasn't) and it works now.
