### ISSUE TITLE
Links to plex and couch potato go to localhost

### ISSUE THREAD

**Issue by scottwf** [lokenx/plexrequests-meteor#39]
I don't see a place to change this setting and I have it installed on a remoter server so I would have to set up a proxy to connect because when I manually enter the correct url it doesn't let me log into plex.

**Comment by lokenx** [comment]
Can you please explain more fully how you have it setup? What web server is in front of it? Are you running it under `meteor` in development mode, or under nodejs and MongoDB in production style setup?

**Comment by hthighway** [comment]
$ ROOT_URL=http://xxx.xxx.xxx.xxx:3000/ meteor
just enter the remote IP address above
Assuming you are running under development mode, this is what I did for my remote server

**Comment by lokenx** [comment]
Yes setting the ROOT_URL would work as well, it's typically assumed requests are being sent via proxy to Meteor which would replace `localhost:3000` with whatever address it's on

**Comment by scottwf** [comment]
I'm using meteor to run it in screen so I can detach without it shutting down. 
Where would I configure $ROOT_URL?

**Comment by hthighway** [comment]
I run it the same way (in a screen)
Instead of just typing 
   $ meteor
you type  
   $ ROOT_URL=http://xxx.xxx.xxx.xxx:3000/ meteor
instead

**Comment by scottwf** [comment]
Thanks, I got it and the links now point to the correct url, however I still can't login to the plex page with my main plex account. I've put my token in manually, but I still can't log in to the request page with my account name or any others and it doesn't' matter if I set it to try or false in the admin area. I should probably just go back to the master since I don't know what I'm doing on the dev.

**Comment by lokenx** [comment]
Well considering I'm going to merge dev into master tomorrow that wouldn't help!

What does it say specifically? Does the server give any error logs? Are you running a clean install? 

I've found that if people don't update cleanly that can cause problems depending what's changed. Now obviously don't over write your DB (`/plexrequests-meteor/.meteor/local`) but can you give a new install a try? Or even just do it separately and just test that functionality out?

**Comment by lokenx** [comment]
From forums: 

> ...however I think I'll change how the URL get's generated. Right now it's using `Meteor.absoluteUrl()`which get's the variable from `ROOT_URL`. But assuming you're not serving from a sub directory I should be able to get it to work with just a `/plex`. I'll test later and update as needed.

**Comment by lokenx** [comment]
Changed as of b29e1165b047a52b211523c41fe96592fc77eecf, let me know if it works better now
