### ISSUE TITLE
Question: tag series for sharing with requester?

### ISSUE THREAD

**Issue by philipsd6** [lokenx/plexrequests-meteor#390]
I have most series in Plex tagged for sharing with Public. If a new series is added with Plex Requests, that sharing tag is not applied, so it won't show up for the requester. How can I ensure that new series are shared with the Public tag? Can there be some kind of post series creation hook?

**Comment by lokenx** [comment]
You mean within Plex itself you have stuff setup on a per show basis, not on a per library basis? Or is this a Sonarr/SickRage feature?

**Comment by philipsd6** [comment]
Yes, in Plex itself, I use the sharing tags feature on a per show basis.

**Comment by rigrassm** [comment]
This sounds like something that should be handled with your TV download client/Plex. PlexRequests doesn't handle the media itself.

You'll probably need to create a post-process script that'll run after the download client finishes it's work.
