### ISSUE TITLE
"message": "constraint failed\r\nNOT NULL constraint failed: Series.Images"

### ISSUE THREAD

**Issue by supavog** [lokenx/plexrequests-meteor#391]
PlexRequests stopped working for TV Shows with this error:

""message": "constraint failed\r\nNOT NULL constraint failed: Series.Images""

I'm unsure why that would be null unless it's somehow not pulling the images from TVDB or where ever but I could be completely out of the ballpark on what is actually happening.  It's happening with seemingly any TV Show.

**Comment by lokenx** [comment]
Is there anything more to the error message preceding "message"?

**Comment by supavog** [comment]
This is everything showing in the command prompt:

"I20160727-13:14:08.770(-4)? Sonarr Series Post -> failed [409] {
I20160727-13:14:08.770(-4)?    "message": "constraint failed\r\nNOT NULL constraint failed: Series.Images"
I20160727-13:14:08.770(-4)?  }
W20160727-13:14:08.779(-4)? (STDERR) error: Error adding to Sonarr
I20160727-13:22:10.465(-4)?    "message": "constraint failed\r\nNOT NULL constraint failed: Series.Images"
I20160727-13:22:10.465(-4)? Sonarr Series Post -> failed [409] {
I20160727-13:22:10.465(-4)?  }
W20160727-13:22:10.465(-4)? (STDERR) error: Error adding to Sonarr
I20160727-13:23:18.851(-4)? Sonarr Series Post -> failed [409] {
I20160727-13:23:18.851(-4)?    "message": "constraint failed\r\nNOT NULL constraint failed: Series.Images"
I20160727-13:23:18.851(-4)?  }
W20160727-13:23:18.852(-4)? (STDERR) error: Error adding to Sonarr
I20160727-13:36:45.744(-4)? Sonarr Series Post -> failed [409] {
I20160727-13:36:45.744(-4)?    "message": "constraint failed\r\nNOT NULL constraint failed: Series.Images"
I20160727-13:36:45.744(-4)?  }
W20160727-13:36:45.745(-4)? (STDERR) error: Error adding to Sonarr"

**Comment by supavog** [comment]
So another weird thing, is that my Sonarr log shows the following line:

Adding Series [83237][Stargate Universe] Path: [G:\TV Shows\Stargate Universe]

Which is the show that I'm requesting, but then the errors show up in Command Prompt, nothing shows up in Sonarr and that directory is never created.

**Comment by tidusjar** [comment]
See this:
https://github.com/tidusjar/PlexRequests.Net/issues/440

**Comment by lokenx** [comment]
@supavog thanks to @tidusjar digging it appears to be a Sonarr bug which has been opened (https://github.com/Sonarr/Sonarr/issues/1403). Not sure if there's a current fix or when a version will be pushed with a fix, but I'll see if there's a workaround for the moment.

**Comment by tidusjar** [comment]
@lokenx Hey, so a workaround for now is that we can just add the `image` property to the JSON payload as an empty array (Not been fully tested yet, but the Markus said that should fix it). Which makes sense since the DB `null` constraint is no longer violated.
