### ISSUE TITLE
[Feature Request] Setting "Available" after CP/Sonarr adds media to Plex

### ISSUE THREAD

**Issue by ratherDashing** [lokenx/plexrequests-meteor#392]
I've had a bunch of people who stare at the X instead of checking Plex.  I then check Plex, say that it's there and they always ask me why it didn't update the available X.  I then go into the requests tab (which isn't optimal on mobile) and click available.

Any way to update available after it's done importing into Plex?

Thanks for a great product!

**Comment by lokenx** [comment]
We currently check against CouchPotato/Sonarr/SickRage themselves for download status. If it's marked as done in CouchPotato it should update every hour. Just because it's downloaded however doesn't mean that CouchPotato considers it done, that's dependent on your quality profile settings.
