### ISSUE TITLE
Unable to integrate Pushover, receiving "Application token is invalid"

### ISSUE THREAD

**Issue by zprewitt** [lokenx/plexrequests-meteor#394]
Just trying to figure out what more I can do here. I have an API key and a user key and they're both correct.

**Comment by lokenx** [comment]
Are the being used successfully in a different application? No stray spaces at the start or end of the string?

**Comment by bncorbet** [comment]
I am having this same issue. Tried using user API with and without Application API. I receive pushover alerts from others apps all day.

**Comment by bncorbet** [comment]
So I was able to get Pushover notifications to work.  I first enabled Pushover, then pressed Update Settings.  I then updated the User and Application API keys and clicked Update again.  I then did a Test PushOver and it worked.

**Comment by lokenx** [comment]
Weird, thanks for letting us know how you got it working!
