### ISSUE TITLE
[Feature Request] More customization for request limit

### ISSUE THREAD

**Issue by gabo77** [lokenx/plexrequests-meteor#395]
On my setup, I have configured most users with autoapprove where couchpotato sends the torrent to rtorrent, which then downloads it in sequential order. This is great since people can just request and watch it 5 minutes later.

But this can easily get broken if there are too much requests in a short period of time. To solve the issue, the program would only have to be able to set a minimum time frame between two requests. Together with a request limit per day per user, there would be no worries about a request not being downloaded right away or a user abusing the feature.

Is this something that the dev team would consider?
Thanks :)

**Comment by lokenx** [comment]
I'm not 100% sure I understand what you want? Per user limits and per day instead of week limits?

How is having too many requests causing an issue? How many is too many in what period of time? Is it Couch Potato that can't keep up, or you want to throttle how much users can requests?

**Comment by gabo77** [comment]
In my situation, I would like to have limit of one request per user per day. I would also like to have a minimum time gap of one hour between request for any user. Let's say that user A requests a movie at 19h, user B or any other user could not request another movie before 20h, or at least user B's request would not be autoapproved before 20h and he would be informed of that.

Requests are set to auto approved because they go straight to a sequential download that gets instantly added to the Plex library for streaming. If a second request gets added 30 minutes after the first, there are good chances that the user who requested a movie first will not be able to watch it completely without buffering (since he is streaming the movie while it is being downloaded).

So it's not couchpotato that can't keep up, but it is an issue with available downlink bandwidth for downloads. I don't want to throttle in the torrent downloader since I want to keep the "streaming" feature for my Plex users. Implementing this in Plexrequests would also give the possibility of notifying users that their request was not autoapproved right away because another one as been approved not too long before and that it is still being downloaded. We could also notify the user about when their requests would go through (automatically autoapproved) and be available for watching/streaming.

**Comment by rigrassm** [comment]
These examples are things that should be configured on the download client and library manager side of things. Plexrequests shouldn't be used for rate limiting due to bandwidth constraints as this isn't within its scope to properly implement.

Most download clients be it torrents or NZB downloaders have the proper tools necessary for administering systems to conform to these exact scenarios and would be able to do it much more efficiently.

I'm going to close this out as out of scope, I highly recommend looking into y'all's various download clients available configurations (or third party plugins) to resolve these issues.
