### ISSUE TITLE
Can't login as admin unless I'm connecting to localhost:3000/admin

### ISSUE THREAD

**Issue by alexholliz** [lokenx/plexrequests-meteor#396]
I've been wrestling with my nginx proxy all night, everything else for Plexrequests works perfectly over my reverse proxy, but when I try to login to the admin page I just get the error:
Login Forbidden

There's nothing in my nginx error.log, and nothing is logging to the plexrequests error log either. I really don't know where to look.

```
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://0.0.0.0:3000;
    }

    location /admin {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://0.0.0.0:3000/admin;
    }
```

This is my nginx conf, I added the /admin section to test it, but it is still not working.

**Comment by rigrassm** [comment]
Set the proxy pass ip address to 127.0.0.1, remove the /admin location and see if that fixes it. Don't forget to restart Nginx after making the change.

**Comment by alexholliz** [comment]
Nope, still "Login Forbidden"

**Comment by rigrassm** [comment]
Is this a fresh install of plex requests? If so, the first time you go to the admin page you will need to click the register link and fill out the form(Note: this is a seperate login from the one used to login as a user, that login is the one you use to access plex).

**Comment by alexholliz** [comment]
It is fresh, but I registered the admin account from localhost:3000/admin

**Comment by lokenx** [comment]
I can pull up mine later today at home, refer to the wiki config as well.

You definitely shouldn't have a `/admin` entry in nginx though.

https://github.com/lokenx/plexrequests-meteor/wiki/Reverse-Proxy

**Comment by rigrassm** [comment]
As @lokenx said, there's no need for the second directory entry. The first one will handle everything.
