### ISSUE TITLE
Bug when Running Plexrequests Raspberry Pi

### ISSUE THREAD

**Issue by dmeadows013** [lokenx/plexrequests-meteor#397]
Trying to run plexrequests out of my /opt directory on a RP3 running the latest Jessie distro. Followed the install guide exactly, but when I run meteor in the plexrequests directory, I receive this error:

`/home/pi/meteor/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: EACCES, mkdir '/opt/plexrequests/.meteor/local/isopacks'
`

Has anyone run into this or found a fix? Thanks

**Comment by lokenx** [comment]
This seems like a permissions issue as it states in the error message: `Error: EACCES`. It's trying to make a folder `mkdir '/opt/plexrequests/.meteor/local/isopacks'`.

**Comment by rigrassm** [comment]
Gonna close this as its an issue with meteor and system file permissions and not with Plexrequests-meteor.
