### ISSUE TITLE
How do you install the update within Docker

### ISSUE THREAD

**Issue by bncorbet** [lokenx/plexrequests-meteor#400]
I deployed the PR via a docker on my QNAP.  It woks excellent so far, but it is at 1.14.0.  It is telling me there is a new update available, but I can not figure out how to update the application when it is within the docker.

Am I missing something very obvious?

**Comment by lokenx** [comment]
Which docker container? I think if it's the one under my username it's suppose to update on restart? Although I don't use Docker so I could be misspeaking.

**Comment by NathanTheGr8** [comment]
I can confirm the docker container doesn't update on restart. The [base](https://github.com/meteorhacks/meteord) you are doing is doing some magic I don't quite understand. It seems you use method 2.2 from that readme. I will look into why it doesn't update on restart.

**Comment by NathanTheGr8** [comment]
I can't get it to update even on rebuild. I tried purging the mounted mongo database too and it didn't help. @bncorbet did you ever find a way to update? My install is no longer working with sonarr so I am trying to update to the latest.

**Comment by bncorbet** [comment]
I was not able to figure it out.  I am still stuck on 1.14.0.

I also have issue with requesting a TV series if the name does not exactly match in Sonarr, i.e. War and Peace (PlexRequests) but War & Peace (Sonarr).  This request will fail.

Thanks!


Brian Corbet
Senior UC Consultant
CDW – Minneapolis
+1.763.592.5804

**Comment by NathanTheGr8** [comment]
I think my issue is solve by #405 , just really confused that I can get it updated on my sever. I am willing to do a clean install but I don't see what I am doing wrong. when I install plex requests on a different host it gets the most up to date version. So what on my current box am I not doing?

**Comment by rjorgenson** [comment]
You may need to do a docker pull on the image and recreate the container.

**Comment by NathanTheGr8** [comment]
I am an idiot, I forgot to pull the latest image so of course I wasn't updating. @bncorbet try
```
docker pull lokenx/plexrequests-meteor
docker ps
docker rm mongoid plexrequestsid
docker-compose up
```
You will lose your settings but it will update plex requests. In the future now the database is stored on a volume on the host so it shouldn't be an issue.

**Comment by bncorbet** [comment]
Sorry for the noob question, but what am I suppose to do with this command?  Do I need to replace ‘mongoid’ or ‘plexrequestsid’ with something?



docker rm mongoid plexrequestsid

LT-XXXXXXXX:plexrequests-meteor-master BC$ docker rm mongoid plexrequestsid
Error response from daemon: No such container: mongoid
Error response from daemon: No such container: plexrequestsid
LT-XXXXXXXXX:plexrequests-meteor-master BC$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by NathanTheGr8** [comment]
@bncorbet yes sorry I should have been more explicit. Replace mongoid and plexrequests id with the container id you see from docker ps. the id's with look like random characters.

**Comment by lokenx** [comment]
@bncorbet let us know if you're good to go and I'll close this! Thanks for the save @rjorgenson 👍
