### ISSUE TITLE
PlexRequests -> Sonarr - Error adding to Sonarr

### ISSUE THREAD

**Issue by carnivorouz** [lokenx/plexrequests-meteor#405]
Hey Lokenx, looks like this issue started with Sonarr ver. 2.0.0.4323 (now on 2.0.0.4326 as of today's patch).
When a user requests any show they receive "Couldn't submit request, please try again!" at the bottom of PlexRequests and the logs show "Error adding to Sonarr".
What's really peculiar though is in Sonarr I'll have these in the logs:
Component	Message	Time
SeriesService	Adding Series [75978][Family Guy] Path: [/mnt/Media/Shows/Family Guy]	9:42pm

As if it was added just fine.  The series does not show up under Series and no directory created.
Adding shows manually through Sonarr works just fine.
In the .4323 notes there is "Significantly improved api performance." so may have something to do with it.
I've gone through the usual integration checks and everything tests fine from PlexRequests and I do have the download quality profile pulled and saved without issue.

This may be more of a Sonarr issue than a PlexRequests issue but I also figure if they have made API changes it's the PlexRequests side that now has to adjust.

Great service, keep up the good work :)

**Comment by nullenvoid** [comment]
I'm having the same issue. I pulled this out of the Sonarr logs. /api/series/: 409.Conflict (31 ms)

Sonarr ver. 2.0.0.4326
Plex Request ver 1.15.3

This was a brand new installation of PlexRequest on CentOS. 

Thank you!

**Comment by lokenx** [comment]
This is related to https://github.com/Sonarr/Sonarr/issues/1403 , I added the temporary work around, but I think the variable name was `images` not `image` so it should good now once you've updated!

**Comment by carnivorouz** [comment]
Works like a charm. Thanks!
