### ISSUE TITLE
Can't start Mongo server

### ISSUE THREAD

**Issue by fm-techbts** [lokenx/plexrequests-meteor#406]
This started since I updated to Sierra so I'm pretty sure it has something or everything to do with that. Any help is appreciated!

plexrequests-meteor $ meteor
[[[[[ ~/Documents/plexrequests-meteor ]]]]]   

=> Started proxy.  
Unexpected mongo exit code 14. Restarting.  
Unexpected mongo exit code 14. Restarting.  
Unexpected mongo exit code 14. Restarting.  
Unexpected mongo exit code 14. Restarting.  
Unexpected mongo exit code 14. Restarting.  
Can't start Mongo server.  
Unspecified unrecoverable error. Exit was not clean

**Comment by lokenx** [comment]
Have you tried a clean install or a simple Meteor app? I haven't updated yet to Sierra but I'll see if I've a spare SSD to boot into it with.

Use the main tutorial to get a super simple Meteor app going in a few commands: https://www.meteor.com/tutorials/blaze/creating-an-app

**Comment by fm-techbts** [comment]
I have tried a clean install but it didnt work. I should have mentioned that before. I havent tried packaging the app. I will try that today and report back.

**Comment by lokenx** [comment]
I haven't seen any posts on the Meteor side regarding issues with the development mongo server, so maybe worth opening something up there?

**Comment by fm-techbts** [comment]
Created a new directory and created a meteor app as suggested. Installed plexrequests and got this.   

`/Users/justin/.meteor/packages/meteor-tool/.1.4.1_1.1ipppb9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

ReferenceError: SimpleSchema is not defined
    at meteorInstall.lib.collections.collections.js (lib/collections/collections.js:10:18)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at /usr/local/plexrequests-new/.meteor/local/build/programs/server/app/app.js:2931:1
    at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:292:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/justin/.meteor/packages/meteor-tool/.1.4.1_1.1ipppb9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:128:5
Exited with code: 1
Your application is crashing. Waiting for file change.`

**Comment by fm-techbts** [comment]
There is a more complete log in Terminal if you would like that output.

**Comment by lokenx** [comment]
Now it's saying it hasn't installed some dependencies..something seems weird. What's your Meteor version?

Can you run the below to test a demo Meteor app:

```
meteor create simple-todos
cd simple-todos
meteor npm install
meteor
```

**Comment by fm-techbts** [comment]
Meteor 1.4.1.1

```
[[[[[ ~/Documents/simple-todos ]]]]]          

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

**Comment by fm-techbts** [comment]
```
$ meteor update
This project is already at Meteor 1.4.1.1, the latest release.
Your top-level dependencies are at their latest compatible versions.
```

**Comment by lokenx** [comment]
Can you run `meteor update` in the Plex Request installation?

**Comment by fm-techbts** [comment]
Updated all packages in the new plexrequests dir and started the server again, same result. 

```
Your app is crashing. Here's the latest log:
/Users/justin/.meteor/packages/meteor-tool/.1.4.1_1.1ipppb9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

ReferenceError: SimpleSchema is not defined
    at meteorInstall.lib.collections.collections.js (lib/collections/collections.js:10:18)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at /usr/local/plexrequests-new/.meteor/local/build/programs/server/app/app.js:2931:1
    at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:292:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/justin/.meteor/packages/meteor-tool/.1.4.1_1.1ipppb9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:128:5
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by lokenx** [comment]
Can you uninstall and re-install Meteor itself? I'm honestly not sure what's happening 😕

**Comment by fm-techbts** [comment]
How would I uninstall? I dont see a command for it under help.

**Comment by lokenx** [comment]
And its still constantly dying on `SimpleSchema`? Let me do some more searching...

**Comment by rigrassm** [comment]
Have we tested against version 1.4? There may be some changes that are
causing the issue.

**Comment by fm-techbts** [comment]
There is an update to MacOS to 10.12.1, I'll update today and see if it resolves the issue.

**Comment by fm-techbts** [comment]
```
plexrequests-new justin$ meteor
[[[[[ /usr/local/plexrequests-new ]]]]]       

=> Started proxy.                             
=> Started MongoDB.                           
W20160924-12:58:55.453(-5)? (STDERR) /Users/justin/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160924-12:58:56.286(-5)? (STDERR) 						throw(ex);
W20160924-12:58:56.287(-5)? (STDERR) 						^
W20160924-12:58:56.287(-5)? (STDERR) 
W20160924-12:58:56.287(-5)? (STDERR) ReferenceError: SimpleSchema is not defined
W20160924-12:58:56.287(-5)? (STDERR)     at meteorInstall.lib.collections.collections.js (lib/collections/collections.js:10:18)
W20160924-12:58:56.287(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160924-12:58:56.288(-5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160924-12:58:56.288(-5)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/app/app.js:2931:1
W20160924-12:58:56.288(-5)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:292:10
W20160924-12:58:56.289(-5)? (STDERR)     at Array.forEach (native)
W20160924-12:58:56.304(-5)? (STDERR)     at Function._.each._.forEach (/Users/justin/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160924-12:58:56.305(-5)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:128:5
=> Exited with code: 1
W20160924-12:59:00.974(-5)? (STDERR) /Users/justin/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160924-12:59:00.974(-5)? (STDERR) 						throw(ex);
W20160924-12:59:00.974(-5)? (STDERR) 						^
W20160924-12:59:00.975(-5)? (STDERR) 
W20160924-12:59:00.975(-5)? (STDERR) ReferenceError: SimpleSchema is not defined
W20160924-12:59:00.975(-5)? (STDERR)     at meteorInstall.lib.collections.collections.js (lib/collections/collections.js:10:18)
W20160924-12:59:00.975(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160924-12:59:00.975(-5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160924-12:59:00.976(-5)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/app/app.js:2931:1
W20160924-12:59:00.976(-5)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:292:10
W20160924-12:59:00.976(-5)? (STDERR)     at Array.forEach (native)
W20160924-12:59:00.977(-5)? (STDERR)     at Function._.each._.forEach (/Users/justin/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160924-12:59:00.977(-5)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:128:5
=> Exited with code: 1
W20160924-12:59:05.517(-5)? (STDERR) /Users/justin/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160924-12:59:05.518(-5)? (STDERR) 						throw(ex);
W20160924-12:59:05.518(-5)? (STDERR) 						^
W20160924-12:59:05.518(-5)? (STDERR) 
W20160924-12:59:05.519(-5)? (STDERR) ReferenceError: SimpleSchema is not defined
W20160924-12:59:05.519(-5)? (STDERR)     at meteorInstall.lib.collections.collections.js (lib/collections/collections.js:10:18)
W20160924-12:59:05.519(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160924-12:59:05.520(-5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160924-12:59:05.520(-5)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/app/app.js:2931:1
W20160924-12:59:05.520(-5)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:292:10
W20160924-12:59:05.520(-5)? (STDERR)     at Array.forEach (native)
W20160924-12:59:05.520(-5)? (STDERR)     at Function._.each._.forEach (/Users/justin/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160924-12:59:05.521(-5)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:128:5
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
^C
justin:plexrequests-new justin$ 

```

**Comment by fm-techbts** [comment]
Ran Meteor update today and got 1.4.1.2.  but its still crashing on SimpleSchema

**Comment by rigrassm** [comment]
1) Backup your  /path/to/plexrequests-meteor/.meteor/local/db folder by copying it to your home directory.
2) rm -rf meteor, your users .meteor folder then mv the plexrequests app out of the way
3) git clone plexrequests again
4) Reinstall meteor
5) Start plexrequests(don't move the DB folder back yet, start with getting a fresh app up)
6) once the app is running, register the admin email and pass so it'll generate the mongo collections then go to the .meteor/local/db folder and list the contents
7)  Paste the contents of the directory here.

**Comment by fm-techbts** [comment]
Same error on SimpleSchema. Has anyone else tried on Sierra?

**Comment by gjunkie** [comment]
I'm on Sierra as well. I'm attempting to install it on a QNAP server via its Container manager. Ive been getting the same `Exited with code: 1`. Here's the log it spat out:

```
/config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:348
}).run();
   ^

Error: The babel-runtime npm package could not be found in your node_modules 
directory. Please run the following command to install it:

  meteor npm install --save babel-runtime

    at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at require (packages/modules-runtime.js:106:16)
    at packages/babel-runtime.js:139:15
    at packages/babel-runtime.js:150:3
    at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:295:34
    at Array.forEach (native)
    at Function._.each._.forEach (/home/.meteor/packages/meteor-tool/.1.4.2_3.12j2a02++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:128:5
    at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:344:5
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by fm-techbts** [comment]
WQhat happens when you run `meteor npm install --save babel-runtime`

**Comment by gjunkie** [comment]
@fm-techbts I unfortunately have zero console control. I can only run the container or stop it.

**Comment by fm-techbts** [comment]
You should be able to SSH into your server.

**Comment by fm-techbts** [comment]
Anyone else on Sierra yet having issues?

**Comment by c314** [comment]
same problem on Ubuntu 16.04.1 x64

```
root@linux:~/app$ meteor
[[[[[ ~/app ]]]]]

=> Started proxy.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
Can't start Mongo server.
Unspecified unrecoverable error. Exit was not clean
```

**Comment by gjunkie** [comment]
Alright... made some progress.

When I first tried running `meteor npm install --save babel-runtime` it told me Meteor didn't know the `npm` command. So the first thing I had to do was `meteor update`.

Then i tried running `meteor npm install --save babel-runtime`. Had to do it twice, this was the result:
![screen shot 2017-02-01 at 12 21 57 am](https://cloud.githubusercontent.com/assets/626628/22499610/b3719c7c-e814-11e6-998f-dca2a3bd1d25.png)

The app boots up now, but when loading it up I get all kinds of js errors:
![screen shot 2017-02-01 at 12 24 15 am](https://cloud.githubusercontent.com/assets/626628/22499640/dc8642ca-e814-11e6-9dfb-ab8868f22f78.png)

**Comment by rigrassm** [comment]
### System Information
=============================================================
```
┌─[rickygrassmuck@Rickys-Mac-mini]─(~/Development/plexrequests-meteor)
└─[02:42]$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
```
=============================================================
###  Plexrequests-meteor application information
=============================================================
```
┌─[rickygrassmuck@Rickys-Mac-mini]─(~/Development/plexrequests-meteor)
└─[02:42]$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```
=============================================================
### Initial Meteor version
=============================================================
```
┌─[rickygrassmuck@Rickys-Mac-mini]─(~/Development/plexrequests-meteor)
└─[02:44]$ meteor --version
Meteor 1.2.1
```
=============================================================


### Running Plexrequests-meteor on MacOS Sierra 10.12

**From the applications base directory, I ran:**
```
┌─[rickygrassmuck@Rickys-Mac-mini]─(~/Development/plexrequests-meteor)
└─[02:46]$ meteor update
```

**This updated the application to use meteor 1.4.2.3**
```
┌─[rickygrassmuck@Rickys-Mac-mini]─(~/Development/plexrequests-meteor)
└─[02:59]$ meteor --version
Meteor 1.4.2.3
```

**Then I installed the babel-runtime npm per the error message given if you try to run it immediately following the update**
```
┌─[rickygrassmuck@Rickys-Mac-mini]─(~/Development/plexrequests-meteor)
└─[02:50]$ meteor npm install --save babel-runtime
npm WARN saveError ENOENT: no such file or directory, open '/Users/rickygrassmuck/Development/plexrequests-meteor/package.json'
/Users/rickygrassmuck/Development/plexrequests-meteor
└─┬ babel-runtime@6.22.0
  ├── core-js@2.4.1
  └── regenerator-runtime@0.10.1

npm WARN enoent ENOENT: no such file or directory, open '/Users/rickygrassmuck/Development/plexrequests-meteor/package.json'
npm WARN plexrequests-meteor No description
npm WARN plexrequests-meteor No repository field.
npm WARN plexrequests-meteor No README data
npm WARN plexrequests-meteor No license field.
```

**Finally, to increase the speed of the bcrypt library(recommended by meteor), I installed the native implementation of bcrypt using meteor npm install as well.**
```
┌─[rickygrassmuck@Rickys-Mac-mini]─(~/Development/plexrequests-meteor)
└─[02:51]$ meteor npm install --save bcrypt

> bcrypt@1.0.2 install /Users/rickygrassmuck/Development/plexrequests-meteor/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.6.2 (node-v46 ABI) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
  COPY /Users/rickygrassmuck/Development/plexrequests-meteor/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
npm WARN saveError ENOENT: no such file or directory, open '/Users/rickygrassmuck/Development/plexrequests-meteor/package.json'
/Users/rickygrassmuck/Development/plexrequests-meteor
└─┬ bcrypt@1.0.2
  ├── bindings@1.2.1
  ├── nan@2.5.0
  └─┬ node-pre-gyp@0.6.32
    ├─┬ mkdirp@0.5.1
    │ └── minimist@0.0.8
    ├─┬ nopt@3.0.6
    │ └── abbrev@1.0.9
    ├─┬ npmlog@4.0.2
    │ ├─┬ are-we-there-yet@1.1.2
    │ │ ├── delegates@1.0.0
    │ │ └── readable-stream@2.2.2
    │ ├── console-control-strings@1.1.0
    │ ├─┬ gauge@2.7.2
    │ │ ├── aproba@1.0.4
    │ │ ├── has-unicode@2.0.1
    │ │ ├── object-assign@4.1.1
    │ │ ├── signal-exit@3.0.2
    │ │ ├─┬ string-width@1.0.2
    │ │ │ ├── code-point-at@1.1.0
    │ │ │ └─┬ is-fullwidth-code-point@1.0.0
    │ │ │   └── number-is-nan@1.0.1
    │ │ ├─┬ strip-ansi@3.0.1
    │ │ │ └── ansi-regex@2.1.1
    │ │ ├── supports-color@0.2.0
    │ │ └── wide-align@1.1.0
    │ └── set-blocking@2.0.0
    ├─┬ rc@1.1.6
    │ ├── deep-extend@0.4.1
    │ ├── ini@1.3.4
    │ ├── minimist@1.2.0
    │ └── strip-json-comments@1.0.4
    ├─┬ request@2.79.0
    │ ├── aws-sign2@0.6.0
    │ ├── aws4@1.5.0
    │ ├── caseless@0.11.0
    │ ├─┬ combined-stream@1.0.5
    │ │ └── delayed-stream@1.0.0
    │ ├── extend@3.0.0
    │ ├── forever-agent@0.6.1
    │ ├─┬ form-data@2.1.2
    │ │ └── asynckit@0.4.0
    │ ├─┬ har-validator@2.0.6
    │ │ ├─┬ chalk@1.1.3
    │ │ │ ├── ansi-styles@2.2.1
    │ │ │ ├── escape-string-regexp@1.0.5
    │ │ │ ├── has-ansi@2.0.0
    │ │ │ └── supports-color@2.0.0
    │ │ ├─┬ commander@2.9.0
    │ │ │ └── graceful-readlink@1.0.1
    │ │ ├─┬ is-my-json-valid@2.15.0
    │ │ │ ├── generate-function@2.0.0
    │ │ │ ├─┬ generate-object-property@1.2.0
    │ │ │ │ └── is-property@1.0.2
    │ │ │ ├── jsonpointer@4.0.1
    │ │ │ └── xtend@4.0.1
    │ │ └─┬ pinkie-promise@2.0.1
    │ │   └── pinkie@2.0.4
    │ ├─┬ hawk@3.1.3
    │ │ ├── boom@2.10.1
    │ │ ├── cryptiles@2.0.5
    │ │ ├── hoek@2.16.3
    │ │ └── sntp@1.0.9
    │ ├─┬ http-signature@1.1.1
    │ │ ├── assert-plus@0.2.0
    │ │ ├─┬ jsprim@1.3.1
    │ │ │ ├── extsprintf@1.0.2
    │ │ │ ├── json-schema@0.2.3
    │ │ │ └── verror@1.3.6
    │ │ └─┬ sshpk@1.10.2
    │ │   ├── asn1@0.2.3
    │ │   ├── assert-plus@1.0.0
    │ │   ├── bcrypt-pbkdf@1.0.0
    │ │   ├─┬ dashdash@1.14.1
    │ │   │ └── assert-plus@1.0.0
    │ │   ├── ecc-jsbn@0.1.1
    │ │   ├─┬ getpass@0.1.6
    │ │   │ └── assert-plus@1.0.0
    │ │   ├── jodid25519@1.0.2
    │ │   ├── jsbn@0.1.0
    │ │   └── tweetnacl@0.14.5
    │ ├── is-typedarray@1.0.0
    │ ├── isstream@0.1.2
    │ ├── json-stringify-safe@5.0.1
    │ ├─┬ mime-types@2.1.14
    │ │ └── mime-db@1.26.0
    │ ├── oauth-sign@0.8.2
    │ ├── qs@6.3.0
    │ ├── stringstream@0.0.5
    │ ├─┬ tough-cookie@2.3.2
    │ │ └── punycode@1.4.1
    │ ├── tunnel-agent@0.4.3
    │ └── uuid@3.0.1
    ├─┬ rimraf@2.5.4
    │ └─┬ glob@7.1.1
    │   ├── fs.realpath@1.0.0
    │   ├── inflight@1.0.6
    │   ├─┬ minimatch@3.0.3
    │   │ └─┬ brace-expansion@1.1.6
    │   │   ├── balanced-match@0.4.2
    │   │   └── concat-map@0.0.1
    │   ├── once@1.4.0
    │   └── path-is-absolute@1.0.1
    ├── semver@5.3.0
    ├─┬ tar@2.2.1
    │ ├── block-stream@0.0.9
    │ ├─┬ fstream@1.0.10
    │ │ └── graceful-fs@4.1.11
    │ └── inherits@2.0.3
    └─┬ tar-pack@3.3.0
      ├─┬ debug@2.2.0
      │ └── ms@0.7.1
      ├── fstream-ignore@1.0.5
      ├─┬ once@1.3.3
      │ └── wrappy@1.0.2
      ├─┬ readable-stream@2.1.5
      │ ├── buffer-shims@1.0.0
      │ ├── core-util-is@1.0.2
      │ ├── isarray@1.0.0
      │ ├── process-nextick-args@1.0.7
      │ ├── string_decoder@0.10.31
      │ └── util-deprecate@1.0.2
      └── uid-number@0.0.6

npm WARN enoent ENOENT: no such file or directory, open '/Users/rickygrassmuck/Development/plexrequests-meteor/package.json'
npm WARN plexrequests-meteor No description
npm WARN plexrequests-meteor No repository field.
npm WARN plexrequests-meteor No README data
npm WARN plexrequests-meteor No license field.
```

**After following those steps, I was able to run meteor without any issue.**
```
┌─[rickygrassmuck@Rickys-Mac-mini]─(~/Development/plexrequests-meteor)
└─[02:51]$ meteor --production run
Warning: The --production flag should only be used to simulate production bundling for testing purposes. Use meteor build to create
a bundle for production deployment. See: https://guide.meteor.com/deployment.html
[[[[[ ~/Development/plexrequests-meteor ]]]]]

=> Started proxy.
=> Started MongoDB.
I20170201-02:56:53.320(-6)? No change detected for the collection tv
I20170201-02:56:53.366(-6)? No change detected for the collection movies
I20170201-02:56:53.367(-6)? No change detected for the collection settings
I20170201-02:56:53.367(-6)? No change detected for the collection permissions
=> Started your app.

=> App running at: http://localhost:3000/
```

I'm not quite sure why your system is having issues as it appears to run just fine provided you take the extra step of installing babel-runtime with npm after updating.

**Comment by fm-techbts** [comment]
I actually tried that a couple days ago myself with no success. Tonight I wiped out meteor again and installed to a new directory and then updated babel as well and I got the same error. 

`ustin:local justin$ cd plexrequests-new/
justin:plexrequests-new justin$ meteor npm install babel-runtime
plexrequests-new@ /usr/local/plexrequests-new
└─┬ babel-runtime@6.22.0 
  ├── core-js@2.4.1 
  └── regenerator-runtime@0.10.1 

justin:plexrequests-new justin$ meteor npm install --save babel-runtime
plexrequests-new@ /usr/local/plexrequests-new
└── babel-runtime@6.22.0 

justin:plexrequests-new justin$ meteor
[[[[[ /usr/local/plexrequests-new ]]]]]       

=> Started proxy.                             
=> Started MongoDB.                           
W20170201-20:22:57.179(-6)? (STDERR) /Users/justin/.meteor/packages/meteor-tool/.1.4.2_3.1q8jn29++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170201-20:22:57.343(-6)? (STDERR) 						throw(ex);
W20170201-20:22:57.343(-6)? (STDERR) 						^
W20170201-20:22:57.343(-6)? (STDERR) 
W20170201-20:22:57.343(-6)? (STDERR) ReferenceError: SimpleSchema is not defined
W20170201-20:22:57.344(-6)? (STDERR)     at meteorInstall.lib.collections.collections.js (lib/collections/collections.js:10:18)
W20170201-20:22:57.344(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170201-20:22:57.345(-6)? (STDERR)     at require (packages/modules-runtime.js:111:16)
W20170201-20:22:57.346(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/app/app.js:3203:1
W20170201-20:22:57.346(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:295:34
W20170201-20:22:57.346(-6)? (STDERR)     at Array.forEach (native)
W20170201-20:22:57.346(-6)? (STDERR)     at Function._.each._.forEach (/Users/justin/.meteor/packages/meteor-tool/.1.4.2_3.1q8jn29++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170201-20:22:57.346(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:128:5
W20170201-20:22:57.347(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:344:5
W20170201-20:22:57.347(-6)? (STDERR)     at Function.run (/usr/local/plexrequests-new/.meteor/local/build/programs/server/profile.js:480:12)
=> Exited with code: 1
W20170201-20:22:58.844(-6)? (STDERR) /Users/justin/.meteor/packages/meteor-tool/.1.4.2_3.1q8jn29++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170201-20:22:58.845(-6)? (STDERR) 						throw(ex);
W20170201-20:22:58.845(-6)? (STDERR) 						^
W20170201-20:22:58.845(-6)? (STDERR) 
W20170201-20:22:58.846(-6)? (STDERR) ReferenceError: SimpleSchema is not defined
W20170201-20:22:58.846(-6)? (STDERR)     at meteorInstall.lib.collections.collections.js (lib/collections/collections.js:10:18)
W20170201-20:22:58.846(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170201-20:22:58.847(-6)? (STDERR)     at require (packages/modules-runtime.js:111:16)
W20170201-20:22:58.847(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/app/app.js:3203:1
W20170201-20:22:58.847(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:295:34
W20170201-20:22:58.848(-6)? (STDERR)     at Array.forEach (native)
W20170201-20:22:58.848(-6)? (STDERR)     at Function._.each._.forEach (/Users/justin/.meteor/packages/meteor-tool/.1.4.2_3.1q8jn29++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170201-20:22:58.849(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:128:5
W20170201-20:22:58.849(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:344:5
W20170201-20:22:58.849(-6)? (STDERR)     at Function.run (/usr/local/plexrequests-new/.meteor/local/build/programs/server/profile.js:480:12)
=> Exited with code: 1
W20170201-20:23:00.416(-6)? (STDERR) /Users/justin/.meteor/packages/meteor-tool/.1.4.2_3.1q8jn29++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170201-20:23:00.417(-6)? (STDERR) 						throw(ex);
W20170201-20:23:00.417(-6)? (STDERR) 						^
W20170201-20:23:00.417(-6)? (STDERR) 
W20170201-20:23:00.418(-6)? (STDERR) ReferenceError: SimpleSchema is not defined
W20170201-20:23:00.418(-6)? (STDERR)     at meteorInstall.lib.collections.collections.js (lib/collections/collections.js:10:18)
W20170201-20:23:00.418(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170201-20:23:00.418(-6)? (STDERR)     at require (packages/modules-runtime.js:111:16)
W20170201-20:23:00.419(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/app/app.js:3203:1
W20170201-20:23:00.419(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:295:34
W20170201-20:23:00.419(-6)? (STDERR)     at Array.forEach (native)
W20170201-20:23:00.419(-6)? (STDERR)     at Function._.each._.forEach (/Users/justin/.meteor/packages/meteor-tool/.1.4.2_3.1q8jn29++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170201-20:23:00.420(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:128:5
W20170201-20:23:00.420(-6)? (STDERR)     at /usr/local/plexrequests-new/.meteor/local/build/programs/server/boot.js:344:5
W20170201-20:23:00.420(-6)? (STDERR)     at Function.run (/usr/local/plexrequests-new/.meteor/local/build/programs/server/profile.js:480:12)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.`

**Comment by fm-techbts** [comment]
No idea why its working now, just blew out the directory and recloned from the repo and bam. 

![screenshot_90](https://cloud.githubusercontent.com/assets/5819204/22614173/b01c2588-ea44-11e6-90d7-269d4fcb58ba.png)
