### ISSUE TITLE
Blank page in some browsers

### ISSUE THREAD

**Issue by sharepointalex** [lokenx/plexrequests-meteor#409]
Running the latest version from Master branch. Noticed recently that on my iPhone on IOS10, the plex requests page does not render and stays blank.

Also tried it in the latest version of Chrome and the same issue.

Seems to render only in IE at the moment.

Has this already been reported and fixed in another branch?

![image](https://cloud.githubusercontent.com/assets/12395485/19042333/7dfcce62-8983-11e6-9373-27ca9bb262f0.png)

**Comment by lokenx** [comment]
Well that's not good... Have you restarted the server? What version you on? Any console error messages? Normally it's IE that isn't working...

**Comment by sharepointalex** [comment]
Restarted the server, i'm running it as a windows service but tried running directly from cmd prompt and running meteor with the same result. I believe i'm on 1.1.1 but clicking the 'About' page in the admin area just redirects me back to the requests area - very strange! Can I backup the db? Then i'll try grabbing from git again.

**Comment by sharepointalex** [comment]
Just switched to latest dev branch version and it's still knackered :-(

**Comment by lokenx** [comment]
Don't use the dev branch! Why aren't you on the master branch?

The dev is still on `1.7.2` while master is up to `1.15.5`!

**Comment by sharepointalex** [comment]
Ok so I deleted all files and cloned again from GIT and all is well. Switched back to Master branch btw :-)

I backed up my db folder before but if I restore that folder the database doesn't restore - can I get it back??

**Comment by lokenx** [comment]
I believe the database is saved in `.meteor/local/db`, if you've the old installation can copy the contents of that folder into the new one (delete old one first).

**Comment by lokenx** [comment]
Let me know if still need help with this and we can re-open!
