### ISSUE TITLE
Auto start plexrequest on OSX

### ISSUE THREAD

**Issue by MartinMeel** [lokenx/plexrequests-meteor#410]
Hi all,

I'm be able to have this beautiful piece of software working on my mac.
As a fact it was pretty simple for me to install it using the many sites which explained me how to get it working. And i'm not even a developer ;-)
But.... unfortunately i did not find any site that gives me an example of how i can create a service/deamon or whatever you call it to create an automatic startup file that starts plexrequest as soon as i login to my mac.

Is there somebody who managed to do this? And would you share the code or perhaps the file(s) which does the job?

Thanks in advance.

**Comment by TSPARR** [comment]
What you're looking for is called a LaunchAgent. Create a file called com.lokenx.plexrequests.plist in the folder ~/Library/LaunchAgents. The file's contents should be the same as below though you may need to change the Working Directory if you installed PlexRequests somewhere else.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.lokenx.plexrequests</string>
	<key>Program</key>
	<string>/usr/local/bin/meteor</string>
	<key>RunAtLoad</key>
	<true/>
	<key>WorkingDirectory</key>
	<string>/Applications/PlexRequests/</string>
</dict>
</plist>
```

**Comment by MartinMeel** [comment]
Hi TSPARR,

Thank you so much. This one did the job. 
I also found out that i should run the command  " launchctl load ~/Library/LaunchAgents/com.lokenx.pleqrequests.plist " in Terminal to have it load. I'm not sure if this is necessary, but on my Mac it works finaly.

Thanks for helping me out with tis ;-)
