### ISSUE TITLE
[Request] Telegram notificator integration

### ISSUE THREAD

**Issue by WzL** [lokenx/plexrequests-meteor#412]
First off, i really love PlexRequest, it works like a charm and is used often here by several users. Feedback from them is very positive, userfriendly interface, works as expected! Additionally, when possible, I would like to have the [telegram ](https://telegram.org/) notifier added to PlexRequest. Currently other apps have Telegram notification Support included like SickRage,CouchPotato, AutoSub and also PlexPy. I would love to see Telegram notificator included which sends a notification when new content is requested using PlexRequest.
Telegram is very open about their messaging platform (API's, sourcecode etc) and supports/offer loads of frameworks / library's.

**Comment by lokenx** [comment]
I'm actually looking at Telegram right now, I'm just having issues wrapping my head around how it works as it's different than Pushbullet and Pushover. Everything seems to be revolving around chat rooms and bots of some of kind. I do want to try and integrate it--I'm travelling all of October for conferences but once things settle down I'll take another stab and figuring how it works.

**Comment by WzL** [comment]
I requested the same feature to AutoSub and the author replyed that the api documentation was not that clear from Telegram orligional documentation and that he eventually looked at the Telegram integration code of SickRage at github and he basically said from that moment it was immediately clear that is was super simple and AutoSub - Telegram client integration was implemented in no time. So maybe that can be a shortcut in this case also?! if testing needs to be done i am available.

**Comment by lokenx** [comment]
OK cool thanks, I'll take a look at it this week! This weekend is set aside to get my Plex environment re-setup so I'd like to move away from Pushbullet personally too.

**Comment by DoublePlusGood23** [comment]
Any progress on this? 
It would be great to get a notification this way.

**Comment by jasperrooduijn** [comment]
It would be really great to have this feature. Ik use Telegram for all notifications on my htpc!

**Comment by AncientVale** [comment]
I would definitely be interested in seeing this to match it up with SickRage and Radarr.

**Comment by jasii** [comment]
Any updates on this? I would love to have Telegram notifications.

**Comment by JagandeepBrar** [comment]
I have added support for Telegram, and created a pull request: #497.

**Comment by bilyboy785** [comment]
Notifications with Telegram doesn't work on linuxserver/plexrequest docker image ..
