### ISSUE TITLE
Requests list using incorrect URL for posters

### ISSUE THREAD

**Issue by Cheezykins** [lokenx/plexrequests-meteor#413]
For some reason posters are getting an incorrect URL for most movies.

Most TV shows fine but for movies I'm seeing tags like:

```html
<img src="https://image.tmdb.org/t/p/w154https://image.tmdb.org/t/p/w154/mYZdcd5XeZkye72oQejkLuAGI7q.jpg" class="img-responsive" alt="Poster">
```

When the src should clearly be https://image.tmdb.org/t/p/w154/mYZdcd5XeZkye72oQejkLuAGI7q.jpg

Weirdly some work, for instance

```html
<img src="https://image.tmdb.org/t/p/w154https://image.tmdb.org/t/p/w154/fSCSAv0K3RatZgvQhk9l1nP6wPo.jpg" class="img-responsive" alt="Poster">
```
![Example poster working](https://image.tmdb.org/t/p/w154https://image.tmdb.org/t/p/w154/fSCSAv0K3RatZgvQhk9l1nP6wPo.jpg)

**Comment by rjorgenson** [comment]
I am also experiencing this issue with movies.

**Comment by rigrassm** [comment]
Is that on the search page, requests or both?

**Comment by rjorgenson** [comment]
@rigrassm This only happens for me on the Requests page. The search results show up with their artwork.

**Comment by rigrassm** [comment]
Not sure why it waited to pop up now since the links have been generating incorrectly for a while now but I just committed the fix. Should just need to git pull but It may require a restarting the service.
