### ISSUE TITLE
Error Adding to Sonarr

### ISSUE THREAD

**Issue by kfulgham** [lokenx/plexrequests-meteor#414]
Most of my users have issues with making requests. Sometimes they have to click the request button twice. Others it completely fails. This is my log right now:

`error  Error adding to Sonarr  2016/10/28 10:04:01
error   Error adding to Sonarr  2016/10/28 10:03:10
error   Error adding to Sonarr  2016/10/28 10:01:35
error   Error adding to Sonarr  2016/10/28 10:01:16
error   Error adding to Sonarr  2016/10/28 10:00:45
error   Error adding to Sonarr  2016/10/28 10:00:32
error   Error adding to Sonarr  2016/10/28 10:00:24
error   Error adding to Sonarr  2016/10/28 10:00:17`

**Comment by rigrassm** [comment]
Can you go and do a test connection to see if it's even able to connect and get a response?

Also, check sonarrs logs to see if it's giving you any error messages there as well.

**Comment by kfulgham** [comment]
Yup. It came back with "Success".

I don't see anything in the Sonarr Logs with a matching time.

**Comment by Brandon-short** [comment]
Hey kfulgham, I was running into a similar issue and was able to resolve it by updating plexrequests

**Comment by kfulgham** [comment]
Thanks. I'm confused because I'm apparently on the latest release, but it's also showing that there is an update available. I'll give it another update.

**Comment by cmilam87** [comment]
I am having the same issue. However when I try to add a TV Show, Sonarr says its adding the series, but PlexRequests logs error adding to Sonarr. The series never gets added though.

From Sonarr:
`SeriesService	Adding Series [302938][LetterKenny] Path: [E:\TV Shows\LetterKenny]	10:39am`

From PlexRequests:
`error	Error adding to Sonarr	2016/12/16 10:41:58`

**Comment by Brandon-short** [comment]
What branch and version are you on and if you test the sonarr connection is it successful? Have you tried rebooting the sonarr and plex requests servers?

**Comment by cmilam87** [comment]
Running master branch, says version 1.9.0 but below the version number is different. 1.15.6
![image](https://cloud.githubusercontent.com/assets/627555/21321873/abc7cd22-c5e4-11e6-9681-123ca3a9177d.png)

Sonarr version is 2.0.0.4427

If I test the connection on PlexRequests to Sonarr I get a success message.
I have rebooted both Sonarr and PlexRequests and I still have the issue .

**Comment by rigrassm** [comment]
That version number is not right, the version number is hard coded and is currently set to 1.15.6. 

You may want to back up your DB files and pull down a fresh copy from git add see if that fixes things for you.

**Comment by cmilam87** [comment]
That seems to have fixed it. That was odd. I had been using the update feature regularly. Not sure why it wasn't updating properly.

**Comment by rigrassm** [comment]
Yeah, not sure what happened there. Gonna close this out but let us know if you run into the issue again.
