### ISSUE TITLE
unable to load image on requests

### ISSUE THREAD

**Issue by dualznz** [lokenx/plexrequests-meteor#415]
Hi 
I have found this small bug where on the Requests page alot of the images fail to load, you get a 404 when you open image in new tab.

this is what the address of one of the requests i trying to locate
https://image.tmdb.org/t/p/w154https://image.tmdb.org/t/p/w154/7SMCz5724COOYDhY0mj0NfcJqxH.jpg
this part here should not be in the image https://image.tmdb.org/t/p/w154

the actual image url is: https://image.tmdb.org/t/p/w154/7SMCz5724COOYDhY0mj0NfcJqxH.jpg

**Comment by rigrassm** [comment]
Just fixed this issue with 1.5.6, update Plexrequests and all will be good.

**Comment by dualznz** [comment]
ahh ok sweet will do cheers
