### ISSUE TITLE
[Request] Generic output RSS, XML, Flat file for other integrations

### ISSUE THREAD

**Issue by bagobones** [lokenx/plexrequests-meteor#416]
Instead of specific integration a standing RSS feed or file with one line per outstanding request would make for easy integration with other clients / scripts that support RSS or tools that can process lists. The RSS feed would also be handy for monitoring the current list for the admin.

**Comment by jmacul2** [comment]
I second this!  ;)

**Comment by rigrassm** [comment]
Got quite a few things that would be ahead of this and I'm not sure if it is something that will be implemented but I will look into it after I've gotten some higher priority things fixed and finished.

**Comment by bagobones** [comment]
Is there work being done to provide anything like a library or API for other apps to integrate? In an essence Plex requests creates a list with some meta-data that would be nice to consume in other applications.
