### ISSUE TITLE
Headphones looking for none - none instead of my request

### ISSUE THREAD

**Issue by castanza128** [lokenx/plexrequests-meteor#418]
I'm having a problem adding albums to headphones with plexrequests.
All my settings seem to be right, api is right, test works.
I have it set to require admin approval for Tv shows, but not movies or music.
When an album is requested, it shows "requested" like it worked......but in headphones logs I see this:
2016-11-26 21:33:42	INFO	Searching for "None - None" since it was marked as wanted
2016-11-26 21:33:42	INFO	Searching for wanted albums
2016-11-26 21:33:42	INFO	Recieved API command: queueAlbum
It repeats this over and over again, every 2 seconds, filling up my logs. (not to mention wasting cpu cycles and everything else)
It won't stop, unless I go into "Wanted" and delete artist "none" and of course, their newest album: "none"
Any ideas?

**Comment by castanza128** [comment]
BTW: Using newest rogueosb Unraid docker, "linuxserver" headphones docker.
Updating to the newest version of headphones released a few days ago didn't help.
Main forks of both.
Anything else you need to know, I'll be happy to provide info/logs

**Comment by lokenx** [comment]
I think you're looking for Jamie's fork!

https://github.com/tidusjar/PlexRequests.Net
