### ISSUE TITLE
couchpotato api key

### ISSUE THREAD

**Issue by konsumer** [lokenx/plexrequests-meteor#419]
I can't connect to couchpotato because it doesn't appear to use an API key, and it fails when I leave it blank (with all other settings correct.)

Here is what my couchpotato settings/general looks like:

![screen shot 2016-11-27 at 1 00 06 am](https://cloud.githubusercontent.com/assets/83857/20647002/eb36998e-b43c-11e6-8ad2-59be5e73a2f0.png)

**Comment by rigrassm** [comment]
Click show advanced in the CP general section and you'll see your API key.

**Comment by konsumer** [comment]
I don't.
![screen shot 2016-11-27 at 1 08 35 am](https://cloud.githubusercontent.com/assets/83857/20647036/145c907e-b43e-11e6-8c6e-42731a53edfb.png)

**Comment by konsumer** [comment]
(this is with the latest update)

**Comment by konsumer** [comment]
Oh! I found it. It was all muted. Weird UI choice. Thanks!

**Comment by rigrassm** [comment]
Yes you do, it's right between "Bookmarklet Host" and "Use Proxy"...

**Comment by lokenx** [comment]
I sometimes click the `Docs` link as it'll show you the API key. And yeah the dark theme is hard to read sometimes!
