### ISSUE TITLE
Show's Available: 0/0

### ISSUE THREAD

**Issue by Dgameman1** [lokenx/plexrequests-meteor#422]
Hey guys, when I look under requests in PlexRequests, I see that one of the accepted Requests shows

> Available: 0 / 0

I have them downloaded it manually and it's even showing up on Sonarr and Plex.

Any ideas?

#### Plex Requests.Net Version:
Branch: master
Version: 1.15.6

#### Operating System:
Ubuntu Server 16.04.1 LTS

#### Mono Version:
```
:~$ mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

#### Reproduction Steps:

Have a user request the walking dead and then approve it and manually download it from Sonarr

**Comment by Dgameman1** [comment]
Lol well then

**Comment by lokenx** [comment]
You're looking for Jamie's fork that's just been renamed!

https://github.com/tidusjar/Ombi
