### ISSUE TITLE
[Request] Radarr Integration

### ISSUE THREAD

**Issue by JoeStratton** [lokenx/plexrequests-meteor#428]
This would be a great addition as it becomes more stable https://github.com/Radarr/Radarr

**Comment by tidusjar** [comment]
Just to let you guys know, the Radarr API is very similar to Sonarr. 

I added it into my version ([Ombi](https://github.com/tidusjar/Ombi)) very quickly because of this!

**Comment by jasperrooduijn** [comment]
Would be great to have this feature. I'm using Radarr as a replament for couchpotato after being a very happy Sonarr user for a while.

**Comment by rigrassm** [comment]
@tidusjar are there any docs on their API endpoints?

**Comment by rigrassm** [comment]
Started working on Radarr integration at work tonight and have it most of
the way there. Still gotta work out some minor kinks but should have a
branch pushed out to test in the next couple days.

**Comment by rigrassm** [comment]
Went ahead and pushed my current commits to a new branch [add-radarr-support](https://github.com/lokenx/plexrequests-meteor/tree/add-radarr-support).

Keep in mind this is not ready for use and has a few bugs I need to work out. Once I have it in usable shape I'll merge  it withe the develop branch for testing.

**Comment by rigrassm** [comment]
Ok, so pull request #434 merged Radarr integration into the new [dev-testing](https://github.com/lokenx/plexrequests-meteor/tree/dev-testing) branch and is ready to be field tested. I was only able to do some cursory testing as I don't use Radarr(yet!) but please be sure to file issue reports for anything that you find.

**Comment by tidusjar** [comment]
@rigrassm Sorry didn't see the notification, there was no documentation when I implemented it, but I think there is now.

**Comment by rigrassm** [comment]
@tidusjar No worries, I was able to wing it and get things going. Now just need to get some testers to make sure I got everything covered and we'll be good to go!

For everyone else, I mentioned before that I created a dev-testing branch that you could pull from. After my latest round of commits I decided to go ahead and through out a [pre-release](https://github.com/lokenx/plexrequests-meteor/releases/tag/v1.20.0-dev.1) as well which is based on pull request #435.

Please test if you are able to, I only have a docker container running on my workstation at the moment to test against so I really need some feedback from real world usage.

**Comment by zerrikan** [comment]
I'm using the Docker container in Unraid by linuxserver.io. Is there a way to switch branches so that I can test this?

**Comment by rigrassm** [comment]
I submitted a request to the Linux Server IO to have them add the ability
to specify the dev-testing branch as a tag but haven't heard back on that
yet.

**Comment by rigrassm** [comment]
I went ahead and merged dev-testing into master a few hours ago so Radarr support is now there. For details see pull requests #443.

**Comment by rigrassm** [comment]
Closing this as fulfilled. Any new issues should be opened in separate issue reports.
