### ISSUE TITLE
[REQUEST] Chrome Extension

### ISSUE THREAD

**Issue by hthighway** [lokenx/plexrequests-meteor#43]
Create a Chrome Extension/Button that transfers the search term field from plex.tv/web to "Plex Request".   

When a user is searching plex for a movie, and the search comes up empty the user can click a button on the browser that sends the "search term" used to "Plex Request"

SAMPLE PLEX URL: http://plex/tv/we/app#!/search/some%20search%20term

**Comment by hthighway** [comment]
Create one as a test locally;
modified "/client/templates/search.html" by inserting a javascript routine at the top
When the "Chrome button" is clicked whatever is entered into the search box inside of plex.tv/web is passed to "Plex Request:

---------------- search.html -----------------
var urlParams;
(window.onpopstate = function () {
    var match,
        pl     = /\+/g,  // Regex for replacing addition symbol with a space
        search = /([^&=]+)=?([^&]*)/g,
        decode = function (s) { return decodeURIComponent(s.replace(pl, " ")); },
        query  = window.location.search.substring(1);

    urlParams = {};
    while (match = search.exec(query))
       urlParams[decode(match[1])] = decode(match[2]);
})();
if(urlParams)
{
   var elem = document.getElementById("search");
  elem.value = urlParams["search"];
}



------------------- manifest.json  ---------------
{
   "background": { "scripts": ["background.js"] },
  "browser_action": {
      "default_icon": "icon16.png",
      "default_title": "Add to Plex Request"
   },
    
  "permissions": [ "activeTab" ],  // should restrict to only working when http://plex.tv/web is present

  "manifest_version": 2,
  "name": "Send to Plex Request",
  "description": "This extension passes the search string from plex.tv to Plex Request",
  "version": "0.1",
  "icons": { "16": "icon16.png"}
 }


------------------- background.js  --------------
chrome.browserAction.onClicked.addListener(function(tab){
    var my_url = tab.url;
    var url_split = my_url.split("/");
	var baseurl = "http://37.48.65.123:3000";   // probably need to create an option in the extension for the user to input this URL
	var newURL = baseurl + "?search=" + url_split[6];
  
  chrome.tabs.create({ url: newURL });
});

**Comment by lokenx** [comment]
I don't know much about how chrome extensions work but why is anything needed in the search html? Wouldn't the extension pull the search query from Plex.tv and insert it into the search field? Also what if someone isn't logged into Plex Requests?

Also should put all the code in code highlighting so its easier to follow!

**Comment by hthighway** [comment]
Regarding the search.html insert, I'm sure there's a better way this is just what I thought came upwith on the fly
