### ISSUE TITLE
Not able to deploy PlexRequests

### ISSUE THREAD

**Issue by duramato** [lokenx/plexrequests-meteor#436]
After trying to install PlexRequests on a new machine i'm failing to do it, i installed meteor and did a git clone. When trying to run `meteor` on plexrequests directory, it doesn't start it 
```
plex@maga:~/plexrequests-meteor$ meteor 
Killednloading meteor-tool@1.1.10...         [==========================] 100% 0.0s
```
thats all the output i get, i don't know if i can enable any more detailed output.

**Comment by rigrassm** [comment]
The initial run can take a little bit, if it hangs, try re cloning
Plexrequests and running it again

**Comment by rigrassm** [comment]
Closing as this is a meteor issue and not an issue with Plexrequests.
