### ISSUE TITLE
Install on raspberry

### ISSUE THREAD

**Issue by obouallou** [lokenx/plexrequests-meteor#437]
Hello, 

I'm trying to get plexrequests working on a raspberry, but I encountered the following error 👍 

`While building plugin `compileScssBatch` in package `fourseven:scss`:
   error: couldn't run `npm shrinkwrap`: Command failed: npm ERR! Error: Problems were encountered
   npm ERR! Please correct and try again.
   npm ERR! missing: try-thread-sleep@^1.0.0, required by spawn-sync@1.0.15
   npm ERR!     at shrinkwrap_ (/home/pi/meteor/dev_bundle/lib/node_modules/npm/lib/shrinkwrap.js:30:15)
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/lib/shrinkwrap.js:24:5
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/lib/ls.js:45:30
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:130:5
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
   npm ERR!     at cb (/home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
   npm ERR!     at cb (/home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
   npm ERR!     at cb (/home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
   npm ERR! If you need help, you may report this *entire* log,
   npm ERR! including the npm and node versions, at:
   npm ERR!     <http://github.com/npm/npm/issues>

   npm ERR! System Linux 4.4.38-v7+
   npm ERR! command "/home/pi/meteor/dev_bundle/bin/node" "/home/pi/meteor/dev_bundle/bin/npm" "shrinkwrap"
   npm ERR! cwd /opt/plexrequests/packages/scss/.npm/plugin/compileScssBatch-new-12xq5fu
   npm ERR! node -v v0.10.40
   npm ERR! npm -v 1.4.28
   npm ERR!
   npm ERR! Additional logging details can be found in:
   npm ERR!     /opt/plexrequests/packages/scss/.npm/plugin/compileScssBatch-new-12xq5fu/npm-debug.log
   npm ERR! not ok code 0
   npm ERR! Error: Problems were encountered
   npm ERR! Please correct and try again.
   npm ERR! missing: try-thread-sleep@^1.0.0, required by spawn-sync@1.0.15
   npm ERR!     at shrinkwrap_ (/home/pi/meteor/dev_bundle/lib/node_modules/npm/lib/shrinkwrap.js:30:15)
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/lib/shrinkwrap.js:24:5
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/lib/ls.js:45:30
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:130:5
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
   npm ERR!     at cb (/home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
   npm ERR!     at cb (/home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
   npm ERR!     at /home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
   npm ERR!     at cb (/home/pi/meteor/dev_bundle/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
   npm ERR! If you need help, you may report this *entire* log,
   npm ERR! including the npm and node versions, at:
   npm ERR!     <http://github.com/npm/npm/issues>

   npm ERR! System Linux 4.4.38-v7+
   npm ERR! command "/home/pi/meteor/dev_bundle/bin/node" "/home/pi/meteor/dev_bundle/bin/npm" "shrinkwrap"
   npm ERR! cwd /opt/plexrequests/packages/scss/.npm/plugin/compileScssBatch-new-12xq5fu
   npm ERR! node -v v0.10.40
   npm ERR! npm -v 1.4.28
   npm ERR!
   npm ERR! Additional logging details can be found in:
   npm ERR!     /opt/plexrequests/packages/scss/.npm/plugin/compileScssBatch-new-12xq5fu/npm-debug.log
   npm ERR! not ok code 0
`

Any idea why please ?

**Comment by rigrassm** [comment]
Try running meteor in a fresh clone of the Plexrequests repo. If that doesn't work reinstall meteor and Plexrequests.
