### ISSUE TITLE
Sonarr works but CP does not: { [Error: ESOCKETTIMEDOUT] stack: [Getter] }

### ISSUE THREAD

**Issue by almontef** [lokenx/plexrequests-meteor#442]
I am running Meteor 1.4.2.7 with the latest PlexRequests. I am on Windows 10. 

My CouchPotato and Sonarr are running on a different server running Windows 7. 

Sonarr works just fine, but when I attempt to test the CouchPotato connection from the PlexRequests admin page, I get the following error in the console:

{ [Error: ESOCKETTIMEDOUT] stack: [Getter] }

I don't get any other errors nor do I get any errors in the CP logs. 

The strange thing is that Sonarr which is on the same system as CP works fine. Also, I can connect correctly from the Windows 10 browser (where plexrequests is installed) to the Sonarr and CP web GUIs. I can also remote desktop from my Windows 10 to the Windows 7 system no problem. 

Tried using both IP address and host name with the same results. I am at a loss at what the problem could be being that I can access the CP GUI from this system. 

If there is any assistance that could be provided to point me in the right direction, it would be greatly appreciated. Thanks in advance.

**Comment by rigrassm** [comment]
Please post the CouchPotato settings you've tried.

Also, make sure that you are clicking the update button and song any changes before you try testing any changes.

**Comment by rigrassm** [comment]
Any update on this?

**Comment by almontef** [comment]
I am closing this issue as I no longer want to pursue. Thanks for your help!
