### ISSUE TITLE
Unable to Update via Git Gui

### ISSUE THREAD

**Issue by Fiala06** [lokenx/plexrequests-meteor#444]
Followed the Updating section here: http://8bits.ca/posts/2015/installing-plex-requests-on-windows/

Said it successfully update yet I'm still on the same version I was before. I have reboot the system also.

Here is what I get now after a reboot and supposedly updated successfully:

![plreq](https://cloud.githubusercontent.com/assets/5183146/23132295/f4eb87f8-f741-11e6-9927-c265935d0b92.png)

Any ideas for what to try? Thanks!

**Comment by rigrassm** [comment]
You need to do a git pull after the git fetch.

I recommend stopping Plexrequests, running git fetch, git pull and then
restart.

**Comment by Fiala06** [comment]
Sorry not really familiar with git.  I don't see anything with Pull from the menus. I'm assuming its in Git Gui?

**Comment by rigrassm** [comment]
Seeing as it's a major part of git I would assume so. I don't have a
Windows machine to look at and I'm on mobile right now but I'm almost
positive there are some guides out there on how to do a git pull from the
git GUI.

Try doing a quick Google search for "git pull in git gui Windows"

**Comment by Fiala06** [comment]
Humm well nothing seems to work from the top searches. If I just re-download the files and replace them all in the directory will that work?

**Comment by Fiala06** [comment]
Got it figured out found this thread: https://www.reddit.com/r/PleX/comments/43dfd4/how_to_update_plex_requests/

Just navigate to the folder that contains plexrequests in command prompt, and issue the command "git pull". Then type meteor to relaunch.
