### ISSUE TITLE
Requested Movie on Radarr needs release date parameter

### ISSUE THREAD

**Issue by galli-leo** [lokenx/plexrequests-meteor#445]
Hey, Radarr Dev here.

I noticed some Radarr users having issues where the folder generated by Radarr for a movie requested through PlexRequests have a 0 instead of a year. At the moment Radarr needs the release date and year in the add movie request to properly create the folder.

**Comment by basmith7** [comment]
I am having this problem if any more info is needed.

**Comment by rigrassm** [comment]
Yea, I haven't had a chance to look at it yet but I will be tonight and
i'll get the fix pushed out. I was the one to initially report it but if
you get any other reports you can point them here for info.

**Comment by galli-leo** [comment]
@rigrassm If you need anything more feel free to hop on our discord :) (https://discord.gg/NWYch8M)

**Comment by rigrassm** [comment]
Awesome, just joined the room. I'll hit y'all up there is I run into any
issues and when I get the update pushed out.
