### ISSUE TITLE
Docker hasn't been updated in months

### ISSUE THREAD

**Issue by dawtmaytrikx** [lokenx/plexrequests-meteor#447]
For whatever reasons, this docker container is the only version I've succesfully got running on my machine. Since I've switched to Radarr I haven't been able to use it properly though, because the docker container is several months out of date. Would you mind taking a look at updating it? Thanks :)

**Comment by rigrassm** [comment]
Right now, the Linuxserver.io docker container for Plexrequests is the best
option. It was last built 18 hours ago it looks like.

https://hub.docker.com/r/linuxserver/plexrequests/

**Comment by dawtmaytrikx** [comment]
Unfortunately that container doesn't work for me. See the error below.

> 2017-03-05 13:13:22 [initandlisten] MongoDB starting : pid=255 port=27017 dbpath=/config/db 64-bit host=PlexRequests
> 2017-03-05 13:13:22 [initandlisten] db version v3.2.9
> 2017-03-05 13:13:22 [initandlisten] git version: 22ec9e93b40c85fc7cae7d56e7d6a02fd811088c
> 2017-03-05 13:13:22 [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
> 2017-03-05 13:13:22 [initandlisten] allocator: tcmalloc
> 2017-03-05 13:13:22 [initandlisten] modules: none
> 2017-03-05 13:13:22 [initandlisten] build environment:
> 2017-03-05 13:13:22 [initandlisten]     distmod: ubuntu1604
> 2017-03-05 13:13:22 [initandlisten]     distarch: x86_64
> 2017-03-05 13:13:22 [initandlisten]     target_arch: x86_64
> 2017-03-05 13:13:22 [initandlisten] options: { storage: { dbPath: /config/db"" } }"
> 2017-03-05 13:13:22 [initandlisten] exception in initAndListen std::exception: boost::filesystem::status: Permission denied: \"/config/db/storage.bson\", terminating
> 2017-03-05 13:13:22 [initandlisten] dbexit:  rc: 100
> 2017-03-05 13:13:22 
> 2017-03-05 13:13:22 /app/bundle/programs/server/node_modules/fibers/future.js:278
> 2017-03-05 13:13:22 						throw(ex)
> 2017-03-05 13:13:22 						      ^
> 2017-03-05 13:13:23 Error: failed to connect to [127.0.0.1:27017]
> 2017-03-05 13:13:23     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
> 2017-03-05 13:13:23     at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
> 2017-03-05 13:13:23     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
> 2017-03-05 13:13:23     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
> 2017-03-05 13:13:23     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
> 2017-03-05 13:13:23     at new Mongo.Collection (packages/mongo/collection.js:102:1)
> 2017-03-05 13:13:23     at AccountsServer.AccountsCommon (accounts_common.js:23:18)
> 2017-03-05 13:13:23     at new AccountsServer (accounts_server.js:16:5)
> 2017-03-05 13:13:23     at Package (globals_server.js:5:12)
> 2017-03-05 13:13:23     at /app/bundle/programs/server/packages/accounts-base.js:1814:4
> 2017-03-05 13:13:23     - - - - -
> 2017-03-05 13:13:23     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
> 2017-03-05 13:13:23     at [object Object].emit (events.js:106:17)
> 2017-03-05 13:13:23     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
> 2017-03-05 13:13:23     at [object Object].emit (events.js:98:17)
> 2017-03-05 13:13:23     at Socket.<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
> 2017-03-05 13:13:23     at Socket.emit (events.js:95:17)
> 2017-03-05 13:13:23     at net.js:441:14
> 2017-03-05 13:13:23     at process._tickCallback (node.js:458:13)

**Comment by rigrassm** [comment]
Looks like a permissions issue.

    2017-03-05 13:13:22 [initandlisten] exception in initAndListen
std::exception: boost::filesystem::status: Permission denied:
"/config/db/storage.bson", terminating

Gotta make sure the user and group the container is running as has the
correct access to the files in the config directory.

**Comment by lokenx** [comment]
Let me know which Docker container you're using? One is with mine that I can check, but one of them is under another user's--mine should be up to date with GitHub, the other I'm not sure!

Will re-open once have more info!
