### ISSUE TITLE
Typos: Sonarr information on Radarr setup page

### ISSUE THREAD

**Issue by desimaniac** [lokenx/plexrequests-meteor#451]
Looks like some information needs to be updated for radarr:

"Enter your API from Radarr. It can be found in Sonarr Settings -> General." 
to
"Enter your API from Radarr. It can be found in **Radarr** Settings -> General."

"Enter the port used by Radarr. The default is 8989." 
to 
"Enter the port used by Radarr. The default is **7878**."

**Comment by rigrassm** [comment]
Thanks again for the Pull request

**Comment by desimaniac** [comment]
Np. Sorry about leaving this issue open...I had forgotten that I had created it.

**Comment by rigrassm** [comment]
No problem at all, just doing a bit of way overdue house keeping lol
