### ISSUE TITLE
Movies downloaded in Radarr not updating as "available" on Requests page. 

### ISSUE THREAD

**Issue by desimaniac** [lokenx/plexrequests-meteor#452]
This is even after waiting for the hourly updates (log below).

![image](https://cloud.githubusercontent.com/assets/5501908/23583550/40f9635c-010d-11e7-96cb-701572b26c6e.png)

Radarr Ver. 0.2.0.375
Plex Request Version: 1.20.2

**Comment by rigrassm** [comment]
Fixed with v1.20.9 release.

**Comment by desimaniac** [comment]
Yup. Very old. Sorry again!

**Comment by rigrassm** [comment]
No worries at all, I actually just got this merged into master (it's been
in dev-testing but never got merged) so I'm glad this was still here to
reminds me of that.
