### ISSUE TITLE
Error Approving Movies

### ISSUE THREAD

**Issue by hrc1079** [lokenx/plexrequests-meteor#454]
Sonarr is working with no issues but an having an issue with adding movies.  I've set up Radarr and am successfully connecting to the server and retrieving profiles.  Searching movies is fine and requesting them works with no issue.  When I go to "Approve" I get the following error -

"Unable to approve (movie) please try again"

This is happening for every movie.  Any ideas?

Branch: master
Version: 1.20.2

**Comment by brandonshough** [comment]
Seeing the same issue with the following error.

"Status of downloaded content must be a boolean"

Radarr is on version **0.2.0.535**
Plex Requests is on version **1.20.2**

**Comment by lokenx** [comment]
Can you guys try updating, a PR was merged for this I believe!

**Comment by xandora** [comment]
I freshly reinstalled 10 minutes ago, still getting this error when adding movies. However, I did pull across my .meteor folder, could that be causing the error?

**Comment by jeradM** [comment]
Did you choose a quality profile in Radarr settings?

**Comment by xandora** [comment]
I think the Radarr settings field is forgetting the quality profile. I can set it, but when I got back in, the dropdown is empty again. Either way, I'm still getting an `expected string...` error in the console ouput.

**Comment by lokenx** [comment]
And you do hit save/update settings and such after setting it? Just making
sure!

Try without moving your whole meteor folder. There should be a local/DB one
you can move to keep your database though!

**Comment by AngryNoodlez** [comment]
Hey,

I've had a similar problem, though I've not seen any errors in the logs.

Master branch v1.20.0 is working fine for me - no issues with approving/requesting Radarr movies with Couchpotato disabled.

Updated to master branch v1.20.3 today and could no longer request or approve movies. I've pushed myself back to v1.20.0 for now, so everything is working OK for me.

**Comment by AngryNoodlez** [comment]
So since my last post, and in the last couple of days, mobile users stopped being able to request whereas users on a PC were still OK. As of this morning, nobody can request on any device. I just get "Couldn't submit request, please try again!" when requesting either a movie or a TV show. Sonarr & Radarr tests are OK from the Admin menu, and Couchpotato is disabled.

Nothing in the logs at all.. so I'm not entirely sure what could be causing it.

![image](https://cloud.githubusercontent.com/assets/11348750/24739722/4307aafe-1a95-11e7-89cc-598eb4ccbccc.png)

**Comment by AngryNoodlez** [comment]
After having a dig around - if I turn off the global require approval setting I no longer get the issues.

**Comment by lokenx** [comment]
@brandonshough your error should be fixed now as of 1.20.4.

I don't run Radarr so I'll have to get that installed and working this week to have a look here as it seems to be primarily with Radarr--or are CouchPotato people having issues too?

**Comment by rigrassm** [comment]
Fixed by https://github.com/lokenx/plexrequests-meteor/commit/fa39630c3f9975e6a958d15a759c15c009136d2a
