### ISSUE TITLE
Can't Request Existing Movies (CouchPotato)

### ISSUE THREAD

**Issue by aporzio1** [lokenx/plexrequests-meteor#455]
I can add TV Shows no problem, but when I try to add a movie the log show the following error

`Status of downloaded content must be a boolean`

**Comment by crotinger** [comment]
Seeing the the same thing. Looks to be only presented when a user requests something that already exists in couchpotato.

**Comment by lokenx** [comment]
Are you both on the latest version (1.20.3) and using CouchPotato?

**Comment by crotinger** [comment]
I am using latest of both.

**Comment by lokenx** [comment]
Can you let me know if you have approvals enabled?

**Comment by lokenx** [comment]
This should be solved now on `1.20.4` so please update! If not let me know and can re-open.

**Comment by crotinger** [comment]
I'll update tonight. FYI I did not have it set to require approvals.

**Comment by lokenx** [comment]
OK! I found the bug earlier in the logic before approvals are checked (no
need to approve if it exists already) so you should hopefully be good now.

**Comment by crotinger** [comment]
Very fair point. The reported error has cleared with the update.
