### ISSUE TITLE
Would it be out of the question to add a ebooks feature?

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [lokenx/plexrequests-meteor#457]
I know that this is primarily Plex-oriented, and they have no support for ebooks, but Plex Requests is pretty nice even as a general purpose request server. It would be nice if my users could request books or periodicals on another tab, and have it look them up on Amazon for the poster/cover.

**Comment by lokenx** [comment]
I sincerely doubt this would ever get added, and definitely not before the existing music/headphones request. Sorry!

**Comment by NoMoreNicksLeft** [comment]
That's ok. I'll just have to find better software then.
