### ISSUE TITLE
Add pushbullet notifications to specific device ID

### ISSUE THREAD

**Issue by mzaur** [lokenx/plexrequests-meteor#464]
Please add the ability to add the device ID for pushbullet notifications (like in Sonarr)

Thank you!

**Comment by rigrassm** [comment]
Addressed this in #470 and will be working on it. Going to be working on getting this pushed out soon.

**Comment by JagandeepBrar** [comment]
I have added support for device IDs, check pull request #500.

**Comment by JagandeepBrar** [comment]
This has now been implemented with #503, so the issue can be closed!

**Comment by Qw-in** [comment]
Thanks
