### ISSUE TITLE
New Users not showing up in Plex Requests.

### ISSUE THREAD

**Issue by Rikumo1978** [lokenx/plexrequests-meteor#467]
Hello, since setting up Plex Requests, I have imported all my users like normal. Since then I have added 6 new Users to Plex, but their names aren't showing up in the Users tab in Plex Requests. How do I tell Plex Requests to rescan the Plex Users List? Thank you! Been fighting this for a month and have gotten nowhere. So it's time to ask the experts! :)

**Comment by Rikumo1978** [comment]
Still hoping to get some insight into this issue!

**Comment by lokenx** [comment]
Sorry for not replying soon! It should update every time it checks but I'm rusty so I'll have a look at code tonight or tomorrow and see what's up for you!

**Comment by Rikumo1978** [comment]
Best thing I've heard all week! Thank you so much! :-)

**Comment by lokenx** [comment]
Can  let me know your version and OS running on?

**Comment by lokenx** [comment]
The list should get updated every time you navigate to the admin settings > user page. This asks the server to `permissionsUpdateUsers` which gets your Plex friends list and adds or updates them in the permissions database. It logs on any database errors, but not success, and doesn't log that it runs or fails to run which should change. That code doesn't look like it's changed in awhile.

Is your Plex token still valid and up to date?

**Comment by Rikumo1978** [comment]
I believe I know what the issue is.... I made the rookiest of rookie
mistakes. Im still using an older version lol. Much older. I guarantee you
if I upgrade versions it will work just fine. For the record it's a
headless Ubuntu server machine. I will comment back once I have done this
upgrade. Thank you.

**Comment by Rikumo1978** [comment]
Just got home from out of state, ran all my updates and everything I repeat, EVERYTHING!! Works as planned. Thank you for your patience. Keep your stuff updated people! Don't be like me xD
