### ISSUE TITLE
Movies added to Radarr without "availability" setting

### ISSUE THREAD

**Issue by raysguy** [lokenx/plexrequests-meteor#479]
Hi

I've noticed movies added to Radarr with PlexRequests are added with the "Availability" field blank so movies added this way are not searched for and requires each to be manually edited to complete the Radarr entry.  Is it possible to specify the desired availability (for me that would be "Announced" in PlexRequests admin settings in the same way "Quality Profile" is selected?  That way it wouldn't require manual input every time someone adds a movie.

Thanks.

**Comment by rigrassm** [comment]
I'll look into this, should be trivial to add.

**Comment by rigrassm** [comment]
Are you referring to the status of the movie, ie. "Announced" "Released" "tba" etc.? If so, this field is actually set by Radarr and isn't something that gets manually set by the API.

**Comment by raysguy** [comment]
No not the status, I'm talking about the "Minimum Availability" field you have to select when you initially add a movie (at the same time as Path, Monitor status and Quality Profile).  It's a dropdown with four options: Announced; In Cinemas; Physical/Web; Pre-db.  Currently PlexRequests passes that field to Radarr as empty so Radarr doesn't know when to start looking for the movie, so it simply doesn't look for it.

**Comment by rigrassm** [comment]
I see what you're talking about now. I'll have to dig into it since the key name and accepted values aren't listed in the API docs.

**Comment by rigrassm** [comment]
So, think I got this up and running correctly in the branch `add-min-availability`. 

@lokenx @raysguy, yall mind checking out that branch and verifying that there aren't any noticeable issues before I merge it into master?

**Comment by lokenx** [comment]
Make PR and set as reviewer and can check tonight or tomorrow 👌🏼

**Comment by rigrassm** [comment]
@lokenx 10-4

**Comment by raysguy** [comment]
Awesome that seems to have worked a treat.  Thanks for getting that added so quickly.
