### ISSUE TITLE
Radarr & Sonarr receiving error: The header content contains invalid characters

### ISSUE THREAD

**Issue by Ulterior83** [lokenx/plexrequests-meteor#485]
You will have to excuse my ignorance as I'm still learning my way around Linux, I'm running my plex server on Ubuntu. When configuring plexrequests through the webui, I keep receiving the Error! result when I try and test the connection.

Simultaneously, when reviewing the terminal output I receive the following error message:

info: Error checking for update: TypeError: The header content contains invalid characters

Is there any insight into this?

**Comment by rigrassm** [comment]
Make sure that you are clicking the "Update Settings" button before trying to test the connection.

Also, is that error coming from Plexrequests or from Radarr and Sonarr?

**Comment by rigrassm** [comment]
Any update on this issue?

**Comment by stephenbrannen** [comment]
I'm experiencing this same behavior, but at one point did not. I can successfully test the connection, but any time that I try to make a request to add a movie/tv show it fails and the following is logged:

Error checking for update: TypeError: The header content contains invalid characters

I am on the most up to date versions of Sonarr, Radarr, and Plex Requests. The last successful request I was able to make was on June 6th.
