### ISSUE TITLE
whole setup just stopped working

### ISSUE THREAD

**Issue by tarnecki** [lokenx/plexrequests-meteor#487]
hi,
i've had this installed on vps for months and worked flawlessly but not it just died?
Application seems to be running:

● plexrequests.service - PlexRequest
   Loaded: loaded (/etc/systemd/system/plexrequests.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-09-13 08:50:40 UTC; 9s ago
 Main PID: 4140 (node)
    Tasks: 54 (limit: 4915)
   CGroup: /system.slice/plexrequests.service
           ├─4140 /root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.brows
           └─4233 /root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.brows

Sep 13 08:50:40 localhost systemd[1]: Started PlexRequest.
Sep 13 08:50:43 localhost meteor[4140]: Even with METEOR_ALLOW_SUPERUSER or --allow-superuser,
Sep 13 08:50:43 localhost meteor[4140]: directory will be incorrect if you ever attempt to per
Sep 13 08:50:43 localhost meteor[4140]: a normal user. If you need to fix your permissions, ru
Sep 13 08:50:43 localhost meteor[4140]: from the root of your project:
Sep 13 08:50:43 localhost meteor[4140]:   sudo chown -Rh <username> .meteor/local
Sep 13 08:50:45 localhost meteor[4140]: [[[[[ /opt/plexrequests ]]]]]
Sep 13 08:50:45 localhost meteor[4140]: => Started proxy.
Sep 13 08:50:46 localhost meteor[4140]: => Meteor 1.5.2 is available. Update this project with
Sep 13 08:50:48 localhost meteor[4140]: => Started MongoDB.

I've checked version and i'm already running meteor 1.5.2.

when you go to web address you get:
This site can’t be reached
ERR_CONNECTION_TIMED_OUT

Please advise?

**Comment by rigrassm** [comment]
While logged into the VPS over SSH, try connecting to PlexRequests using the command below.

```
curl -ILv 127.0.0.1:3000
```

Should get some output that looks similar to the output below.
```
* Rebuilt URL to: 127.0.0.1:3000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> HEAD / HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.53.1
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Vary: Accept-Encoding
Vary: Accept-Encoding
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< Date: Wed, 27 Sep 2017 18:26:57 GMT
Date: Wed, 27 Sep 2017 18:26:57 GMT
< Connection: keep-alive
Connection: keep-alive
```

If you get something like that, then the application is running correctly and the issue is likely a networking/routing issue.

**Comment by rigrassm** [comment]
Closing this issue for now after 2 weeks of no response. Please reopen if the issue persists.
