### ISSUE TITLE
<year> in custom notifications always undefined

### ISSUE THREAD

**Issue by bagobones** [lokenx/plexrequests-meteor#490]
I tested out a few different movies that clearly have a year in the movie database but it is always coming back as undefined in the notification message.

**Comment by jrdnlc** [comment]
Same issue here. Hopefully it get's fixed soon @lokenx

**Comment by rigrassm** [comment]
Found the issue yesterday, I'm at a conference today and tomorrow and want to fix a few more things before passing the commits. May possibly be tonight but more likely tomorrow night.
