### ISSUE TITLE
Radarr, movies in separate folders

### ISSUE THREAD

**Issue by jazzy348** [lokenx/plexrequests-meteor#508]
I'm receiving this issue when I have all of my movies in separate folders, any ideas?

I20171109-19:17:10.188(0)? Radarr Movie Post -> Match error: Expected number, got undefined
I20171109-19:17:32.864(0)? Radarr Movie Post -> failed [400] [
I20171109-19:17:32.865(0)?    {
I20171109-19:17:32.865(0)?      "propertyName": "RootFolderPath",
I20171109-19:17:32.865(0)?      "errorMessage": "Invalid Path",
I20171109-19:17:32.865(0)?      "attemptedValue": "/home/media/Movies/",
I20171109-19:17:32.865(0)?      "formattedMessageArguments": [],
I20171109-19:17:32.865(0)?      "formattedMessagePlaceholderValues": {
I20171109-19:17:32.865(0)?        "propertyName": "Root Folder Path",
I20171109-19:17:32.866(0)?        "propertyValue": "/home/media/Movies/"
I20171109-19:17:32.866(0)?      }
I20171109-19:17:32.866(0)?    }
I20171109-19:17:32.866(0)?  ]

**Comment by rigrassm** [comment]
You need to set a quality profile for Radarr.

**Comment by jazzy348** [comment]
Thanks, worked :)

**Comment by rigrassm** [comment]
Try deleting and re-requesting the movies and see if you are able to approve them then.

**Comment by rigrassm** [comment]
Any update on this?

**Comment by jazzy348** [comment]
Nothing seemed to work, not entirely sure why. I have switch to using it on my Windows box instead.

**Comment by rigrassm** [comment]
If you did a full reinstall on the CentOS 7 box it would probably work. Gonna close the issue, open a separate one for this issue if you have any more issues.
