### ISSUE TITLE
movie request

### ISSUE THREAD

**Issue by blissend** [lokenx/plexrequests-meteor#511]
When making a request I get a red popup notice on the bottom of page saying...

> Couldn't submit request, please try again!

In the logs it says...

> Exception while invoking method 'requestMovie' TypeError: Cannot read property 'permAPPROVAL' of undefined
    at [object Object].Meteor.methods.requestMovie (server/methods/search/requestMovie.js:115:1)

This is for version v1.20.13 according to the about page (docker image from linuxserver.io)

When I try again on something different gives same message. This happens on an account with no autoapproval. The request should be sent to couchpotato. It works on my plex account but not this new account I created (originally created via google login with periods in the name, then recreated by deleting old plex account and making new one via email without periods some.email.address@gmail.com -> someemailaddress@gmail.com). What does this error mean? Anything I can do?

**Comment by blissend** [comment]
Just noticed when enabling user tab it shows user with periods in the name. This while technically correct for gmail (gmail accepts periods anywhere in address), it's not correct for the login used for plex (it would fail to login because that account was deleted).

**Comment by rigrassm** [comment]
Can you send a screenshot of the user permission page?

**Comment by blissend** [comment]
https://imgur.com/m9bBCM9 is the page and at the bottom you can see problem account that shouldn't exist

**Comment by rigrassm** [comment]
Does that user still show up in your friends list on Plex?

**Comment by blissend** [comment]
No it doesn't from what I can see https://imgur.com/a/0CKNo

**Comment by rigrassm** [comment]
It looks like it may be getting caused from that switch of account names.

You could try the steps below to see if it clears up the issue:

1) Remove that Plex server from Plexrequests by signing into a different
one (gonna put a removal method on my Todo list)

2) Re-add the server to get it to pull in the friends list again (another
Todo list item - refreshing friends).

Let me know if this helps.

**Comment by blissend** [comment]
That works! Simply went to authentication page to get token for a different account and then checked that user page changed. Once it did I signed back into mine to see the user page now shows the user account properly.

Thanks again and yes I second the idea of your todo list 8)
