### ISSUE TITLE
plex request setup

### ISSUE THREAD

**Issue by pilothobs** [lokenx/plexrequests-meteor#512]
Hello

I have downloaded and installed plex requests and am having trouble setting it up. In couch potato and sonarr I can't seem to get it to test. I am not sure what the problem is but I have tried several different local host names and ip addresses. 

Any ideas?

**Comment by rigrassm** [comment]
Make sure you click update settings before trying to test.

**Comment by pilothobs** [comment]
I was able to get CP to work. The question I have now is how does it work in plex. Do I need to put it in the extions folder.

Thanks 

Hobs

**Comment by rigrassm** [comment]
Plex requests is a standalone web application, there's used to be a
different project that did something similar that you loaded as a as a Plex
channel but I haven't kept up with its progress for a long time. It may
still be developed but I'm not sure.
