### ISSUE TITLE
Admin controls redirecting to search

### ISSUE THREAD

**Issue by jdhagan** [lokenx/plexrequests-meteor#513]
I've just installed Plex Requests on my Windows server using the instructions provided. When I log in and go to the Admin page I get the "General" page and can update those settings, but if I click on any of the other links I get a message saying that "You're already signed in" and it redirects to the search page, so I can't set up the connections to Sonarr or Couchpotato.

**Comment by rigrassm** [comment]
Try clearing your browser's cache and then reloading the app.
