### ISSUE TITLE
"Couldn't submit request, please try again!" All non-Plex admins

### ISSUE THREAD

**Issue by jayqwellin** [lokenx/plexrequests-meteor#516]
I recently installed PlexRequests v1.21.0 on a Ubuntu 16.04.3 LTS VM, following instructions from https://github.com/lokenx/plexrequests-meteor/wiki/Installation for install, including the run as service steps. I enabled "Enable user authentication," "Require users to login with their passwords," and "Enable user permissions" under "Authentication" to ensure that requests come from my users. I can log into Plex Requests with both my Plex.tv admin as well as my friends/invited accounts, however only the Plex.tv admin account is able to make requests. Any non-admin account that requests a movie or TV show is greeted with a generic "Couldn't submit request, please try again!" I am using Sonarr for TV shows and CouchPotato for movies, and both appear to work fine under the Plex.tv admin account. If I disable all of the above settings in "Authentication" my users can then make requests without issue, however I do not want to leave my Plex Requests that wide open. For the Plex authorization token I have tested using:
1. The "Get token" function
2. My authentication_token generated from a HTTP POST request as instructed in the Plex forums (https://forums.plex.tv/discussion/129922/how-to-request-a-x-plex-token-token-for-your-app/p1)
In both instances they appear to authenticate successfully (the "Users" tab populates properly in Plex requests), but again my standard users cannot make requests. I have tested granting users "No Approval" and "No Limit" individually as well as both permissions at the same time, no change. 

As I just went through the install process (Saturday/Sunday) I believe I should be fully up to date. I've been scouring trying to find a solution but I have been unsuccessful. Is there a bug I'm not aware of, or have I configured something incorrectly?

**Comment by rigrassm** [comment]
It's a known issue that cropped up after adding the ability to login with
email addresses. There's an open issue about it that I plan to address
after the holidays.

Regular user accounts should be able login without any issues so as a work
around you can convert the Plex home users into regular Plex.tv accounts
and have them login with the username and password. This will be addressed
by the end of next week though if that's not something you want to do in
the meantime.

**Comment by jayqwellin** [comment]
Thank you for the very quick response, I will try that after work


Sent from my Sprint Samsung Galaxy S7.
-------- Original message --------From: Ricky Grassmuck <notifications@github.com> Date: 12/26/17  23:54  (GMT-05:00) To: lokenx/plexrequests-meteor <plexrequests-meteor@noreply.github.com> Cc: jayqwellin <matthew.h.stacey@gmail.com>, Author <author@noreply.github.com> Subject: Re: [lokenx/plexrequests-meteor] "Couldn't submit request, please try
  again!" All non-Plex admins (#516) 
It's a known issue that cropped up after adding the ability to login with

email addresses. There's an open issue about it that I plan to address

after the holidays.



Regular user accounts should be able login without any issues so as a work

around you can convert the Plex home users into regular Plex.tv accounts

and have them login with the username and password. This will be addressed

by the end of next week though if that's not something you want to do in

the meantime.
