### ISSUE TITLE
TV Show Requesting animation not working

### ISSUE THREAD

**Issue by AngryNoodlez** [lokenx/plexrequests-meteor#519]
Hey,

Not a big issue, but the requesting animation when requesting TV Shows isn't working. It's causing some people to duplicate the requests by clicking it multiple times until a successful response is sent to the user. Is this an issue for you too?

Branch: master
Version: v1.21.0

**Comment by AngryNoodlez** [comment]
This is fixed by changing;

https://github.com/lokenx/plexrequests-meteor/blob/e7ee1e1adbdc8dae0a0a43f4956120c08d799b80/client/templates/search/search.js#L96

To;

`        var tvBtn = $( "button.tv-request" )`


I tried changing it to this to keep the format but for some reason lost button styling when using this.
`        var tvBtn = $(event.target).parent().parent()`


Not sure how to do a pull request so will leave this open for a few days and hope you see it.

**Comment by AngryNoodlez** [comment]
Figured out pull request

https://github.com/lokenx/plexrequests-meteor/pull/530

**Comment by rigrassm** [comment]
Fixed with #530
