### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by grregis** [lokenx/plexrequests-meteor#528]
I've downloaded plex requests and set it up, however I thought I could use it to download from couchpotato and sonarr.  When I get to the requests page, I see that I can approve and deny them, however I don't see anything to start the download.  I though I read somewhere that there was a download button, but I can't find it anywhere.

**Comment by rigrassm** [comment]
Plexrequests sends the request to the client(Couchpotato, Radarr etc.). You
have to configure that software to do the actual downloading.

**Comment by grregis** [comment]
I've set it to use the clients and the tests have gone through fine on the admin page, but the requested movies aren't going to CP.

**Comment by rigrassm** [comment]
If you don't have auto approve enabled in the Plex requests settings you'll
need to approve the request first before it will be sent to the client.

**Comment by grregis** [comment]
I approved it a log time ago and it's still hasn't been sent over
![screen shot 2018-02-27 at 6 48 01 pm](https://user-images.githubusercontent.com/36903277/36761976-7334d556-1bef-11e8-8545-1189c834a2db.png)
![screen shot 2018-02-27 at 6 47 42 pm](https://user-images.githubusercontent.com/36903277/36761978-73446034-1bef-11e8-8b4e-6691c910a118.png)

**Comment by rigrassm** [comment]
Did you get any error messages? Can you check the Couchpotato logs to see
if there are any messages about any failed API calls?

**Comment by grregis** [comment]
It looked like I put the api key for the searcher I use for CP in the wrong section.  I corrected on CP, deleted the old request and re-entered it and it when to CP then started downloading just fine.  Thanks for the help.
