### ISSUE TITLE
[Feature Request]  Support HTTPS connection as well as HTTP

### ISSUE THREAD

**Issue by ChrisColotti** [lokenx/plexrequests-meteor#542]
I noticed that if you try and connect to https://<ipaddress>:3000 the connection is refused.  I did not see any documentation on enabling https vs http.  If this is going to be pushed out to users I would want it to respond on SSL connection as I host in docker on an SSL based server.

**Comment by rigrassm** [comment]
While you can connect to the application directly by specifying the port,
you should be using a proxy (nginx, HAproxy etc.) to handle the SSL side of
things.

Free signed certificates can be obtained through LetsEncrypt and a proxy
such as Nginx is fairly trivial to set up with plenty of guides being
available with a simple web search.
