### ISSUE TITLE
Cannot create initial admin account

### ISSUE THREAD

**Issue by bobflem** [lokenx/plexrequests-meteor#543]
Trying to install on a clean Windows Server 2016 build made from scratch today. I have used plexrequests in the past, and decided to come back to it. I installed git, installed chocolatey to install meteor, cloned the repository, and started it with `meteor`.

When I navigate to http://localhost:3000, I am prompted to create a user account on the popup. I click on the link, and it takes me to the admin page, but doesn't hide the popup telling me to create the account. Fine, I can just close the popup. When I close it, all I see is an admin login page asking for an email and a password, and my only option is to "Sign In". When I enter the credentials I would like to use for an admin account, I am given [this error](https://i.imgur.com/COeFgC8.png).

I have tried dropping the user's database using `db.users.drop()` suggested in #205, but no luck there. I have tried `mongo reset` multiple times, tried re-cloning the repository... nothing has helped so far. Is there anything else I can try? Please let me know what other information I can provide to help you help me.

Thank you

Edit: Also, I was using this guide to install plexrequests: http://8bits.ca/posts/2015/installing-plex-requests-on-windows/

**Comment by rigrassm** [comment]
Don't use a clone of the repo, I'm doing work on various parts of the
application and it's likely to have issues as I push commits to it.

Just download and extract the latest release from the releases tab and it
should work for you.

**Comment by bobflem** [comment]
Haha wow... sorry for the slight time waster. I'm glad it was something so simple. Thanks for your help!
