### ISSUE TITLE
I have version 1.21.2, and the about page under admin reports there is an update available.

### ISSUE THREAD

**Issue by deus402** [lokenx/plexrequests-meteor#548]
and yes, i have restarted plexrequests after doing a git pull.

![image](https://user-images.githubusercontent.com/24859724/41828949-b4c0f148-77fd-11e8-8771-d0ec24940743.png)

![image](https://user-images.githubusercontent.com/24859724/41828990-dff5839c-77fd-11e8-9f90-a548f34d663d.png)

**Comment by rigrassm** [comment]
Use the latest release from the releases section of the project rather than
cloning/pulling the project. There are changes in the matter branch that
are not ready to be used right now.

**Comment by deus402** [comment]
https://github.com/lokenx/plexrequests-meteor/blob/master/README.md#installation

> Installation is straightforward: please update to Meteor 1.2.1, clone the repo, cd into the directory, and run meteor.

`¯\(°_o)/¯`
