### ISSUE TITLE
Sonarr and Port change

### ISSUE THREAD

**Issue by damiantje99** [lokenx/plexrequests-meteor#55]
Hi,

First of all, you did an hell of an job with this! My compliments!

Now my questions, are you already busy with adding Sonarr? And where can I change the default port? Right now its 3000, but I want to change it.

Kind Regards

**Comment by lokenx** [comment]
Sonarr support has been added as of commit 2dee721, please refer to issue #19 for future updates.

The port 3000 is a Meteor specific thing, not the app. You would have to set the ROOT_URL environmental variable to a different port, or whatever you wanted.

**Comment by damiantje99** [comment]
Thanks for your response, but I have no idea where I can find this "ROOT_URL" and how the Sonarr intergration works. (Noob). For the ROOT_URL, can you tell me where I can edit this? And for Sonarr, does it mean that people can request tv shows? if so, than how?

Thanks!

**Comment by hthighway** [comment]
@damiantje99 

instead of lauching it with just 
```meteor```
use
```ROOT_URL=http://YOUR_IP_ADDRESS:xxxx/ meteor```
WHERE xxxx is what ever port you want to use

**Comment by lokenx** [comment]
Thanks @hthighway !

Yes, just like for Movies, users can select TV and search for a Series. Series are then added to Sonarr if enabled, or just added to the collection in the app. Settings for all the different apps can be configured at the `http://localhost:3000/admin` interface (or whatever you've changed it to) within the Settings collection. There are also status pages for each (links in the admin interface) to make sure things are up and running.

**Comment by damiantje99** [comment]
@hthighway Thanks, ill try that!

@lokenx How can I update to the version with Sonarr support? Or do I need to download the ZIP-File again?

**Comment by lokenx** [comment]
What platform are you running on? How did you get it installed initially? The preferred way is using Git so you can easily switch branches and update to the latest versions. If you're running Windows please refer to [this](http://8bits.ca/blog/installing-plexrequests-windows/) blog post.

**Comment by damiantje99** [comment]
@lokenx I found it! Thank you very much!

**Comment by jrudio** [comment]
To change the port just do 

    meteor --port <port number>

**Comment by damiantje99** [comment]
@jrudio 

Found it, thank u!
