### ISSUE TITLE
Error on boot - => Exited with code: 8

### ISSUE THREAD

**Issue by FoobyGitHub** [lokenx/plexrequests-meteor#559]
Just done a fresh install of the app.

Used Meteor to create project folder and exported the tar of 1.21.2.

I added the en_US to locales which fixed the mongodb problem, but now i'm getting this and it wont start.

No change detected for the collection tv
No change detected for the collection movies
No change detected for the collection settings
No change detected for the collection permissions

/opt/plexrequests-meteor/plexrequests/.meteor/local/build/programs/server/app/server/main.js:1
(function(Npm, Assets){(function(){import { Meteor } from 'meteor/meteor';
                                   ^^^^^^
SyntaxError: Unexpected reserved word
    at /opt/plexrequests-meteor/plexrequests/.meteor/local/build/programs/server/boot.js:241:30
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/plexrequests-meteor/.meteor/packages/meteor-tool/.1.1.10.1ikbw7f.wqs++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /opt/plexrequests-meteor/plexrequests/.meteor/local/build/programs/server/boot.js:137:5
Exited with code: 8
Your application is crashing. Waiting for file change.

any ideas?

plexmeteor@arkp-nas:~/plexrequests$ ls -lh
total 5.7M
drwxr-xr-x   5 plexmeteor plexmeteor 4.0K Feb 16  2018 client
-rw-r--r--   1 plexmeteor plexmeteor  361 Feb 16  2018 docker-compose.yml
-rw-r--r--   1 plexmeteor plexmeteor   33 Feb 16  2018 Dockerfile
drwxr-xr-x   3 plexmeteor plexmeteor 4.0K Feb 16  2018 include
drwxr-xr-x   5 plexmeteor plexmeteor 4.0K Feb 16  2018 lib
-rwxr-xr-x   1 plexmeteor plexmeteor 1.2K Feb 16  2018 LICENSE.txt
drwxr-xr-x 186 plexmeteor plexmeteor 4.0K Feb 16  2018 node_modules
-rw-r--r--   1 plexmeteor plexmeteor  193 Feb 16  2018 package.json
-rw-r--r--   1 plexmeteor plexmeteor  59K Feb 16  2018 package-lock.json
drwxr-xr-x   4 plexmeteor plexmeteor 4.0K Feb 16  2018 packages
-rw-r--r--   1 plexmeteor plexmeteor   25 Feb 16  2018 packages.json
drwxr-xr-x   2 plexmeteor plexmeteor 4.0K Feb 16  2018 private
drwxr-xr-x   2 plexmeteor plexmeteor 4.0K Feb 16  2018 public
-rwxr-xr-x   1 plexmeteor plexmeteor 5.8K Feb 16  2018 README.md
drwxr-xr-x   5 plexmeteor plexmeteor 4.0K Feb 16  2018 server
drwxr-xr-x   2 plexmeteor plexmeteor 4.0K Sep  3 18:15 tests
-rw-r--r--   1 plexmeteor plexmeteor 5.5M Sep  3 18:19 v1.21.2.tar.gz
-rw-r--r--   1 plexmeteor plexmeteor    7 Feb 16  2018 version.txt
plexmeteor@arkp-nas:~/plexrequests$ cat /etc/debian_version
10.0

**Comment by FoobyGitHub** [comment]
In solution to this. I deleted the entire folder (including the hidden .meteor) files. Re-downloaded the latest version and its now working. Unsure what was up with it. But its now behaving, just thought i'd post an update to what i did.

**Comment by fryfrog** [comment]
You might also consider Ombi, this hasn't had an update since 2018.
