### ISSUE TITLE
Sonarr Status check

### ISSUE THREAD

**Issue by lokenx** [lokenx/plexrequests-meteor#56]
Currently, if get reply from Sonarr server it counts as up, need to add a check in case we get an unauthorized return message or something similar.

**Comment by jrudio** [comment]
How about checking the status code on        

     try {
            var status = Meteor.http.call("GET", soURL + "/api/system/status/", {headers: {"X-Api-Key":soAPI}, timeout:5000});
          if(status.statusCode === 200){
           // authorized
            return true;
          }
          else{
            // Something else happened
            return false;
          }
        }
        catch (error) {
            //If can't connect error out
            console.log(error)
            return "error";
        }

**Comment by lokenx** [comment]
That should work, because I think it returns `unauthorized` when API key is incorrectly. The catch should return false though so the client side method shows the appropriate response.

**Comment by lokenx** [comment]
Added, as of c646379eb4e9b4d72f4531f17960637a42bb8803
