### ISSUE TITLE
Selecting specific season/episode on TV requests

### ISSUE THREAD

**Issue by camjac251** [lokenx/plexrequests-meteor#58]
Shows are currently only added to Sonarr, not scanned for. It would be nice to allow the user to select an episode at where they left off watching at so it would mark only those episodes for sonarr to grab, and then trigger Sonarr to automatically search for them.

**Comment by lokenx** [comment]
This will be evaluated for both SickRage and Sonarr once v0.5 is pushed out. However, there's no promises it will be implemented as of this moment

**Comment by drzoidberg33** [comment]
I've tried to tackle this. Unfortunately the Sickrage API is quite limiting and doesn't allow you to request specific seasons when adding a new show. I've created a option that works for both Sickrage and Sonarr. My pull request is here: https://github.com/lokenx/plexrequests-meteor/pull/74

**Comment by lokenx** [comment]
So for both SickRage and Sonarr the options are, new episodes going forward or all episodes? Even though Sonarr would be able to support current season and new episodes, SR doesn't and I'm ok with keeping it to those two options for now.

**Comment by drzoidberg33** [comment]
Yep. I would also try and keep it the same for both using the lowest common denominator.

**Comment by camjac251** [comment]
Just because Sickrage doesn't support it, doesn't mean Sonarr users should suffer for not having this option. PlexRequests is pointless if it can't download from a certain episode on and auto search for those episodes.
