### ISSUE TITLE
Re-write CouchPotato/SickRage test pages

### ISSUE THREAD

**Issue by lokenx** [lokenx/plexrequests-meteor#59]
Get rid of JavaScript inside the HTML template and move it to templates helpers etc. Use the Sonarr page as a starting point.

**Comment by jrudio** [comment]
:) Want me to do it?

**Comment by lokenx** [comment]
Lol feel free! It's low priority so no rush.

**Comment by lokenx** [comment]
Done, thanks to @jrudio
