### ISSUE TITLE
 { [Error: ESOCKETTIMEDOUT] stack: [Getter] } Error When Accessing Setup Pages

### ISSUE THREAD

**Issue by dcplaya** [lokenx/plexrequests-meteor#60]
Whenever I try to access couchpotato/Sonarr/Sickrage setup pages via the admin page, I get

 { [Error: ESOCKETTIMEDOUT] stack: [Getter] }

I am on CentOS7 running Meteor 1.1.0.2

**Comment by lokenx** [comment]
Are you running Meteor with any special parameters? Or are you running in production mode with NodeJS?

Can you navigate to the pages manually `http://localhost:3000/couchpotato` ? Does the Plex authentication page work `http://localhost:3000/plex` ?

**Comment by dcplaya** [comment]
I can navigate to couchpotato/plex/sonarr by going there without using the link on the admin page (or by clicking the link and then refreshing the page). 

The socket timeout error was due to couchpotato not  being set up correctly in the setting page I believe.  I now get no error in my terminal when going to those status pages.

**Comment by lokenx** [comment]
Yes your server console will output errors if something isn't working, that's expected. However, the web page should load regardless as it is suppose to indicate whether there is an error or not: so is this not happening? Or it is, but you've to refresh the page?

(Unrelated, I have noticed my admin interface sometimes requires a refresh to show, not sure if this is an iron:router issue, houston package issue, Meteor issue, or my app.

**Comment by dcplaya** [comment]
Once I fixed the connection issue with CP or Plex, I no longer get errors in the console. But the issue with the webpage not loading when using the link in the admin page is still there. 

Sounds like you have the same issue with the admin page as I have with the status pages.

**Comment by lokenx** [comment]
Something is applying the below style to the body element when clicking on links from the admin interface. Refreshing removes it, opening in a new tab removes it, or directly visiting the URL. So not sure what's adding it.

`style="visibility: hidden;"`

**Comment by lokenx** [comment]
Temporarily fixed by making links open in a new tab, until I can more thoroughly look into it, seems to be an iron:router bug but not sure.

3ab2bbd
