### ISSUE TITLE
Start a version scheme and show it somewhere

### ISSUE THREAD

**Issue by dcplaya** [lokenx/plexrequests-meteor#61]
Start versioning the releases so I know I correctly updated. It can be shown on the main page or in the admin page or anywhere really. It is just helpful to know what version I am on and what version your have released.

**Comment by lokenx** [comment]
I've been meaning to do that for some time just haven't had a chance, I'll move it up the to do list!

**Comment by lokenx** [comment]
Currently releases to the master branch have version numbers, although it's not displayed in the application itself ([seen here](https://github.com/lokenx/plexrequests-meteor/releases)).

For the dev branch not sure what's the best way to handle it, maybe just provide the Git commit hash as it's really just a staging area for new features. Ideas welcome though!

**Comment by dcplaya** [comment]
I think Couchpotato does git hashes. I am not even sure if I am on their dev branch but it auto updates so I never have to think about it.

Anyway, I think git hashes for the dev branch would be perfectly fine. Its just a way to easily distinguish what I am on and if I should update.

**Comment by lokenx** [comment]
OK, I'll look into adding that as well as stating which branch you're on (and release for master). I wish I could implement auto-updates but haven't a clue how to

**Comment by selthius** [comment]
I would suggest looking at similar projects, such as sickrage og CP. It probably is just something like this:

git fetch
git pull
restart application

**Comment by lokenx** [comment]
Started to create page, but need help creating the new server functions not async to wait for the result to pass to the client side call (I forgot nodejs stuff is all async).

59a08effa0feba713a14ab8df0a289a1ca0838d6

**Comment by jrudio** [comment]
There's a synchronous version of git-rev https://www.npmjs.com/package/git-rev-sync 
You can use a promise on the server (Though I think there's an issue when trying to get the result on the client)
Or, a hacky way you can do is to store the result in the db.

**Comment by lokenx** [comment]
@jrudio thanks for the link to the synchronous version!

**Comment by lokenx** [comment]
This is entirely useless if you're using the downloaded zip file which doesn't contain the `.git` folder (a note is present on the page). But more importantly, when you bundle the app for running in production (how I'm running it) you also lose the git information.

Need to come up with a second way, store commit/branch in a Collection maybe, but how would those downloading the .zip get it. Unless we don't use the commit hash at all, and manually tag things.

**Comment by jrudio** [comment]
How about hardcoding a semantic version in a collection and increment on every commit (obviously). 

Then, on an interval check the repository for a file, say version.txt, and see if the current app is less than the version in the repo. 

If it is then download the .zip and display in the console or even the application that you have a new version downloaded. You can accomplish this easily with the package `request`.
