### ISSUE TITLE
Filter and accept/decline option

### ISSUE THREAD

**Issue by damiantje99** [lokenx/plexrequests-meteor#62]
Hi,

Is it possible to add filter? So people can't request movies with certain words in it?
And is it possible to have users an option to choose if they want to see all te requested movies or just their requested movies?

Its just an idea

Kind Regards

**Comment by jrudio** [comment]
Regarding the filter it seems pretty straightforward... you have a DB collection of blacklisted words and two documents consisting of movie and tv show, they each have an array containing the words. When the user attempts to add a movie/tv show we check against the the collection  and allow/deny the request. 

What do you think @lokenx ?

**Comment by lokenx** [comment]
It could work, what's the use case though? Are you trying to limit people from requested R rated content?

We could also restrict adult movies not being included in search results if that's the particular focus?

http://docs.themoviedb.apiary.io/#reference/search/searchmovie

**Comment by damiantje99** [comment]
@lokenx Yes, I don't want any adult content on my Plex, so it would be nice to block it, or that it can't be found while seaching. 

And what about the option that u can choose as an user to only see their own requested movies or all requested movies?

**Comment by lokenx** [comment]
There's an API parameter we can use that removes adult content from Search results and I'm guessing it's not on by default.

I don't know if we'd change the ability to see all requests, I responded to this via a comment from someone below:

>Afternoon,

>That is indeed intended behaviour. All requests can be seen by everyone, however only the admin (the currentUser) can see who requested content--your users won't know whose requested what, just that it has been.

>We let people know when something has already been requested when they attempt to request it, but if it doesn't show up in the requests list it would be giving opposing information.

>Hope that clears it up!

That feature has been asked before and will be evaluated once the current version has been merged to master.

**Comment by damiantje99** [comment]
Alright, so where can I edit this API Parameter?

And I didn't know that users can't see other usernames, thats very usefull!

I'll wait for this update then, thank you!

**Comment by lokenx** [comment]
I've changed the API to not show `adult_content`, can you check and see if your results are any different?

Yep, that table column isn't show unless you're logged into the admin page.

**Comment by damiantje99** [comment]
Alright, I'll let you know if it worked!

**Comment by lokenx** [comment]
Closing this issue. Can you please create separate issues for the various other things that got brought up in this discussion as it's easier to manage things that way!
