### ISSUE TITLE
Netstat -ano

### ISSUE THREAD

**Issue by damiantje99** [lokenx/plexrequests-meteor#65]
Hi,

Since I installed Plex Request on Windows Server 2012 R2, I get the following Error with meteor:

Error: Couldn't run netstat -ano: {}

It hadn't to do anything with Plex Request but with Meteor.
I found the fix and I thought I share it with you guys.

The fix is the following:

Go to: C:\Users\%username%\AppData\Local\ .meteor\packages\meteor-tool\VERSION\mt-os.windows.x86_32\tools

In there you have a file called run-mongo.js

Open that file with notepad++ or anything similair.

Then on line 87 find the text:

child_process.exec('netstat -ano', function (error, stdout, stderr) {

And replace it with

child_process.exec('netstat -ano', {maxBuffer: 1024 * 1024}, function (error, stdout, stderr) {

That fixed it for me, its not that you guys can do something about it, but maybe if more people get this problem, you have the fix :)

Kind Regards

**Comment by MaartenMol96** [comment]
Worked for me :+1:

**Comment by damiantje99** [comment]
@maartenmol96 I'm glad I could help you.

**Comment by sharepointalex** [comment]
@damiantje99 awesome thx - been searching for a fix for this for a while! Likewise I am running Win 2012R2 x64 :+1:

**Comment by damiantje99** [comment]
@sharepointalex happy to help!

**Comment by lokenx** [comment]
Thanks guys, awesome job!

If this is a Meteor issue, have you posted it on their page, or is it a known fix already?

**Comment by damiantje99** [comment]
No problem, I haven't yet, because I don't know if its only happening to the PlexRequest app. But I will make a topic about it!

**Comment by sharepointalex** [comment]
@damiantje99 where did you find the issue where they use your fix? Only issue I can find is this one - https://github.com/meteor/windows-preview/issues/88 which they closed after someone suggested a reboot fixed it.

**Comment by lokenx** [comment]
Open an issue, and link to our issue/app for context.
Thanks!
On May 13, 2015 11:29 AM, damiantje99 <notifications@github.com> wrote:No problem, I haven't yet, because I don't know if its only happening to the PlexRequest app. But I will make a topic about it!

**Comment by msshariful** [comment]
Awesome, Thank you very much :+1:
