### ISSUE TITLE
Pushover integration not working

### ISSUE THREAD

**Issue by sharepointalex** [lokenx/plexrequests-meteor#66]
I have the pushover setting enabled with my Pushover user key entered in the 'userKey' field and also the 'api_key' field. It is not clear which fields need filling out so tried both? The api field is left blank though.

I get the following error in the console 
![capture](https://cloud.githubusercontent.com/assets/12395485/7586369/28d4e1ac-f8a4-11e4-885b-d1265e36efbb.PNG)

Any ideas?

**Comment by Foebik** [comment]
You need a seperate Application API

Got to https://pushover.net/and log in. Towards the bottom there something that says 
Your Applications  (Register an Application)
Click the link and give it a name; use the drop down that says website. You can add more details or mess around with it further but really all you need to do now is click the "create application" button. It will then tell you your API.

**Comment by sharepointalex** [comment]
Thanks - I've tried this already as I figured it might need an application key but that doesn't work either. I've filled out the API Key and API fields? See attached screenshot from this time round.

It's weird as now it's complaining about a user token but i'm using an application token - I'm starting to think it's the wrong way round in the code?

![capture](https://cloud.githubusercontent.com/assets/12395485/7586974/5dc1efc6-f8aa-11e4-8fc7-cbd965dcc2be.PNG)

**Comment by sharepointalex** [comment]
Ok i've made some more progress - now got 'invalid application token' even though it is correct. Which fields need filling out for Pushover plz?

**Comment by sharepointalex** [comment]
Strange - it seems putting the Application key in the api key and API key field causes the user identifier error - just filling out API key causes the application token error :-(

**Comment by sharepointalex** [comment]
EDIT - figured it out by looking at the code - both User Key and API fields need to be populated. The code doesn't use the API key field for Pushover.

**Comment by lokenx** [comment]
Yes sorry I was in the process of confirming which keys are required exactly. The extra fields are from Sonarr which requires excessive fields and unfortunately messes up the settings page. Glad you figured it out!

For reference, I pre-populate the fields you need to fill out with filler data, if the field is blank, keep it blank!

**Comment by lokenx** [comment]
Unrelated, probably going to look into writing a settings page to make things cleaner.
