### ISSUE TITLE
Reverse proxy issues

### ISSUE THREAD

**Issue by Mirabis** [lokenx/plexrequests-meteor#68]
Hi,

I'm having a bit of trouble with my reverse proxy, as it keeps pointing to the main hostname.com and not the subdirectory hostname.com/request/ in the HTML file itself  (/packages etc)

Manually going to hostname.com/request/packages* works fine. 

Do we need an option like in nzbdrone, couchpotato ? to add a url base? 

`	
< Location /request >

		ProxyPreserveHost On

		ProxyPass   http://10.0.0.24:3000/

		ProxyPassReverse   http://10.0.0.24:3000/

	</Location>
`

**Comment by lokenx** [comment]
I need a bit more information. What keeps pointing to the main hostname? If you're trying to run the application from a sub directory instead of sub domain I can see that giving you issues as I'm making an assumption it's being served from the root.

If that's what you're asking, I can look and see how Meteor handles being served from a sub directory. Personally mines running from http://plex.hostname.com via reverse proxy (nginx).

**Comment by lokenx** [comment]
I have a scribble for nginx that could help, but I think you're using apache I'm guessing?

    $ ROOT_URL=http://site.url/subfolder meteor
   
    ---
    
    server {
    listen      80;
    server_name site.url;
    
    location /subfolder {
        proxy_pass http://site.url:3000;
    }

**Comment by Mirabis** [comment]
Ah yes using Apache2.

hostname.com = root / different app
hostname.com/request/ = PlexRequests 


So when browsing to the root of hostname.com/request it does point to 10.0.0.x:3000/ and i can see the icon and veiw the code through source. Page stays blank because it won't load.

Below is part of the source:
 `
  <script type="text/javascript" src="/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18"></script>
  <script type="text/javascript" src="/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf"></script>
  <script type="text/javascript" src="/packages/json.js?e22856eae714c681199eabc5c0710b904b125554"></script>
  <script type="text/javascript" src="/packages/base64.js?1a63019243b73298e2964e6d4680f25bca657726"></script>
  <script type="text/javascript" src="/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14"></script>
  <script type="text/javascript" src="/packages/logging.js?07e201b648f16be8435a4f666156995eeda0c750"></script>
  <script type="text/javascript" src="/packages/reload.js?
` 

Which won't work, because it points to hostname.com/packages and not hostname.com/request/packages.

Somehow other tools have the urlBase as option, and append /couchpotato/ or w/e.

Pretty sure it can be done by an option in reverse proxy but ... debian 8 and latest updates are being a bit nitpicky on the code i can find online.

**Comment by lokenx** [comment]
Well they're all written in different languages!

But I believe the `ROOT_URL` command is what you need to pass to Meteor when you start it. So instead of just `meteor`, it's `ROOT_URL=http://site.url/subfolder meteor`

Regardless, it's a Meteor thing you need to look into, not so much my app.

**Comment by Mirabis** [comment]
Ah thanks, will look into Meteor and where to pass the url :)

**Comment by Mirabis** [comment]
U may mark this as resolved :)

FIx: http://docs.meteor.com/#/full/absoluteurl

**Comment by lokenx** [comment]
Damn, sorry to hear! Why not just make a new subdomain? http://plex.hostname.com or request.hostname.com

I haven't seen any mention of running a Meteor app out of a sub directory, especially if the `ROOT_URL` variable doesn't help.

**Comment by Mirabis** [comment]
Did some more fiddling with the root Url and i finally managed to get it to append /request/ on the packages etc.

/request/packages/base64..... instead of /packages/base64 which pointed to the root url.

Unfortunately, the main page does not seem to work.

Clicking  "Opps, go back to main page?' points to my home url and displays it lol...

Can PM u the url if u want to see for urself.

**Comment by lokenx** [comment]
Can you let me know what you did to get it to work? I don't run Apache but I can ask someone I know who does.

And does the main page work when you go to it manually, or not at all? Do any of the other pages work such as `/sickrage` or something? Or is it just the links which aren't working right now (and they won't ever work with a sub-directory instead of sub-domain)

**Comment by Mirabis** [comment]
Navigating to the main page directly will show another website as it's pointed to something else. 

I've got it running on http://10.0.0.x:3000/request/

Which I then used in my rev_proxy to point to https://miniws.nl/request/ 

The page is white with a 404 not found, but if u see /source it shows that it appended /request/ and direct links to the packages work.

**Comment by lokenx** [comment]
In the console it's complaining about not finding a bunch of `.css` files as well as creating a `WebSocket` connection even with the `/requests` at the start of it.

Honestly, why not just use a sub-domain? Is fighting with this worth a sub-directory?

**Comment by Mirabis** [comment]
Ah yeh true.... its more of a 20 subdirectories and 1 sub-domain then :P

Don't worry i'll close the issue - and will fiddle with it some more.

**Comment by lokenx** [comment]
You could have the sub-directory redirect to the sub-domain? Give it a little more cohesion?

Let me know if you figure out the sub-directory though!
