### ISSUE TITLE
[dev] sonar doesn't automatically searches after add a serie

### ISSUE THREAD

**Issue by whitecollar17** [lokenx/plexrequests-meteor#69]
Hi,

First of all, great tool!
I use the dev branch to test. 

I found a little bug with the connection of sonar.
When i add a tv serie in plexrequests, its push the tv serie to sonar, but sonar doesn't start with automatic searching.
Is this a bug with the api or a problem with sonar?

CP doesn't have this problem.

**Comment by Foebik** [comment]
By default if you were to add a new series to Sonarr the normal way, it will just add it in and only look for new shows moving forward. You have to manually tell it to look for missing episodes. I don't know of any settings you can access within the GUI to change this behavior (and if you do, let me know :) ). 

BUT, DrJohnZoidberg has posted a few promising items in the Plex forum thread recently that might help with all that. Last I heard he found some "undocumented api parameters" within Sonarr that might just be what we need.

**Comment by lokenx** [comment]
As Foebik mentioned, I believe Sonarr acts like that through web interface too. Closing this, and follow issue #58 for more info regarding adding more specific content into Sonarr and SickRage.
