### ISSUE TITLE
hardcoded links in the admin webgui

### ISSUE THREAD

**Issue by aptalca** [lokenx/plexrequests-meteor#71]
In the admin webgui page, the two links at the top: "Plex Auth Setup" and "Couchpotato Status" are hardcoded to localhost:3000

They should probably point to ../plex and ../couchpotato because when connecting from a remote computer and with port forwarding they don't work.

Thanks

**Comment by lokenx** [comment]
They haven't been hard coded for awhile last I checked: what branch are you running, master or dev? All the links are created the same.

If you're running it somewhere else, are you passing the `ROOT_URL` parameter to Meteor on start up?

**Comment by lokenx** [comment]
You must be on master branch, where I see it's still the old style of link generation. I am merging to the next update tomorrow and it should be fixed for you once you update after tomorrow.

**Comment by aptalca** [comment]
Yes, I was on the master branch.

I actually created a docker container for unRaid (it should work on other platforms as well): https://registry.hub.docker.com/u/aptalca/docker-plexrequests/

It installs meteor, pulls the master branch of plexrequests and runs it in a container

Thanks

**Comment by aptalca** [comment]
Is the dev branch fairly stable? Should I be using that instead?

Thanks

**Comment by lokenx** [comment]
Typically it's just for when I'm implementing something new, for example currently it's TV. It's normally fine, but I honestly wouldn't use it unless you really want TV or you're OK updating frequently (as I commit often, at least I feel like it's far too often). However, I'm merging the branches tomorrow so I wouldn't worry, just check back tomorrow night or Wednesday and they should be in sync.

**Comment by Jeradin** [comment]
@aptalca Thanks so much for creating a plex requests container! I spent far too long trying to make one, but was the first time playing with Docker and didn't getting set up right.

Once the dev is merged with auto update this is going to be super awesome running on my Synology!

**Comment by aptalca** [comment]
Sure, no problem. I updated the docker with an EDGE=1 variable to switch to the dev branch. I also updated the readme with instructions for running the docker from cli.
