### ISSUE TITLE
PlexRequest Reverse Proxy

### ISSUE THREAD

**Issue by damiantje99** [lokenx/plexrequests-meteor#76]
Hi,

I have this problem with PlexRequest as a service. To add PlexRequest to services I use Nssm. PlexRequest uses Meteor to run. I created a .bat file, the .bat file itself is working correctly.
When i'm starting the service I get the error: Windows could not start the PlexRequest service on local computer. It doen't give any errors. Do you guys know what the problem is?

Kind Regards

**Comment by lokenx** [comment]
Did it used to work before? What's changed if it did?

Can you give us your `.bat` script and what do you mean it's working correctly by itself?

**Comment by Foebik** [comment]
I had trouble getting nssm to run it as well. I just use this vbs script with windows sch. The end result is the same.

https://forums.plex.tv/index.php/topic/151899-plex-movie-requests/page-16#entry911858

**Comment by damiantje99** [comment]
@lokenx No, but by an friend of mine, it worked. The .bat file only has this in it:

@echo off
meteor

Thats all.

What I mean with that is, when im running the .bat file, it works. But not when im starting the service.

@Foebik 
If I won't getting it worked as a service, I will look at this, thank you!

**Comment by lokenx** [comment]
You can use a reverse proxy, personally I'm  using nginx. However, you'd want it to go to a subdomain, not a sub-directory as that will be hard to implement (check out #68 ).

Mine is `http://plex.domain.com` and works great running on Ubuntu behind nginx forwarding requests to NodeJS (would work same as just using `meteor`)

**Comment by lokenx** [comment]
Closing, let me know if you need more assistance!
