### ISSUE TITLE
HTTPS with certificate

### ISSUE THREAD

**Issue by MaartenMol96** [lokenx/plexrequests-meteor#78]
Is it possible to start it with https with a certificate?

**Comment by lokenx** [comment]
Running it with just Meteor, no I don't believe so. That is primarily meant for testing and local development, less for production. In production it would be run using NodeJS behind a proxy web server such as nginx. Nginx would be serving it over https and then passing requests back to the Node/Meteor server over plain http (within the local environment or even same machine so http is perfectly fine).I'm running with nginx and node with separate MongoDB server so I'll see if I can get it to work over https but I don't foresee too many issues.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: MaartenMol96Sent: Sunday, May 24, 2015 9:09 AMTo: lokenx/plexrequests-meteorReply To: lokenx/plexrequests-meteorSubject: [plexrequests-meteor] HTTPS with certificate (#78)Is it possible to start it with https with a certificate?

—Reply to this email directly or view it on GitHub.

**Comment by MaartenMol96** [comment]
@lokenx So how can I set the url base for meteor then?

I use IIS8.5 and currently Sonarr, CouchPotato and HTPC Manager works via reverse proxy and application request routing. However, I can't find where to set the url base or something similar

**Comment by lokenx** [comment]
You can't set it within the program itself. You can set it by passing the ROOT_URL variable to Meteor when you start it, or as an environmental variable if running with NodeJS. I set it in the Upstart script on web server.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: MaartenMol96Sent: Sunday, May 24, 2015 9:30 AMTo: lokenx/plexrequests-meteorReply To: lokenx/plexrequests-meteorCc: lokenSubject: Re: [plexrequests-meteor] HTTPS with certificate (#78)@lokenx So how can I set the url base for meteor then?

I use IIS8.5 and currently Sonarr, CouchPotato and HTPC Manager works via reverse proxy and application request routing. However, I can't find where to set the url base or something similar 

—Reply to this email directly or view it on GitHub.

**Comment by MaartenMol96** [comment]
@lokenx So how do you do this?

**Comment by lokenx** [comment]
For meteor you'd start it as:Meteor ROOT_URL=requests.domain.comIf you search the issues for ROOT_URL should find a few posts by one of the guys with more details regarding passing this through to Meteor.*On mobile so can't look it up easily                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: MaartenMol96Sent: Sunday, May 24, 2015 10:01 AMTo: lokenx/plexrequests-meteorReply To: lokenx/plexrequests-meteorCc: lokenSubject: Re: [plexrequests-meteor] HTTPS with certificate (#78)@lokenx So how do you do this?

—Reply to this email directly or view it on GitHub.
