### ISSUE TITLE
[Request] Change error message when user doesn't exist on the server

### ISSUE THREAD

**Issue by camjac251** [lokenx/plexrequests-meteor#84]
It would be nice if when the user isn't on the server but their username does exist, it'll say "You do not have access to this Plex Server" or something like that. And if the plex api allows it, for people that have been invited and haven't accepted the invite, it could tell them to do so.

**Comment by lokenx** [comment]
I'm pretty certain we aren't privy to whether someone has been invited but not accepted yet unfortunately, but we can see what information is returned to work with.

What do you mean by:
> their username does exist

Exist where exactly? A Plex.tv account? We don't talk to Plex.tv for that, we only talk to Plex.tv to get the list of users on the server, not whether or not it's a valid Plex.tv account. We can simply change the error message from, user does not exist, to do not have access but that wouldn't apply in situations where the user does exist they just typed it incorrectly. Or message could be:

> Hmm...that user does not exist, or you do not have access.

**Comment by camjac251** [comment]
Yeah I meant to say their username doesn't exist, but if it is possible to check the plex api for existing usernames, it would be cool to say that they do not have access

**Comment by lokenx** [comment]
I don't know if we can query Plex.tv accounts to see if a user exists, but can have a look.

**Comment by camjac251** [comment]
Also this is another thing, can you please consider again using tvdb for tv shows? Went into the Sonarr IRC and asked what they used, got this response.
![ec0fdf2e35](https://cloud.githubusercontent.com/assets/6313132/7898166/e9649be4-06bc-11e5-8b2e-c3df0c700400.png)

**Comment by lokenx** [comment]
The results are worse, so no. They're working on a new API which is hopefully going to be much better as well as using JSON instead of XML so I'll look at it again then. However, TheMovieDB.org results are great and support other languages well too, I've yet to find an instance where another was better if any real way. And no, you can't compare the search results from the tvdb website, and it's an entirely different search engine than their API.

Regardless, we provide the TVDB id number for Sonarr to get it's show information, so I don't see where the issue is exactly.

**Comment by ajongsma** [comment]
I'm slightly confused now, sorry about that. But if you query query https://plex.tv/api/users to check which users are added to the server, doesn't that automatically mean the user exists while he/she has access to the server?

**Comment by lokenx** [comment]
In that situation yes. He's asking whether we can do a check, when the user isn't on the list of users who have access to the server but who do have a Plex.tv account and it's not just a random username that is being entered. We only check the Plex.tv API for the admin users account to verify if the username is on their shared list.

If the user isn't they could either be typing an invalid Plex.tv account, or a Plex.tv account but that doesn't have access to the server--there's a desire for a differentiation between the two failures.
