### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by archedraft** [lokenx/plexrequests-meteor#85]
I just installed this and it's a really great idea! I am assuming that this only supports sharing the request link on your local network correct?

**Comment by lokenx** [comment]
What do you mean precisely? If you have a web server, or are OK with using a dynamic DNS, you can open it up to the internet for users that are not on your local network. There are a number of issues regarding a proxy server you can look at that talk about doing this.

At the simplest level, you could add a port forward rule to your router sending all requests on port 3000 to whatever internal IP the application is running from. Then anyone who visits `http://yourpublicip:30001` would get the application. However, I would never do this as it can open up lots of security holes in your home network!

**Comment by archedraft** [comment]
You answered my question. I was more wondering if there was some way this app worked like how Plex sends the outside network users to plex.tv and they do not have to know my external IP. I suppose the most secure way would be to give the outside network users restricted VPN access to my home network but at that point would they even remember how to log in each time.

**Comment by lokenx** [comment]
The easiest for the user would be to setup a nginx webserver that can proxy the requests. They visit http://requests.domain.com and nginx shows the application. If you don't have a domain it could work with just your external IP but that's not as friendly obviously.

My users go to http://plex.domain.com with nginx running on a Ubuntu virtual machine.

**Comment by lokenx** [comment]
Closing, if you require more assistance let me know!
