### ISSUE TITLE
[Enhancement] More user friendly settings page

### ISSUE THREAD

**Issue by lokenx** [lokenx/plexrequests-meteor#87]
Currently, changing settings for the various services requires manually changing DB entry fields. In addition, the place to make changes can be visually confusing.

Have started to create a new page at `/settings` that will provide an easier way to enter the various details needed for integrated other services, and linking to the various status pages to confirm things are up and running.

**Comment by lokenx** [comment]
![Settings page](https://cloud.githubusercontent.com/assets/10313292/8392220/f8228d58-1cb0-11e5-868b-e0bbbb39426b.png)

@Jeradin start of settings page, let me know what you were thinking with yours.

**Comment by Jeradin** [comment]
Morning!

Here is some of what I did so far, using autoform and accounts-ui with a few other user packages.

Simple top right login/dropdown, I was considering it to be hidden so Plex users didn't think they needed to login.
![logged-out](https://cloud.githubusercontent.com/assets/209476/8479982/5b9cef6e-2098-11e5-9570-261deb43a52c.png)

Dropdown gives access to project page, about, settings and so on. No more need for houston admin at all.
![logged-in-as-admin](https://cloud.githubusercontent.com/assets/209476/8479992/65ba55b8-2098-11e5-9af6-99d5f3e08cc1.jpg)

Simple checkbox next to the service which enables it reactively. Breaking "API" into separate fields for Hostname/IP and API key. This will be good for all services that need different types of settings.
![start-of-settings](https://cloud.githubusercontent.com/assets/209476/8479998/6a210e58-2098-11e5-95e9-c01f93e5f25a.jpg)

I know the first round of layout for the start of settings page does not look clean, but I was still in the how the heck do I get this to work phase. I have settings auto saving as you type. There is a lot of clean up code related to checking on services and testing connections. Also we would need to rewrite the service calls in the server file to build the URLS as needed.

**Comment by lokenx** [comment]
@Jeradin You're doing pretty much what I was thinking and started on, but just prettier!

Before you go to far, let me commit tonight a few other changes, primarily how the settings collection is being published, and then can work off that as it should make things simpler. And yes, new methods will need to be written for making these changes.

Regarding how to login, we can discuss whether we want an option like you have for them to click, or they have to visit an explicit page like things are currently. I'm leaning towards your way, primarily because I was hoping to add a logout button for users to logout if they so desired. We can then provide an option that's like admin login or something in that drop down. But that's lower priority to getting main page working first.

**Comment by lokenx** [comment]
I lied @Jeradin , I already did the commit that changed the Publish method for the settings to make it more generic, instead of specific to the Couch Potato test page, so as long as you're in sync with dev you're good to go!

**Comment by lokenx** [comment]
Updated page in v0.6. It's not perfect (Meteor issue causes the form to flash/refresh on submit, not the whole page), but much better and can be improved down the line (fully custom instead of based on autoform).
