### ISSUE TITLE
[Request] Logout Button

### ISSUE THREAD

**Issue by Foebik** [lokenx/plexrequests-meteor#89]
Would it be possible to add a log out button?
Other than the normal use cases for having one, it would also make testing so much easier.

Thanks

**Comment by lokenx** [comment]
This has been on my personal to do for awhile so expect it in next version update. Personally, I currently use ingocnito windows for testing, for the interim time at least.

**Comment by Foebik** [comment]
Cool. Well I have had the latest Dev installed for a while now and it seems to be working with no problems for me. I finally got a chance to verify the weekly user limits and those work great too. 

Thanks.

**Comment by lokenx** [comment]
Added in v0.6!
