### ISSUE TITLE
[Request] SSL Support

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#90]
I would like to be able to add a Certificate to the application so it runs in SSL

**Comment by lokenx** [comment]
I don't believe Meteor supports SSL when running it using `meteor`. In a more traditional production environment, your proxy web server (say nginx) would handle the SSL connection as the users would never directly interact with the application server.

In addition, Meteor Up which already makes deployment super easy, supports SSL, see [here](https://github.com/arunoda/meteor-up#ssl-support).

**Comment by skidelo** [comment]
It doesn't look like the API works if CP is using SSL either.  As soon as I change CP to be http only, everything is peachy.

**Comment by lokenx** [comment]
Can you confirm whether it's the same as in #12 ? And what OS you running on, version, etc?

**Comment by lokenx** [comment]
Closing, unless someone else is also having this issue.
