### ISSUE TITLE
[Bug] Mobile page auto hides confirmation menu

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#94]
When you add a tv show it hides the popup menu on add, the only way to see it is to swipe up

![veio9u](https://cloud.githubusercontent.com/assets/751756/8539175/1dd4a29c-2446-11e5-8fe4-527b830fd4b0.gif)

video to show the bug
https://mega.nz/#!d4gQHbCL!Nvg7_YSeqrsSUK9WJXqPMDeDNSJgZB_PAycnfovzogU

**Comment by lokenx** [comment]
Confirmed bug and have some CSS changes that should fix it once I've gotten a chance to test it.

**Comment by lokenx** [comment]
See #115
