### ISSUE TITLE
Retry button

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#95]
So in the event it get the wrong movie or it has German language you can click retry and it will re-search for a new release

**Comment by lokenx** [comment]
We don't handle any of the searching, that is something to deal with on the provider side of things (SickRage/Couch Potato/Sonarr). We provide the request, they determine the quality, language, search frequecy, etc for the content.

I am going to implement a page for users to report issues regarding content (bad quality, wrong content, wrong language, no subtitles, etc) that you can then go and look into/fix. This should hopefully help with this.
