### ISSUE TITLE
[Request] Admin feedback

### ISSUE THREAD

**Issue by pmow** [lokenx/plexrequests-meteor#97]
It would be great to be able to leave notes regarding a request.  For example, when the movie is expected, or issues with a TV show being sourced.

An alternative to this is to implement a ticket/helpdesk system.  Although that is more involved, users could report issues with the server and get help.

**Comment by lokenx** [comment]
Definitely not looking for a ticket/helpdesk system, that's beyond the scope of what we're looking for. Regarding leaving notes or something is interesting, but could be similarly accomplished using #67.

**Comment by lokenx** [comment]
Closing as will not be including a ticket system. And reporting problems etc with content can be followed in #67.
