### ISSUE TITLE
Crashing on cp update

### ISSUE THREAD

**Issue by unixjeff** [lokenx/plexrequests-meteor#98]
It seams to stop responding after it runs

[screenshot](http://i.imgur.com/ueK7obc.jpg)

Any ideas

**Comment by lokenx** [comment]
I'm not sure there's anything wrong? That message is from the scheduler that updates the movie status requests every X hours.

    C:\Users\\Seafile\Development\apps\plexrequests-meteor>meteor
    [[[[[ C:\Users\XXXX\Seafile\Development\apps\plexrequests-meteor ]]]]]

    => Started proxy.
    => Started MongoDB.
    => Started your app.

    => App running at: http://localhost:3000/
       Type Control-C twice to stop.

    I20150731-20:32:15.813(-4) (synced-cron-server.js:63) SyncedCron: Scheduled
    "Update CP download status" next run @Sat Aug 01 2015 00:00:00 GMT-0400 
    (Eastern Daylight Time)

**Comment by unixjeff** [comment]
It just all of a sudden has been crashing, is there a way to maybe wipe the db to see if that's causing the issue?

**Comment by lokenx** [comment]
How are you currently running it, just using `meteor`? If so, the DB is saved inside `.meteor\local\db`. I would simply rename the `local` folder to `localBackUp` or something, and meteor will create a new one on start-up.

**Comment by unixjeff** [comment]
Maybe this info would help
 http://pastebin.com/4EFv6SKq

**Comment by lokenx** [comment]
Honestly, not sure what's causing it. Are things still broken when you cleared your DB? What version are you on?

**Comment by unixjeff** [comment]
Branch: dev
Version: 0.5.4

and yes clearing the DB and starting over fixed it
