### ISSUE TITLE
[Request] intergration with trakt.

### ISSUE THREAD

**Issue by valantislevas** [lokenx/plexrequests-meteor#99]
Hello i want to ask if is possible when we add movie or series if we have the ability to add the movie on trakt watchlist on request..

**Comment by lokenx** [comment]
Thanks for the request. I can't make any promises if this will be implemented, but I'll keep it open for now.

**Comment by lokenx** [comment]
Can you give me some details regarding what you want out of Trakt integration? Doesn't Plex keep track of your watch status? I think adding Trakt is a bit beyond the scope of what the app does.

**Comment by bonyboy** [comment]
The only thing that comes to my mind is if you've created a "Watchlist" in Trakt prior to logging into Plex Requests and instead of going through the search process, you would have an option to load your Trakt Watchlist and make a request from those choices.

It may be helpful for those who have built complex lists in Trakt assuming this is what @valantislevas is referring to.

**Comment by lokenx** [comment]
Ah OK. So you'd want the users to somehow connect with their Trakt lists, not some form of integration from the admin user side of things?

**Comment by bonyboy** [comment]
That is the way I see it. It would be an extra authentication (1 using Plex token and 1 for Trakt authentication).

But @valantislevas may have something entirely different in mind.

**Comment by lokenx** [comment]
For users Trakt authentication would have to happen entirely client side as I store no details regarding them in the app (two local storage variables for logged in/username).

I'm not sure if a API token would be required to use Trakt or just the users token. This has always been the downside of not creating full user accounts and just checking usernames. It may make this beyond the scope of the app right now.

**Comment by bonyboy** [comment]
Looks like [OAuth is optional](http://docs.trakt.apiary.io/#reference/users/lists) when returning a users list.

**Comment by gryphonmyers** [comment]
This would be useful to me. I use Flexget and already monitor my trakt watchlist.
